# Generated by Django 3.0.3 on 2020-04-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0030_lot_ea_delivery_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('deadline', models.DateField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Déclaration de Durabilité',
                'verbose_name_plural': 'Déclarations de Durabilité',
                'db_table': 'operator_declaration',
            },
        ),
    ]
