# Generated by Django 3.0.3 on 2020-04-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_lot_ea_delivery_accepted'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.OperatorDeclaration')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lot')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'operator_lots',
            },
        ),
    ]
