# Generated by Django 3.0.3 on 2020-05-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_operatordepot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatordeclaration',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='operatordepot',
            name='country',
        ),
        migrations.RemoveField(
            model_name='operatordepot',
            name='operator',
        ),
        migrations.DeleteModel(
            name='AcceptedLot',
        ),
        migrations.DeleteModel(
            name='OperatorDeclaration',
        ),
        migrations.DeleteModel(
            name='OperatorDepot',
        ),
    ]
