import {
  biocarburant,
  country,
  deliverySite,
  matierePremiere,
  operator,
  producer,
  productionSite,
} from "common/__test__/data"
import { LotDetails } from "lot-details/types"
import {
  CorrectionStatus,
  DeliveryType,
  Lot,
  LotStatus,
} from "transactions/types"

export const lot: Lot = {
  id: 0,
  year: 2020,
  period: 202001,
  carbure_id: "TEST01",
  carbure_producer: producer,
  unknown_producer: "",
  carbure_production_site: productionSite,
  production_site_certificate: "2BS - KNOWN PSITE",
  unknown_production_site: "",
  production_country: country,
  production_site_commissioning_date: "2000-01-31",
  production_site_double_counting_certificate: "",
  volume: 12345,
  weight: 12345,
  lhv_amount: 1245,
  feedstock: matierePremiere,
  biofuel: biocarburant,
  country_of_origin: country,
  eec: 12,
  el: 0,
  ep: 0,
  etd: 0,
  eu: 0,
  esca: 1,
  eccs: 0,
  eccr: 0,
  eee: 0,
  ghg_total: 11,
  ghg_reference: 83.8,
  ghg_reduction: 86.87,
  ghg_reference_red_ii: 94,
  ghg_reduction_red_ii: 84.23124,
  added_by: producer,
  carbure_supplier: producer,
  unknown_supplier: null,
  supplier_certificate: "ISCC1000 - Vendor",
  transport_document_reference: "DAETEST",
  carbure_client: operator,
  unknown_client: "",
  delivery_date: "2020-01-31",
  carbure_delivery_site: deliverySite,
  unknown_delivery_site: "",
  delivery_site_country: country,
  delivery_type: DeliveryType.Unknown,
  lot_status: LotStatus.Draft,
  correction_status: CorrectionStatus.NoProblem,
  free_field: "",
}

export const lotDetails: LotDetails = {
  lot: lot,
  children_lot: [],
  children_stock: [],
  comments: [],
  errors: [],
  updates: [],
  distance: null,
  parent_lot: null,
  parent_stock: null,
}
