# Generated by Django 4.1.7 on 2023-06-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0016_alter_externaladminrights_right"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecProvisionCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quarter", models.IntegerField()),
                ("year", models.IntegerField()),
                ("operating_unit", models.CharField(max_length=64)),
                ("energy_amount", models.IntegerField()),
                ("remaining_energy_amount", models.IntegerField()),
                (
                    "entity",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.entity"),
                ),
            ],
            options={
                "verbose_name": "Certificat de Fourniture (elec)",
                "verbose_name_plural": "Certificats de Fourniture (elec)",
                "db_table": "elec_provision_certificate",
            },
        ),
    ]
