# Generated by Django 4.1.7 on 2023-07-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_externaladminrights_right"),
        ("elec", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecprovisioncertificate",
            name="quarter",
            field=models.IntegerField(choices=[(1, "T1"), (2, "T2"), (3, "T3"), (4, "T4")]),
        ),
        migrations.CreateModel(
            name="ElecTransferCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("certificate_id", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("ACCEPTED", "ACCEPTED"), ("REJECTED", "REJECTED")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("transfer_date", models.DateField()),
                ("energy_amount", models.IntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transfer_certificates",
                        to="core.entity",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transfer_certificates",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificat de Cession (elec)",
                "verbose_name_plural": "Certificats de Cession (elec)",
                "db_table": "elec_transfer_certificate",
            },
        ),
    ]
