# Generated by Django 4.1.7 on 2023-07-27 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_externaladminrights_right"),
        ("elec", "0002_alter_elecprovisioncertificate_quarter_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="elecprovisioncertificate",
            unique_together={("entity", "quarter", "year", "operating_unit")},
        ),
    ]
