# Generated by Django 4.1.7 on 2023-08-01 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_externaladminrights_right"),
        ("elec", "0003_alter_elecprovisioncertificate_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elecprovisioncertificate",
            old_name="entity",
            new_name="cpo",
        ),
        migrations.AlterUniqueTogether(
            name="elecprovisioncertificate",
            unique_together={("cpo", "quarter", "year", "operating_unit")},
        ),
    ]
