# Generated by Django 4.1.7 on 2023-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0004_rename_entity_elecprovisioncertificate_cpo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electransfercertificate",
            name="accepted_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
