# Generated by Django 4.1.7 on 2023-09-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_carburenotification_type"),
        ("elec", "0006_electransfercertificate_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecprovisioncertificate",
            name="cpo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.entity"),
        ),
    ]
