# Generated by Django 4.1.7 on 2023-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0007_alter_elecprovisioncertificate_cpo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecprovisioncertificate",
            name="energy_amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="elecprovisioncertificate",
            name="remaining_energy_amount",
            field=models.FloatField(),
        ),
    ]
