# Generated by Django 4.1.7 on 2023-11-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_carburenotification_type"),
        ("elec", "0007_alter_elecprovisioncertificate_cpo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecChargePointApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("ACCEPTED", "ACCEPTED"), ("REJECTED", "REJECTED")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elec_charge_point_applications",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription points de recharge",
                "verbose_name_plural": "Inscriptions points de recharge",
                "db_table": "elec_charge_point_application",
            },
        ),
        migrations.CreateModel(
            name="ElecChargePoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("charge_point_id", models.CharField(max_length=64)),
                (
                    "current_type",
                    models.CharField(choices=[("AC", "Courant alternatif"), ("DC", "Courant continu")], max_length=2),
                ),
                ("installation_date", models.DateField()),
                ("lne_certificate", models.CharField(blank=True, max_length=64, null=True)),
                ("meter_reading_date", models.DateField(blank=True, null=True)),
                ("meter_reading_energy", models.FloatField(blank=True, null=True)),
                ("is_using_reference_meter", models.BooleanField(default=False)),
                ("is_auto_consumption", models.BooleanField(default=False)),
                ("has_article_4_regularization", models.BooleanField(default=False)),
                ("reference_meter_id", models.CharField(max_length=64)),
                ("station_name", models.CharField(max_length=64)),
                ("station_id", models.CharField(max_length=64)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elec_charge_points",
                        to="elec.elecchargepointapplication",
                    ),
                ),
                (
                    "cpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="elec_charge_points", to="core.entity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Point de recharge",
                "verbose_name_plural": "Points de recharge",
                "db_table": "elec_charge_point",
            },
        ),
    ]
