# Generated by Django 4.1.7 on 2023-11-30 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0008_elecchargepointapplication_elecchargepoint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elecchargepoint",
            old_name="has_article_4_regularization",
            new_name="is_article_2",
        ),
        migrations.RenameField(
            model_name="elecchargepoint",
            old_name="is_using_reference_meter",
            new_name="is_article_4",
        ),
        migrations.RenameField(
            model_name="elecchargepoint",
            old_name="lne_certificate",
            new_name="lne_id",
        ),
        migrations.RenameField(
            model_name="elecchargepoint",
            old_name="meter_reading_date",
            new_name="measure_date",
        ),
        migrations.RenameField(
            model_name="elecchargepoint",
            old_name="meter_reading_energy",
            new_name="measure_energy",
        ),
        migrations.RenameField(
            model_name="elecchargepoint",
            old_name="reference_meter_id",
            new_name="measure_reference_point_id",
        ),
    ]
