# Generated by Django 4.1.7 on 2023-12-05 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0009_rename_has_article_4_regularization_elecchargepoint_is_article_2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elecchargepoint",
            old_name="lne_id",
            new_name="mid_id",
        ),
    ]
