# Generated by Django 4.1.7 on 2023-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0010_rename_lne_id_elecchargepoint_mid_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecchargepoint",
            name="nominal_power",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
