# Generated by Django 4.1.7 on 2023-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0011_elecchargepoint_nominal_power"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecchargepoint",
            name="cpo_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="elecchargepoint",
            name="cpo_siren",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
