# Generated by Django 4.1.7 on 2023-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0012_elecchargepoint_cpo_name_elecchargepoint_cpo_siren"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electransfercertificate",
            name="energy_amount",
            field=models.FloatField(),
        ),
    ]
