# Generated by Django 4.1.7 on 2023-12-12 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0008_alter_elecprovisioncertificate_energy_amount_and_more"),
        ("elec", "0013_alter_electransfercertificate_energy_amount"),
    ]

    operations = []
