# Generated by Django 4.1.7 on 2024-01-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_carburenotification_type"),
        ("elec", "0014_merge_20231212_1633"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecMeterReadingApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("ACCEPTED", "ACCEPTED"), ("REJECTED", "REJECTED")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("quarter", models.IntegerField(choices=[(1, "T1"), (2, "T2"), (3, "T3"), (4, "T4")])),
                ("year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elec_meter_reading_applications",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de relevés de points de recharge",
                "verbose_name_plural": "Dossiers de relevés de points de recharge",
                "db_table": "elec_meter_reading_application",
            },
        ),
    ]
