# Generated by Django 4.1.7 on 2024-01-11 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0017_alter_elecmeterreading_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecmeterreading",
            name="reading_date",
            field=models.DateField(default=datetime.date(2024, 1, 11)),
            preserve_default=False,
        ),
    ]
