# Generated by Django 4.1.7 on 2024-01-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0018_elecmeterreading_reading_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecchargepointapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("AUDIT_IN_PROGRESS", "AUDIT_IN_PROGRESS"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="elecmeterreadingapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("AUDIT_IN_PROGRESS", "AUDIT_IN_PROGRESS"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
