# Generated by Django 4.1.7 on 2024-02-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0019_alter_elecchargepointapplication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecmeterreading",
            name="renewable_energy",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
