# Generated by Django 4.1.7 on 2024-02-07 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0020_elecmeterreading_renewable_energy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elecchargepoint",
            name="is_article_4",
        ),
        migrations.RemoveField(
            model_name="elecchargepoint",
            name="is_auto_consumption",
        ),
    ]
