# Generated by Django 4.1.7 on 2024-02-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0021_remove_elecchargepoint_is_article_4_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecchargepoint",
            name="mid_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="elecchargepoint",
            name="station_name",
            field=models.CharField(max_length=128),
        ),
    ]
