# Generated by Django 4.1.7 on 2024-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0021_remove_elecchargepoint_is_article_4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecprovisioncertificate",
            name="current_type",
            field=models.CharField(
                choices=[("AC", "Courant alternatif"), ("DC", "Courant continu")], max_length=2, null=True
            ),
        ),
    ]
