# Generated by Django 4.1.7 on 2024-02-12 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_depot_electrical_efficiency_and_more"),
        ("elec", "0022_elecprovisioncertificate_current_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="elecprovisioncertificate",
            unique_together={("cpo", "quarter", "year", "current_type", "operating_unit")},
        ),
    ]
