# Generated by Django 4.1.7 on 2024-02-22 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0022_alter_elecchargepoint_mid_id_and_more"),
        ("elec", "0023_alter_elecprovisioncertificate_unique_together"),
    ]

    operations = []
