# Generated by Django 4.1.7 on 2024-03-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0024_merge_20240222_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecchargepoint",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="elecchargepoint",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
