# Generated by Django 4.1.7 on 2024-03-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0025_alter_elecchargepoint_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecchargepoint",
            name="measure_reference_point_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
