# Generated by Django 4.1.7 on 2024-03-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0026_alter_elecchargepoint_measure_reference_point_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecchargepointapplication",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
