# Generated by Django 4.1.7 on 2024-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0027_alter_elecchargepointapplication_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecmeterreadingapplication",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
