# Generated by Django 4.1.7 on 2024-04-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elec", "0028_alter_elecmeterreadingapplication_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="elecprovisioncertificate",
            unique_together=set(),
        ),
    ]
