# Generated by Django 4.1.7 on 2024-04-25 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0029_alter_elecprovisioncertificate_unique_together"),
        ("elec", "0029_elecchargepoint_previous_version"),
    ]

    operations = []
