# Generated by Django 5.0.6 on 2024-05-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elec", "0031_alter_elecchargepoint_cpo_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecAuditSample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("IN_PROGRESS", "IN_PROGRESS"), ("AUDITED", "AUDITED")],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "charge_point_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_sample",
                        to="elec.elecchargepointapplication",
                    ),
                ),
                (
                    "meter_reading_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_sample",
                        to="elec.elecmeterreadingapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Echantillon de points de recharge audités",
                "verbose_name_plural": "Echantillons de points de recharge audités",
                "db_table": "elec_audit_sample",
            },
        ),
        migrations.CreateModel(
            name="ElecAuditChargePoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_auditable", models.BooleanField(default=False)),
                (
                    "current_type",
                    models.CharField(
                        blank=True,
                        choices=[("AC", "Courant alternatif"), ("DC", "Courant continu")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("observed_mid_or_prm_id", models.CharField(blank=True, max_length=128, null=True)),
                ("observed_energy_reading", models.FloatField(default=0)),
                ("has_dedicated_pdl", models.BooleanField(default=False)),
                ("audit_date", models.DateField(blank=True, null=True)),
                ("comment", models.CharField(default="", max_length=512)),
                (
                    "charge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_point_audit",
                        to="elec.elecchargepoint",
                    ),
                ),
                (
                    "meter_reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_reading_audit",
                        to="elec.elecmeterreading",
                    ),
                ),
                (
                    "audit_sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audited_charge_points",
                        to="elec.elecauditsample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point de recharge audité",
                "verbose_name_plural": "Points de recharge audités",
                "db_table": "elec_audit_charge_point",
            },
        ),
    ]
