# Generated by Django 5.0.6 on 2024-05-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0032_elecauditsample_elecauditchargepoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecauditchargepoint",
            name="charge_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge_point_audit",
                to="elec.elecchargepoint",
            ),
        ),
    ]
