# Generated by Django 5.0.6 on 2024-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0033_alter_elecauditchargepoint_charge_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecauditsample",
            name="percentage",
            field=models.IntegerField(default=0),
        ),
    ]
