# Generated by Django 5.0.6 on 2024-05-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_carburenotification_type"),
        ("elec", "0034_elecauditsample_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecauditsample",
            name="auditor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elec_audits",
                to="core.entity",
            ),
        ),
        migrations.AddField(
            model_name="elecauditsample",
            name="cpo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elec_audited_applications",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="elecauditsample",
            name="status",
            field=models.CharField(
                choices=[("IN_PROGRESS", "IN_PROGRESS"), ("AUDITED", "AUDITED")], default="IN_PROGRESS", max_length=32
            ),
        ),
    ]
