# Generated by Django 5.0.6 on 2024-08-11 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0036_alter_elecchargepointapplication_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elecchargepoint",
            name="previous_version",
        ),
    ]
