# Generated by Django 5.0.6 on 2024-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elec", "0037_remove_elecchargepoint_previous_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecauditchargepoint",
            name="has_dedicated_pdl",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="elecauditchargepoint",
            name="is_auditable",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
