# Generated by Django 5.0.6 on 2024-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0038_alter_elecauditchargepoint_has_dedicated_pdl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecauditchargepoint",
            name="observed_energy_reading",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
