# Generated by Django 5.0.6 on 2024-08-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0039_alter_elecauditchargepoint_observed_energy_reading"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecMeter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mid_certificate", models.CharField(blank=False, max_length=128, null=False)),
                ("initial_index", models.FloatField(blank=False, null=True)),
                ("initial_index_date", models.DateField(blank=False, null=True)),
                (
                    "charge_point",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elec_meters",
                        to="elec.elecchargepoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compteur électrique d'un point de charge",
                "verbose_name_plural": "Compteurs électriques des points de charge",
                "db_table": "elec_meter",
            },
        ),
        migrations.AddField(
            model_name="elecchargepoint",
            name="current_meter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elec_charge_points",
                to="elec.elecmeter",
            ),
        ),
        migrations.AddField(
            model_name="elecmeterreading",
            name="meter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elec_meter_readings",
                to="elec.elecmeter",
            ),
        ),
    ]
