# Generated by Django 5.0.6 on 2024-09-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0042_remove_elecchargepoint_measure_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecchargepoint",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
