# Generated by Django 5.0.6 on 2024-10-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0044_empty_prefilled_audit_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecmeter",
            name="charge_point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elec_meters",
                to="elec.elecchargepoint",
            ),
        ),
    ]
