# Generated by Django 5.0.6 on 2024-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0045_alter_elecmeter_charge_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elecprovisioncertificate",
            name="current_type",
        ),
        migrations.AddField(
            model_name="elecprovisioncertificate",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "MANUAL"),
                    ("METER_READINGS", "METER_READINGS"),
                    ("QUALICHARGE", "QUALICHARGE"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
