# Generated by Django 5.0.6 on 2025-01-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0046_remove_elecprovisioncertificate_current_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecmeterreading",
            name="days_since_last_reading",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="elecmeterreading",
            name="energy_used_since_last_reading",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="elecmeterreading",
            name="facteur_de_charge",
            field=models.FloatField(default=0.0),
        ),
    ]
