# Generated by Django 5.0.6 on 2025-01-24 10:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_depot_depot_type"),
        ("elec", "0048_compute_facteur_de_charge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecChargePointHistory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("charge_point_id", models.CharField(max_length=64)),
                (
                    "current_type",
                    models.CharField(
                        choices=[
                            ("AC", "Courant alternatif"),
                            ("DC", "Courant continu"),
                        ],
                        max_length=2,
                    ),
                ),
                ("installation_date", models.DateField()),
                ("is_article_2", models.BooleanField(default=False)),
                (
                    "measure_reference_point_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("station_name", models.CharField(max_length=128)),
                ("station_id", models.CharField(max_length=64)),
                ("nominal_power", models.FloatField(blank=True, null=True)),
                ("cpo_name", models.CharField(blank=True, max_length=128, null=True)),
                ("cpo_siren", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="elec.elecchargepointapplication",
                    ),
                ),
                (
                    "cpo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.entity",
                    ),
                ),
                (
                    "current_meter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="elec.elecmeter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique point de recharge",
                "verbose_name_plural": "Historiques des points de recharge",
                "db_table": "elec_charge_point_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ElecMeterHistory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("mid_certificate", models.CharField(max_length=128)),
                ("initial_index", models.FloatField(null=True)),
                ("initial_index_date", models.DateField(null=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "charge_point",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="elec.elecchargepoint",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique compteur électrique",
                "verbose_name_plural": "Historiques des compteurs électriques",
                "db_table": "elec_meter_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
