# Generated by Django 5.0.6 on 2025-01-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0049_elecchargepointhistory_elecmeterhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="electransfercertificate",
            name="consumption_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="electransfercertificate",
            name="used_in_tiruert",
            field=models.BooleanField(default=False),
        ),
    ]
