# Generated by Django 5.0.6 on 2025-02-06 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0050_electransfercertificate_consumption_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="application",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="cpo",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="cpo_name",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="cpo_siren",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="current_type",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="is_article_2",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="nominal_power",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="station_id",
        ),
        migrations.RemoveField(
            model_name="elecchargepointhistory",
            name="station_name",
        ),
    ]
