# Generated by Django 5.0.6 on 2025-02-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0051_remove_elecchargepointhistory_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecprovisioncertificate",
            name="compensation",
            field=models.BooleanField(default=False),
        ),
    ]
