# Generated by Django 5.0.6 on 2025-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0053_update_model_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecchargepointhistory",
            name="nominal_power",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
