# Generated by Django 5.0.6 on 2025-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0054_elecchargepointhistory_nominal_power"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecprovisioncertificate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
