# Generated by Django 5.0.6 on 2025-07-04 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_carburestockevent_entity"),
        ("elec", "0055_elecprovisioncertificate_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecProvisionCertificateQualicharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("year", models.IntegerField()),
                ("operating_unit", models.CharField(max_length=64)),
                ("station_id", models.CharField(max_length=64)),
                ("energy_amount", models.FloatField()),
                ("is_controlled_by_qualicharge", models.BooleanField(default=False)),
                (
                    "validated_by",
                    models.CharField(
                        blank=True,
                        choices=[("DGEC", "DGEC"), ("AMENAGEUR", "AMENAGEUR"), ("BOTH", "BOTH")],
                        default=None,
                        max_length=16,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("cpo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.entity")),
            ],
            options={
                "verbose_name": "Certificat de Fourniture intermédiaire (elec)",
                "verbose_name_plural": "Certificats de Fourniture intermédiaires (elec)",
                "db_table": "elec_provision_certificate_qualicharge",
            },
        ),
    ]
