# Generated by Django 5.0.6 on 2025-07-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0056_elecprovisioncertificatequalicharge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecprovisioncertificatequalicharge",
            name="validated_by",
            field=models.CharField(
                blank=True,
                choices=[("NO_ONE", "NO_ONE"), ("DGEC", "DGEC"), ("AMENAGEUR", "AMENAGEUR"), ("BOTH", "BOTH")],
                default="NO_ONE",
                max_length=16,
            ),
        ),
    ]
