# Generated by Django 5.2.2 on 2025-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0057_alter_elecprovisioncertificatequalicharge_validated_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="elecprovisioncertificatequalicharge",
            options={
                "verbose_name": "Certificat de Fourniture Qualicharge (elec)",
                "verbose_name_plural": "Certificats de Fourniture Qualicharge (elec)",
            },
        ),
        migrations.AlterField(
            model_name="elecprovisioncertificatequalicharge",
            name="validated_by",
            field=models.CharField(
                blank=True,
                choices=[("NO_ONE", "NO_ONE"), ("DGEC", "DGEC"), ("CPO", "CPO"), ("BOTH", "BOTH")],
                default="NO_ONE",
                max_length=16,
            ),
        ),
    ]
