# Generated by Django 5.2.2 on 2025-11-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_merge_20251023_2042"),
        ("elec", "0058_alter_elecprovisioncertificatequalicharge_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecprovisioncertificatequalicharge",
            name="unknown_siren",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="elecprovisioncertificatequalicharge",
            name="cpo",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.entity"),
        ),
    ]
