# Generated by Django 5.2.2 on 2025-12-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0059_elecprovisioncertificatequalicharge_unknown_siren_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecMeterReadingVirtual",
            fields=[
                ("reading_id", models.IntegerField(primary_key=True, serialize=False)),
                ("current_index_date", models.DateField()),
                ("prev_index_date", models.DateField()),
                ("current_index", models.FloatField()),
                ("prev_index", models.FloatField()),
                ("enr_ratio", models.FloatField()),
            ],
            options={
                "db_table": "elec_meter_reading_virtual",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="elecmeterreading",
            name="days_since_last_reading",
        ),
        migrations.RemoveField(
            model_name="elecmeterreading",
            name="energy_used_since_last_reading",
        ),
        migrations.RemoveField(
            model_name="elecmeterreading",
            name="facteur_de_charge",
        ),
        migrations.RemoveField(
            model_name="elecmeterreading",
            name="renewable_energy",
        ),
        migrations.AddField(
            model_name="elecmeterreading",
            name="enr_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="elecmeterreading",
            name="operating_unit",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
