# Generated by Django 5.2.2 on 2025-12-11 10:04

from django.db import migrations


def populate_operating_unit(apps, schema_editor):
    ElecMeterReading = apps.get_model("elec", "ElecMeterReading")

    readings_to_update = []
    for reading in ElecMeterReading.objects.select_related("meter__charge_point").filter(
        meter__isnull=False,
        meter__charge_point__isnull=False,
    ):
        charge_point_id = reading.meter.charge_point.charge_point_id
        if charge_point_id:
            reading.operating_unit = charge_point_id[:5]
            readings_to_update.append(reading)

    ElecMeterReading.objects.bulk_update(readings_to_update, ["operating_unit"], batch_size=1000)


def reverse_populate_operating_unit(apps, schema_editor):
    ElecMeterReading = apps.get_model("elec", "ElecMeterReading")
    ElecMeterReading.objects.update(operating_unit=None)


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0063_fix_modulo_elec_entity"),
    ]

    operations = [
        migrations.RunPython(populate_operating_unit, reverse_populate_operating_unit),
    ]
