# Generated by Django 5.2.2 on 2026-01-08 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0064_populate_operating_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elecprovisioncertificate",
            name="remaining_energy_amount",
        ),
    ]
