# Generated by Django 5.2.2 on 2025-12-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0064_populate_operating_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elecprovisioncertificate",
            name="compensation",
        ),
        migrations.AddField(
            model_name="electransfercertificate",
            name="is_readjustment",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="elecprovisioncertificate",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "MANUAL"),
                    ("METER_READINGS", "METER_READINGS"),
                    ("QUALICHARGE", "QUALICHARGE"),
                    ("ENR_RATIO_COMPENSATION", "ENR_RATIO_COMPENSATION"),
                    ("ADMIN_ERROR_COMPENSATION", "ADMIN_ERROR_COMPENSATION"),
                ],
                max_length=32,
            ),
        ),
    ]
