# Generated by Django 5.2.2 on 2025-12-29 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_genericcertificate_certificate_type"),
        ("elec", "0065_remove_elecprovisioncertificate_compensation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecCertificateReadjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("energy_amount", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "error_source",
                    models.CharField(
                        choices=[("METER_READINGS", "Relevés"), ("QUALICHARGE", "Qualicharge"), ("MANUAL", "Manuel")],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(default="", max_length=256)),
                ("cpo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.entity")),
            ],
        ),
    ]
