# Generated by Django 5.2.2 on 2026-01-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0066_eleccertificatereadjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecprovisioncertificatequalicharge",
            name="enr_ratio",
            field=models.FloatField(default=0.25),
        ),
    ]
