# Generated by Django 5.2.2 on 2026-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0067_elecprovisioncertificatequalicharge_enr_ratio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elecprovisioncertificate",
            name="remaining_energy_amount",
        ),
        migrations.AddField(
            model_name="elecprovisioncertificate",
            name="compensation",
            field=models.BooleanField(default=False),
        ),
    ]
