# Generated by Django 5.2.2 on 2026-02-19 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0067_elecprovisioncertificatequalicharge_enr_ratio"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS elec_meter_reading_virtual;",
        )
    ]
