# Generated by Django 5.2.2 on 2026-02-24 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "elec",
            "0068_remove_elecprovisioncertificate_remaining_energy_amount_and_more",
        ),
        ("elec", "0068_remove_meter_reading_virtual_view"),
    ]

    operations = []
