# Generated by Django 5.2.2 on 2026-03-12 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0069_merge_20260224_1551"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ElecMeterReadingVirtual",
        ),
    ]
