# Generated by Django 5.2.2 on 2026-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0070_delete_elecmeterreadingvirtual"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecprovisioncertificate",
            name="date_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="elecprovisioncertificate",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
