# Generated by Django 5.2.2 on 2026-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0071_elecprovisioncertificate_date_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecprovisioncertificate",
            name="enr_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
