# Generated by Django 5.2.2

from datetime import datetime

from django.db import migrations, models


def backfill_readjustment_year(apps, schema_editor):
    readjustment_model = apps.get_model("elec", "ElecCertificateReadjustment")
    for row in readjustment_model.objects.filter(year__isnull=True).iterator():
        row.year = row.created_at.year if row.created_at else datetime.now().year
        row.save(update_fields=["year"])


class Migration(migrations.Migration):
    dependencies = [
        ("elec", "0072_elecprovisioncertificate_enr_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleccertificatereadjustment",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_readjustment_year, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="eleccertificatereadjustment",
            name="year",
            field=models.IntegerField(),
        ),
    ]
