# Generated by Django 5.2.2 on 2026-06-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0072_change_feedstock_collation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantité')),
                ('type', models.CharField(choices=[('CREATION_H2', 'CREATION_H2'), ('TRANSFERT', 'TRANSFERT'), ('CONSOMMATION', 'CONSOMMATION'), ('PERTE', 'PERTE'), ('VALORISATION', 'VALORISATION')], max_length=32, verbose_name="Type d'action")),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('REFUSED', 'REFUSED'), ('PENDING', 'PENDING')], max_length=16, null=True, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_poc_actions', to='core.entity', verbose_name='Entité propriétaire')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stock_poc.action', verbose_name='Action parente')),
            ],
            options={
                'verbose_name': 'Action (stock POC)',
                'verbose_name_plural': 'Actions (stock POC)',
                'db_table': 'stock_poc_action',
                'ordering': ['id'],
            },
        ),
    ]
