# Generated by Django 5.2.2 on 2026-06-24 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_poc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="status",
        ),
        migrations.CreateModel(
            name="ActionStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("ACCEPTED", "ACCEPTED"), ("REFUSED", "REFUSED"), ("PENDING", "PENDING")],
                        max_length=16,
                        null=True,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_statuses",
                        to="stock_poc.action",
                        verbose_name="Action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statut d'action",
                "verbose_name_plural": "Statuts d'action",
                "db_table": "stock_poc_action_status",
                "ordering": ["id"],
            },
        ),
    ]
