repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: run-npm-script
        name: Eslint/Prettier
        entry: bash -c 'cd front && npm run lint'
        language: system
        files: ^front/
