version: '3.5'
services:
  carbure-mariadb:
    image: mariadb:latest
    restart: always
    container_name: carbure_mariadb
    environment:
      ENV: ${IMAGE_TAG}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DJANGO_DATABASE}
      MYSQL_USER: ${DJANGO_DB_USER}
      MYSQL_PASSWORD: ${DJANGO_DB_PASSWORD}
    volumes:
    - carburedb:/var/lib/mysql
    networks:
    - carbure

  carbure-django-uwsgi:
    command: bash /app/web/run.sh
    restart: always
    container_name: carbure_app
    image: registry.gitlab.com/la-fabrique-numerique/biocarburants/django_app:${IMAGE_TAG}
    environment:
      DJANGO_DATABASE: ${DJANGO_DATABASE}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      IMAGE_TAG: ${IMAGE_TAG}
      CARBURE_HOME: /app
      SENTRY_DSN: ${SENTRY_DSN}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      PYTHONPATH: /app:/app/web
      AWS_ACCESS_KEY_ID: ${SCALEWAY_API_KEY}
      AWS_SECRET_ACCESS_KEY: ${SCALEWAY_API_SECRET}
      AWS_STORAGE_BUCKET_NAME: ${SCALEWAY_BUCKET_NAME}
      AWS_S3_REGION_NAME:  ${SCALEWAY_REGION_NAME}
      AWS_S3_ENDPOINT_URL: ${SCALEWAY_S3_ENDPOINT}
      AWS_S3_USE_SSL: 1
      TEST: 0
    depends_on:
    - carbure-mariadb
    networks:
    - carbure

  carbure-web-proxy:
    restart: always
    container_name: carbure_web
    image: registry.gitlab.com/la-fabrique-numerique/biocarburants/web_proxy:${IMAGE_TAG}
    environment:
      NGINX_HOSTS: ${NGINX_HOSTS}
      NGINX_SSL_FOLDER: ${NGINX_SSL_FOLDER}
    command: /bin/bash -c "envsubst '$$NGINX_HOSTS $$NGINX_SSL_FOLDER' < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
    - carbure-django-uwsgi
    ports:
    - 80:80
    - 443:443
    networks:
    - carbure
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: carbure_web carbure_app --interval 30

  certbot:
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot

volumes:
  carburedb:
    name: carbure_carburedb

networks:
  carbure:
    name: carbure_default

