version: "3.5"
services:
  carbure-mariadb:
    image: mariadb:latest
    restart: always
    container_name: carbure_mariadb
    environment:
      ENV: ${IMAGE_TAG}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DJANGO_DATABASE}
      MYSQL_USER: ${DJANGO_DB_USER}
      MYSQL_PASSWORD: ${DJANGO_DB_PASSWORD}
    volumes:
      - carburedb:/var/lib/mysql
    networks:
      - carbure

  carbure-django-uwsgi:
    command: bash /app/web/run.sh
    restart: always
    container_name: carbure_app
    image: registry.gitlab.com/la-fabrique-numerique/biocarburants/django_app:${IMAGE_TAG}
    environment:
      DJANGO_DATABASE: ${DJANGO_DATABASE}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      IMAGE_TAG: ${IMAGE_TAG}
      CARBURE_HOME: /app
      SENTRY_DSN: ${SENTRY_DSN}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      PYTHONPATH: /app:/app/web
      AWS_ACCESS_KEY_ID: ${SCALEWAY_API_KEY}
      AWS_SECRET_ACCESS_KEY: ${SCALEWAY_API_SECRET}
      AWS_STORAGE_BUCKET_NAME: ${SCALEWAY_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${SCALEWAY_REGION_NAME}
      AWS_S3_ENDPOINT_URL: ${SCALEWAY_S3_ENDPOINT}
      AWS_S3_USE_SSL: 1
    depends_on:
      - carbure-mariadb
    networks:
      - carbure

  carbure-frontend:
    container_name: carbure_frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      target: production
    volumes:
      - "/app/node_modules"
      - carburedist:/app/dist

  carbure-web-proxy:
    restart: always
    container_name: carbure_web
    image: registry.gitlab.com/la-fabrique-numerique/biocarburants/web_proxy:${IMAGE_TAG}
    environment:
      NGINX_HOSTS: ${NGINX_HOSTS}
      NGINX_SSL_FOLDER: ${NGINX_SSL_FOLDER}
      METABASE_HOST: ${METABASE_HOST}
      METABASE_SSL_FOLDER: ${METABASE_SSL_FOLDER}
    command: /opt/run_nginx.sh
    depends_on:
      - carbure-django-uwsgi
      - carbure-frontend
    ports:
      - 80:80
      - 443:443
    networks:
      - carbure
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - carburedist:/var/www/html_v2

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: carbure_web carbure_app --interval 30

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  carbure-metabase:
    restart: always
    container_name: carbure_metabase
    image: metabase/metabase
    depends_on:
      - carbure-mariadb
    ports:
      - 3000:3000
    networks:
      - carbure
    volumes:
      - ./metabase:/metabase-data
    environment:
      MB_DB_FILE: "/metabase-data/metabase.db"

volumes:
  carburedb:
    name: carbure_carburedb
  carburedist:
    name: carbure_carburedist

networks:
  carbure:
    name: carbure_default
