# Generated by Django 5.2.2 on 2026-02-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0059_alter_carburelot_pos_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group", models.CharField(blank=True, max_length=128)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("subcategory", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "Classification",
                "verbose_name_plural": "Classifications",
                "db_table": "classification",
            },
        ),
        migrations.CreateModel(
            name="Feedstock",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(blank=True, max_length=256)),
                (
                    "classification",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="feedstocks.classification"),
                ),
                (
                    "matiere_premiere",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.matierepremiere"),
                ),
            ],
            options={
                "verbose_name": "Feedstock",
                "verbose_name_plural": "Feedstocks",
                "db_table": "feedstock",
            },
        ),
    ]
