# Generated by Django 5.2.2 on 2026-02-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0060_matierepremiere_is_biofuel_feedstock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group", models.CharField(blank=True, max_length=128)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("subcategory", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "Classification",
                "verbose_name_plural": "Classifications",
                "db_table": "classification",
                "unique_together": {("group", "category", "subcategory")},
            },
        ),
    ]
