# Generated by Django 5.2.2 on 2026-02-05 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedstocks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedstock",
            old_name="display_name",
            new_name="name",
        ),
    ]
