# Generated by Django 5.2.2 on 2026-02-05 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedstocks", "0002_rename_display_name_feedstock_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classification",
            unique_together={("group", "category", "subcategory")},
        ),
    ]
