import useYears from "common/hooks/years-2"
import { useSelectedEntity } from "common/providers/selected-entity-provider"

const getAnnualDeclarationYearsAdmin = () => {
  const currentYear = new Date().getFullYear()
  const startYear = 2025
  const endYear = currentYear > startYear ? currentYear - 1 : startYear

  return Array.from(
    { length: endYear - startYear + 1 },
    (_, i) => startYear + i
  )
}

export const annualDeclarationYearsAdmin = getAnnualDeclarationYearsAdmin()
export const lastAnnualDeclarationYearAdmin =
  annualDeclarationYearsAdmin[annualDeclarationYearsAdmin.length - 1]

/**
 * Get years from 2025 (the first year of the biomethane module), to N-1 (the current year - 1)
 */
export const useAnnualDeclarationYearsAdmin = () => {
  const { selectedEntityId } = useSelectedEntity()

  return useYears(
    `biomethane/admin/declarations/${selectedEntityId}`,
    () => {
      return Promise.resolve({
        data: annualDeclarationYearsAdmin,
        response: new Response(),
      })
    },
    // If the user has the DREAL admin right, we need to be redirected to the last year generated by the getYears function
    // and if the user is a biomethane producer, we just need to fill the select with the years from the API, without redirecting to the last year
    { readOnly: false, withCurrentYearIfEmpty: false }
  )
}
