# Generated by Django 3.2.4 on 2021-08-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublecount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublecountingproduction',
            name='metric_tonnes',
        ),
        migrations.AddField(
            model_name='doublecountingproduction',
            name='approved_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doublecountingproduction',
            name='estimated_production',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doublecountingproduction',
            name='max_production_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doublecountingproduction',
            name='requested_quota',
            field=models.IntegerField(default=0),
        ),
    ]
