# Generated by Django 3.2.4 on 2021-08-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doublecount', '0002_auto_20210824_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublecountingproduction',
            name='dca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='doublecount.doublecountingagreement'),
        ),
        migrations.AlterField(
            model_name='doublecountingsourcing',
            name='dca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing', to='doublecount.doublecountingagreement'),
        ),
    ]
