# Generated by Django 4.1.7 on 2023-05-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_carburenotification_type"),
        ("producers", "0001_initial"),
        ("doublecount", "0003_alter_doublecountingagreement_producer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingagreement",
            name="producer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="doublecountingagreement",
            name="production_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="producers.productionsite",
            ),
        ),
    ]
