# Generated by Django 3.2.4 on 2021-09-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doublecount', '0003_auto_20210827_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleCountingDocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('dca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='doublecount.doublecountingagreement')),
            ],
            options={
                'verbose_name': 'Fichier Double Compte',
                'verbose_name_plural': 'Fichiers Double Compte',
                'db_table': 'double_counting_doc_files',
            },
        ),
    ]
