# Generated by Django 4.1.7 on 2023-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0004_alter_doublecountingagreement_producer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublecountingagreement",
            name="agreement_id",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
