# Generated by Django 3.2.4 on 2021-09-23 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doublecount', '0004_doublecountingdocfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublecountingdocfile',
            name='file_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='doublecountingdocfile',
            name='link_expiry_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 13, 48, 4, 707547, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doublecountingdocfile',
            name='dca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doublecount.doublecountingagreement'),
        ),
        migrations.AlterField(
            model_name='doublecountingdocfile',
            name='url',
            field=models.TextField(),
        ),
    ]
