# Generated by Django 3.2.4 on 2021-09-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublecount', '0005_auto_20210923_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublecountingproduction',
            name='approved_quota',
            field=models.IntegerField(default=-1),
        ),
    ]
