# Generated by Django 4.1.7 on 2023-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0005_doublecountingagreement_agreement_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingagreement",
            name="agreement_id",
            field=models.CharField(max_length=16),
        ),
    ]
