# Generated by Django 4.1.7 on 2023-07-27 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_entity_has_elec"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producers", "0003_alter_productionsite_dc_number"),
        ("doublecount", "0006_alter_doublecountingagreement_agreement_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DoubleCountingAgreement",
            new_name="DoubleCountingApplication",
        ),
    ]
