# Generated by Django 3.2.4 on 2021-09-29 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doublecount', '0006_alter_doublecountingproduction_approved_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublecountingagreement',
            name='producer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
