# Generated by Django 4.1.7 on 2023-07-27 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0007_rename_doublecountingagreement_doublecountingapplication"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="doublecountingapplication",
            table="double_counting_applications",
        ),
    ]
