# Generated by Django 3.2.4 on 2021-09-29 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doublecount', '0007_doublecountingagreement_producer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublecountingagreement',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
