# Generated by Django 3.2.4 on 2021-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublecount', '0008_doublecountingagreement_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublecountingagreement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INPROGRESS', 'INPROGRESS'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED'), ('LAPSED', 'LAPSED')], default='PENDING', max_length=32),
        ),
    ]
