# Generated by Django 4.1.7 on 2023-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0009_doublecountingdocfile_agreement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublecountingdocfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
