# Generated by Django 3.2.8 on 2021-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublecount', '0009_alter_doublecountingagreement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublecountingdocfile',
            name='file_type',
            field=models.CharField(choices=[('SOURCING', 'SOURCING'), ('DECISION', 'DECISION')], default='SOURCING', max_length=128),
        ),
    ]
