# Generated by Django 4.1.7 on 2023-07-27 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0010_doublecountingdocfile_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doublecountingapplication",
            old_name="creation_date",
            new_name="created_at",
        ),
    ]
