# Generated by Django 4.1.7 on 2023-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0011_rename_creation_date_doublecountingapplication_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("INPROGRESS", "INPROGRESS"),
                    ("REJECTED", "REJECTED"),
                    ("ACCEPTED", "ACCEPTED"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
