# Generated by Django 5.0.6 on 2024-10-16 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_depot_entity"),
        (
            "doublecount",
            "0014_rename_agreement_id_doublecountingapplication_certificate_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DoubleCountingSourcingHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("metric_tonnes", models.IntegerField()),
                ("raw_material_supplier", models.CharField(default="", max_length=128)),
                (
                    "supplier_certificate_name",
                    models.CharField(default="", max_length=64),
                ),
                (
                    "dca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_sourcing",
                        to="doublecount.doublecountingapplication",
                    ),
                ),
                (
                    "feedstock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.matierepremiere",
                    ),
                ),
                (
                    "origin_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_origin_country",
                        to="core.pays",
                    ),
                ),
                (
                    "supplier_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.genericcertificate",
                    ),
                ),
                (
                    "supply_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_supply_country",
                        to="core.pays",
                    ),
                ),
                (
                    "transit_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_transit_country",
                        to="core.pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sourcing Double Compte Historique",
                "verbose_name_plural": "Sourcing Double Compte Historique",
                "db_table": "double_counting_sourcing_history",
            },
        ),
    ]
