# Generated by Django 5.0.6 on 2024-12-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0016_alter_doublecountingapplication_production_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublecountingapplication",
            name="download_link",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
