# Generated by Django 5.0.6 on 2024-12-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_depot_depot_type"),
        ("doublecount", "0017_doublecountingapplication_download_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doublecountingsourcinghistory",
            options={
                "verbose_name": "Sourcing Double Compte Historique",
                "verbose_name_plural": "Sourcing Double Compte Historiques",
            },
        ),
        migrations.CreateModel(
            name="DoubleCountingProductionHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("max_production_capacity", models.IntegerField(default=0)),
                ("effective_production", models.IntegerField(default=0)),
                (
                    "biofuel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.biocarburant",
                    ),
                ),
                (
                    "dca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_production",
                        to="doublecount.doublecountingapplication",
                    ),
                ),
                (
                    "feedstock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.matierepremiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Double Compte Historique",
                "verbose_name_plural": "Production Double Compte Historiques",
                "db_table": "double_counting_production_history",
            },
        ),
    ]
