# Generated by Django 5.0.6 on 2025-02-26 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0018_alter_doublecountingsourcinghistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doublecountingapplication",
            options={
                "ordering": ["certificate_id"],
                "verbose_name": "Dossier Double Compte",
                "verbose_name_plural": "Dossiers Double Compte",
            },
        ),
    ]
