# Generated by Django 5.0.6 on 2025-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0021_doublecountingapplication_industrial_wastes_file_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingdocfile",
            name="link_expiry_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
