# Generated by Django 5.0.6 on 2025-06-13 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0022_alter_doublecountingdocfile_link_expiry_dt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doublecountingapplication",
            name="industrial_wastes_file_link",
        ),
    ]
