# Generated by Django 5.0.6 on 2025-06-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "doublecount",
            "0023_remove_doublecountingapplication_industrial_wastes_file_link",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingdocfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("EXCEL", "EXCEL"),
                    ("EXTRA", "EXTRA"),
                    ("DECISION", "DECISION"),
                ],
                default="EXTRA",
                max_length=128,
            ),
        ),
    ]
