# Generated by Django 5.0.6 on 2025-06-13 15:56

import os

from django.db import migrations


def populate_doc_files(apps, schema_editor):
    DoubleCountingApplication = apps.get_model("doublecount", "DoubleCountingApplication")
    DoubleCountingDocFile = apps.get_model("doublecount", "DoubleCountingDocFile")

    # Delete all existing rows in DoubleCountingDocFile
    DoubleCountingDocFile.objects.all().delete()

    # Create one entry for each application with non-NULL download_link
    applications = DoubleCountingApplication.objects.filter(download_link__isnull=False)

    for app in applications:
        DoubleCountingDocFile.objects.create(
            url=app.download_link,
            file_name=os.path.basename(app.download_link),
            file_type="EXCEL",
            dca=app,
        )


def reverse_populate_doc_files(apps, schema_editor):
    DoubleCountingDocFile = apps.get_model("doublecount", "DoubleCountingDocFile")
    DoubleCountingDocFile.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0024_alter_doublecountingdocfile_file_type"),
    ]

    operations = [
        migrations.RunPython(populate_doc_files, reverse_populate_doc_files),
    ]
