# Generated by Django 5.2.2 on 2025-10-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0025_resurrect_dc_doc_file_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingsourcinghistory",
            name="supplier_certificate_name",
            field=models.CharField(default="", max_length=128),
        ),
    ]
