# Generated by Django 5.2.2 on 2026-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doublecount", "0026_alter_doublecountingsourcinghistory_supplier_certificate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("INPROGRESS", "INPROGRESS"),
                    ("REJECTED", "REJECTED"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("WAITING_FOR_DECISION", "WAITING_FOR_DECISION"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
