# Generated by Django 3.2.8 on 2021-11-05 14:29

from django.db import migrations
import datetime
import calendar
from django.db.models.aggregates import Sum
import os
import django
import argparse
from django.db.models import Sum

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "carbure.settings")
django.setup()

from django.db import connection

from core.models import AdminTransactionComment, CarbureLot, CarbureLotComment, CarbureLotEvent, CarbureStock, CarbureStockTransformation, ETBETransformation, Entity, GenericError, LotTransaction, LotV2, TransactionComment, TransactionUpdateHistory

def cleanup_tables():
    cursor = connection.cursor()
    sql = "SET FOREIGN_KEY_CHECKS = 0;"
    cursor.execute(sql)
    sql = "TRUNCATE TABLE carbure_lots;"
    cursor.execute(sql)
    sql = "TRUNCATE TABLE carbure_stock;"
    cursor.execute(sql)
    sql = "TRUNCATE TABLE carbure_stock_transformations;"
    cursor.execute(sql)
    sql = "SET FOREIGN_KEY_CHECKS = 1;"
    cursor.execute(sql)
    
    

if __name__ == '__main__':
    cleanup_tables()
