---
- name: Install aptitude
  apt:
    name: aptitude
    state: present
    
- name: Upgrade packages
  apt:
    upgrade: safe

- name: Delete docker (if exists)
  apt:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent

- name: Install packages
  become: yes
  apt:
    name: ['fail2ban', 'ufw', 'unattended-upgrades', 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip']
    state: present
    update_cache: yes
  tags:
    - packages