# Generated by Django 4.1.1 on 2022-09-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoubleCountingRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("certificate_id", models.CharField(max_length=64)),
                ("certificate_holder", models.CharField(max_length=256)),
                ("registered_address", models.TextField()),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
            ],
            options={
                "verbose_name": "Certificat Double Compte",
                "verbose_name_plural": "Certificats Double Compte",
                "db_table": "double_counting_registrations",
            },
        ),
        migrations.CreateModel(
            name="DoubleCountingRegistrationInputOutput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Périmètre Certificat Double Compte",
                "verbose_name_plural": "Périmètres Certificats Double Compte",
                "db_table": "double_counting_registrations_scope",
            },
        ),
        migrations.CreateModel(
            name="ProductionSiteCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Certificat de site de production",
                "verbose_name_plural": "Certificats de sites de productions",
                "db_table": "production_sites_certificates",
            },
        ),
    ]
