# Generated by Django 3.2 on 2021-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sncertificatecategory',
            old_name='category',
            new_name='description',
        ),
        migrations.AddField(
            model_name='sncertificatecategory',
            name='category_id',
            field=models.CharField(default='', max_length=6),
        ),
    ]
