# Generated by Django 3.2 on 2021-04-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20210419_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sncertificate',
            name='scope',
        ),
        migrations.CreateModel(
            name='SNCertificateScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.sncertificate')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.sncertificatecategory')),
            ],
            options={
                'verbose_name': 'SN Certificate Scope',
                'verbose_name_plural': 'SN Certificate Scopes',
                'db_table': 'sn_certificates_scopes',
            },
        ),
    ]
