# Generated by Django 4.1.7 on 2023-05-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
        ("certificates", "0003_doublecountingregistration_production_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingregistration",
            name="production_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="producers.productionsite",
            ),
        ),
    ]
