# Generated by Django 3.2 on 2021-04-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_sncertificate_valid_from'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SNCertificateCategory',
            new_name='SNCategory',
        ),
    ]
