# Generated by Django 3.2 on 2021-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_rename_sncertificatecategory_sncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sncertificate',
            name='download_link',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
