# Generated by Django 3.2 on 2021-04-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_alter_sncertificate_download_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitysntradingcertificate',
            options={'verbose_name': 'Certificat Système National', 'verbose_name_plural': 'Certificats Système National liés à des sociétés'},
        ),
    ]
