# Generated by Django 5.0.6 on 2025-02-26 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0006_alter_doublecountingregistration_production_site_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doublecountingregistration",
            options={
                "ordering": ["certificate_id", "certificate_holder"],
                "verbose_name": "Certificat Double Compte",
                "verbose_name_plural": "Certificats Double Compte",
            },
        ),
    ]
