# Generated by Django 5.2.2 on 2026-02-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0007_alter_doublecountingregistration_options"),
        ("transactions", "0017_update_site_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublecountingregistration",
            name="production_site",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="transactions.productionsite"
            ),
        ),
        migrations.AlterField(
            model_name="productionsitecertificate",
            name="production_site",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="transactions.productionsite"
            ),
        ),
    ]
