# Generated by Django 3.2 on 2021-04-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20210428_1450'),
        ('producers', '0021_auto_20210219_1416'),
        ('certificates', '0007_auto_20210428_1439'),
    ]

    operations = [
    ]
