# Generated by Django 3.2 on 2021-04-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0021_auto_20210219_1416'),
        ('core', '0134_auto_20210429_1854'),
        ('certificates', '0008_auto_20210428_1450'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DBSCertificate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certificate_id', models.CharField(max_length=64)),
                        ('certificate_holder', models.CharField(max_length=256)),
                        ('holder_address', models.CharField(max_length=512)),
                        ('valid_from', models.DateField()),
                        ('valid_until', models.DateField()),
                        ('certification_type', models.CharField(default='', max_length=512)),
                        ('download_link', models.CharField(default='', max_length=512)),
                    ],
                    options={
                        'verbose_name': '2BS Certificate',
                        'verbose_name_plural': '2BS Certificates',
                        'db_table': 'dbs_certificates',
                    },
                ),
                migrations.CreateModel(
                    name='DBSScope',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certification_type', models.CharField(default='', max_length=512)),
                    ],
                    options={
                        'verbose_name': '2BS Scope',
                        'verbose_name_plural': '2BS Scopes',
                        'db_table': 'dbs_scopes',
                    },
                ),
                migrations.CreateModel(
                    name='EntityDBSTradingCertificate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('has_been_updated', models.BooleanField(default=False)),
                        ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.dbscertificate')),
                        ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
                    ],
                    options={
                        'verbose_name': 'Certificat de Trading 2BS',
                        'verbose_name_plural': 'Certificats de Trading 2BS',
                        'db_table': 'entity_2bs_trading_certificates',
                    },
                ),
                migrations.CreateModel(
                    name='EntityISCCTradingCertificate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('has_been_updated', models.BooleanField(default=False)),
                    ],
                    options={
                        'verbose_name': 'Certificat de Trading ISCC',
                        'verbose_name_plural': 'Certificats de Trading ISCC',
                        'db_table': 'entity_iscc_trading_certificates',
                    },
                ),
                migrations.CreateModel(
                    name='EntityREDCertTradingCertificate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('has_been_updated', models.BooleanField(default=False)),
                    ],
                    options={
                        'verbose_name': 'Certificat de Trading REDCert',
                        'verbose_name_plural': 'Certificats de Trading REDCert',
                        'db_table': 'entity_redcert_trading_certificates',
                    },
                ),
                migrations.CreateModel(
                    name='ISCCCertificate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certificate_id', models.CharField(max_length=64)),
                        ('certificate_holder', models.CharField(max_length=256)),
                        ('addons', models.CharField(max_length=256)),
                        ('valid_from', models.DateField()),
                        ('valid_until', models.DateField()),
                        ('issuing_cb', models.CharField(default='', max_length=256)),
                        ('location', models.CharField(default='', max_length=256)),
                        ('download_link', models.CharField(default='', max_length=512)),
                    ],
                    options={
                        'verbose_name': 'ISCC Certificate',
                        'verbose_name_plural': 'ISCC Certificates',
                        'db_table': 'iscc_certificates',
                    },
                ),
                migrations.CreateModel(
                    name='ISCCScope',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('scope', models.CharField(max_length=8)),
                        ('description', models.CharField(max_length=256)),
                    ],
                    options={
                        'verbose_name': 'ISCC Scope',
                        'verbose_name_plural': 'ISCC Scopes',
                        'db_table': 'iscc_scopes',
                    },
                ),
                migrations.CreateModel(
                    name='REDCertBiomassType',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=16)),
                        ('description_fr', models.CharField(max_length=256)),
                        ('description_en', models.CharField(max_length=256)),
                        ('description_de', models.CharField(max_length=256)),
                    ],
                    options={
                        'verbose_name': 'REDCert Biomass Type',
                        'verbose_name_plural': 'REDCert Biomass Types',
                        'db_table': 'redcert_biomass_types',
                    },
                ),
                migrations.CreateModel(
                    name='REDCertCertificate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certificate_id', models.CharField(max_length=64)),
                        ('certificate_holder', models.CharField(max_length=256)),
                        ('city', models.CharField(default='', max_length=256)),
                        ('zip_code', models.CharField(default='', max_length=12)),
                        ('country_raw', models.CharField(default='', max_length=32)),
                        ('valid_from', models.DateField()),
                        ('valid_until', models.DateField()),
                        ('certificator', models.CharField(default='', max_length=256)),
                        ('certificate_type', models.CharField(default='', max_length=256)),
                        ('status', models.CharField(default='', max_length=32)),
                        ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pays')),
                    ],
                    options={
                        'verbose_name': 'REDCert Certificate',
                        'verbose_name_plural': 'REDCert Certificates',
                        'db_table': 'redcert_certificates',
                    },
                ),
                migrations.CreateModel(
                    name='REDCertScope',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('scope', models.CharField(max_length=8)),
                        ('description_fr', models.CharField(max_length=256)),
                        ('description_en', models.CharField(max_length=256)),
                        ('description_de', models.CharField(max_length=256)),
                    ],
                    options={
                        'verbose_name': 'REDCert Scope',
                        'verbose_name_plural': 'REDCert Scopes',
                        'db_table': 'redcert_scopes',
                    },
                ),
                migrations.CreateModel(
                    name='REDCertCertificateScope',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.redcertcertificate')),
                        ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.redcertscope')),
                    ],
                    options={
                        'verbose_name': 'REDCert Certificate Scope',
                        'verbose_name_plural': 'REDCert Certificate Scopes',
                        'db_table': 'redcert_certificates_scopes',
                    },
                ),
                migrations.CreateModel(
                    name='REDCertCertificateBiomass',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('biomass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.redcertbiomasstype')),
                        ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.redcertcertificate')),
                    ],
                    options={
                        'verbose_name': 'REDCert Certificate Biomass',
                        'verbose_name_plural': 'REDCert Certificate Biomass',
                        'db_table': 'redcert_certificates_biomass',
                    },
                ),
                migrations.CreateModel(
                    name='ProductionSiteCertificate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('type', models.CharField(choices=[('ISCC', 'ISCC'), ('2BS', '2BS'), ('REDCERT', 'REDCERT'), ('SN', 'SN')], default='Pending', max_length=32)),
                        ('certificate_2bs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.entitydbstradingcertificate')),
                        ('certificate_iscc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.entityiscctradingcertificate')),
                        ('certificate_redcert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.entityredcerttradingcertificate')),
                        ('certificate_sn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.entitysntradingcertificate')),
                        ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
                        ('production_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producers.productionsite')),
                    ],
                    options={
                        'verbose_name': 'Certificat de site de production',
                        'verbose_name_plural': 'Certificats de sites de productions',
                        'db_table': 'production_sites_certificates',
                    },
                ),
                migrations.CreateModel(
                    name='ISCCCertificateScope',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.iscccertificate')),
                        ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.isccscope')),
                    ],
                    options={
                        'verbose_name': 'ISCC Certificate Scope',
                        'verbose_name_plural': 'ISCC Certificate Scopes',
                        'db_table': 'iscc_certificates_scopes',
                    },
                ),
                migrations.CreateModel(
                    name='ISCCCertificateRawMaterial',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('raw_material', models.CharField(max_length=128)),
                        ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.iscccertificate')),
                    ],
                    options={
                        'verbose_name': 'ISCC Certificate Raw Material',
                        'verbose_name_plural': 'ISCC Certificate Raw Materials',
                        'db_table': 'iscc_certificates_raw_materials',
                    },
                ),
                migrations.AddField(
                    model_name='entityredcerttradingcertificate',
                    name='certificate',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.redcertcertificate'),
                ),
                migrations.AddField(
                    model_name='entityredcerttradingcertificate',
                    name='entity',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
                ),
                migrations.AddField(
                    model_name='entityiscctradingcertificate',
                    name='certificate',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.iscccertificate'),
                ),
                migrations.AddField(
                    model_name='entityiscctradingcertificate',
                    name='entity',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
                ),
                migrations.CreateModel(
                    name='DBSCertificateScope',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.dbscertificate')),
                        ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.dbsscope')),
                    ],
                    options={
                        'verbose_name': '2BS Certificate Scope',
                        'verbose_name_plural': '2BS Certificate Scopes',
                        'db_table': 'dbs_certificates_scopes',
                    },
                ),
            ],
            database_operations=[],
        )
    ]
