# Generated by Django 3.2 on 2021-05-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_auto_20210429_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscccertificate',
            name='addons',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='iscccertificate',
            name='download_link',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='iscccertificate',
            name='issuing_cb',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='iscccertificate',
            name='location',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
