# Generated by Django 3.2.4 on 2021-07-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_lotv2_lots_v2_year_87d135_idx'),
        ('certificates', '0010_auto_20210509_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleCoutingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=64)),
                ('certificate_holder', models.CharField(max_length=256)),
                ('registered_address', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
            ],
            options={
                'verbose_name': 'Certificat Double Compte',
                'verbose_name_plural': 'Certificats Double Compte',
                'db_table': 'double_counting_registrations',
            },
        ),
        migrations.CreateModel(
            name='DoubleCoutingRegistrationInputOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biofuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.biocarburant')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.doublecoutingregistration')),
                ('feedstock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matierepremiere')),
            ],
            options={
                'verbose_name': 'Périmètre Certificat Double Compte',
                'verbose_name_plural': 'Périmètres Certificats Double Compte',
                'db_table': 'double_counting_registrations_scope',
            },
        ),
    ]
