# Generated by Django 3.2.4 on 2021-07-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20210726_1338'),
        ('certificates', '0011_doublecoutingregistration_doublecoutingregistrationinputoutput'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoubleCoutingRegistration',
            new_name='DoubleCountingRegistration',
        ),
        migrations.RenameModel(
            old_name='DoubleCoutingRegistrationInputOutput',
            new_name='DoubleCountingRegistrationInputOutput',
        ),
    ]
