# Generated by Django 3.2.8 on 2021-12-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_auto_20211214_1910'),
        ('certificates', '0012_auto_20210726_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsitecertificate',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entitycertificate'),
        ),
    ]
