from tiruert.views.operation import OperationViewSet
from tiruert.views.objective import ObjectiveViewSet
from tiruert.views.elec_operation import ElecOperationViewSet
from tiruert.views.mac_fossil_fuel import MacFossilFuelExportViewSet