class SafTicketError:
    TICKET_DETAILS_FAILED = "TICKET_DETAILS_FAILED"
    MALFORMED_PARAMS = "MALFORMED_PARAMS"
    TICKET_REJECTION_FAILED = "TICKET_REJECTION_FAILED"
    TICKET_NOT_FOUND = "TICKET_NOT_FOUND"
    TICKET_ACCEPTANCE_FAILED = "TICKET_ACCEPTANCE_FAILED"
    TICKET_CANCELLATION_FAILED = "TICKET_CANCELLATION_FAILED"
