from .patch import BiomethaneEntityConfigAgreementPatchMixin
from .list import BiomethaneEntityConfigAgreementListMixin


class BiomethaneEntityConfigAgreementMixin(BiomethaneEntityConfigAgreementPatchMixin, BiomethaneEntityConfigAgreementListMixin):
    pass