# Generated by Django 5.0.6 on 2024-10-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apikey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
