FROM node:alpine AS node

WORKDIR /app

COPY front/package.json /app/

RUN npm install

COPY front /app

RUN npm run build

FROM nginx:latest

COPY ./docker/nginx/ /etc/nginx/conf.d/
COPY ./web/static /var/www/html
COPY --from=node /app/dist /var/www/html_v2
COPY ./docker/run_nginx.sh /opt/run_nginx.sh
