FROM node:alpine

WORKDIR /app

COPY front/public /app/public
COPY front/tsconfig.json /app/
COPY front/package.json /app/
COPY front/package-lock.json /app/

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install --legacy-peer-deps

COPY front/src /app/src

CMD ["npm", "run", "start"]
