# Generated by Django 5.2.2 on 2026-07-29 13:49

import django.db.models.deletion
from django.db import migrations, models

import core.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transactions", "0020_site_commissioning_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="H2Station",
            fields=[
                (
                    "site_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transactions.site",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Privé")],
                        max_length=8,
                        verbose_name="Nature d'accès au site",
                    ),
                ),
                (
                    "distributed_pressure",
                    core.models.fields.JSONChoiceField(
                        choices=[(350, "350 bars"), (700, "700 bars")],
                        default=list,
                        verbose_name="Pression de l'hydrogène distribué",
                    ),
                ),
                (
                    "has_personal_vehicle_connector",
                    models.BooleanField(
                        default=False, verbose_name="Connecteurs compatibles avec les véhicules particuliers"
                    ),
                ),
                ("storage_capacity", models.IntegerField(verbose_name="Capacité de stockage sur site")),
                ("distribution_capacity", models.IntegerField(verbose_name="Capacité de distribution")),
            ],
            bases=("transactions.site",),
        ),
    ]
