# Generated by Django 5.2.2 on 2026-08-05 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("h2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="h2station",
            name="distribution_capacity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)], verbose_name="Capacité de distribution"
            ),
        ),
        migrations.AlterField(
            model_name="h2station",
            name="storage_capacity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)], verbose_name="Capacité de stockage sur site"
            ),
        ),
    ]
