# Generated by Django 5.2.2 on 2026-09-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("h2", "0002_alter_h2station_distribution_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="h2station",
            name="has_compliant_measuring_instruments",
            field=models.BooleanField(
                default=False,
                verbose_name="Instruments de mesure de la masse d'H2 conformes au décret 2001-387",
            ),
        ),
    ]
