---
- name: Create docker group
  group:
    name: docker
    state: present
    
- name: Create default user
  user:
    name: "{{ username }}"
    groups: wheel,docker
    password: "{{ password }}"
    shell: /bin/bash
    update_password: always
    state: present

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', public_key) }}"
