- name: Add kubernetes repository key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add kubernetes repo to apt sources
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: "apt-get update"
  apt:
    update_cache: yes

- name: Install kubernetes packages
  apt:
    name: ['kubeadm', 'kubelet', 'kubectl']

- name: Install nfs
  apt:
    name: ['nfs-common']



