# Generated by Django 4.0.2 on 2022-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eecstats',
            name='default_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='epstats',
            name='default_value_max_eec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='epstats',
            name='default_value_min_eec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='etdstats',
            name='default_value',
            field=models.FloatField(default=0.0),
        ),
    ]
