# Generated by Django 4.1.1 on 2022-10-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
        ("core", "0004_entity_has_saf_tickets"),
        ("saf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safticketsource",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saf_source_owner",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="safticketsource",
            name="carbure_producer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saf_source_producer",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="safticketsource",
            name="country_of_origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saf_source_origin_country",
                to="core.pays",
            ),
        ),
        migrations.AlterField(
            model_name="safticketsource",
            name="production_country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saf_source_production_country",
                to="core.pays",
            ),
        ),
        migrations.CreateModel(
            name="SafTicket",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("carbure_id", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("year", models.IntegerField()),
                ("period", models.IntegerField()),
                ("agreement_reference", models.CharField(max_length=64, unique=True)),
                ("agreement_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("volume", models.FloatField()),
                ("unknown_producer", models.CharField(blank=True, default=None, max_length=64, null=True)),
                ("unknown_production_site", models.CharField(blank=True, default=None, max_length=64, null=True)),
                ("production_site_commissioning_date", models.DateField(blank=True, null=True)),
                ("eec", models.FloatField(default=0.0)),
                ("el", models.FloatField(default=0.0)),
                ("ep", models.FloatField(default=0.0)),
                ("etd", models.FloatField(default=0.0)),
                ("eu", models.FloatField(default=0.0)),
                ("esca", models.FloatField(default=0.0)),
                ("eccs", models.FloatField(default=0.0)),
                ("eccr", models.FloatField(default=0.0)),
                ("eee", models.FloatField(default=0.0)),
                ("ghg_total", models.FloatField(default=0.0)),
                ("ghg_reference", models.FloatField(default=0.0)),
                ("ghg_reduction", models.FloatField(default=0.0)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saf_owner",
                        to="core.entity",
                    ),
                ),
                (
                    "biofuel",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.biocarburant"),
                ),
                (
                    "carbure_producer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saf_producer",
                        to="core.entity",
                    ),
                ),
                (
                    "carbure_production_site",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saf_production_site",
                        to="producers.productionsite",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.entity"
                    ),
                ),
                (
                    "country_of_origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saf_origin_country",
                        to="core.pays",
                    ),
                ),
                (
                    "feedstock",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.matierepremiere"),
                ),
                (
                    "parent_ticket_source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saf_ticket",
                        to="saf.safticketsource",
                    ),
                ),
                (
                    "production_country",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saf_production_country",
                        to="core.pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket SAF",
                "verbose_name_plural": "Tickets SAF",
                "db_table": "saf_ticket",
                "ordering": ["carbure_id"],
            },
        ),
    ]
