# Generated by Django 4.1.1 on 2022-10-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0002_alter_safticketsource_added_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="safticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("ACCEPTED", "Accepté"),
                    ("REJECTED", "Refusé"),
                ],
                default="PENDING",
                max_length=24,
            ),
        ),
    ]
