# Generated by Django 4.1.1 on 2022-10-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0004_alter_safticketsource_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safticket",
            name="agreement_date",
            field=models.DateField(null=True),
        ),
    ]
