# Generated by Django 4.1.1 on 2022-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0005_alter_safticket_agreement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safticket",
            name="agreement_reference",
            field=models.CharField(max_length=64),
        ),
    ]
