# Generated by Django 4.1.1 on 2022-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0011_alter_safticket_carbure_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safticket",
            name="agreement_reference",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
