# Generated by Django 4.1.1 on 2022-11-23 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0013_safticket_client_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="safticketsource",
            old_name="period",
            new_name="delivery_period",
        ),
    ]
