# Generated by Django 4.1.1 on 2022-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0015_rename_period_safticket_assignment_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="safticket",
            name="free_field",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
