# Generated by Django 5.0.6 on 2025-01-29 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0021_alter_safticket_carbure_production_site_and_more"),
        ("transactions", "0010_site_icao_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="safticket",
            name="consumption_type",
            field=models.CharField(
                blank=True,
                choices=[("MAC", "MAC"), ("MAC_DECLASSEMENT", "MAC_DECLASSEMENT")],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="safticket",
            name="reception_airport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saf_source_reception_airport",
                to="transactions.site",
            ),
        ),
        migrations.AddField(
            model_name="safticket",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PIPELING", "PIPELING"),
                    ("TRUCK", "TRUCK"),
                    ("TRAIN", "TRAIN"),
                    ("BARGE", "BARGE"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
