# Generated by Django 5.0.6 on 2025-01-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0021_alter_safticket_carbure_production_site_and_more"),
        ("transactions", "0009_alter_site_site_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="safticketsource",
            name="consumption_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Mise à consommation mandat FR/EU",
                        "Mise à consommation mandat FR/EU",
                    ),
                    (
                        "Mise à consommation hors mandat (déclassement)",
                        "Mise à consommation hors mandat (déclassement)",
                    ),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="safticketsource",
            name="reception_airport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saf_source_reception_airport",
                to="transactions.site",
            ),
        ),
        migrations.AddField(
            model_name="safticketsource",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Oléoduc", "Oléoduc"),
                    ("Camion", "Camion"),
                    ("Train", "Train"),
                    ("Barge", "Barge"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
