# Generated by Django 5.0.6 on 2025-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0022_safticket_consumption_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="safticket",
            name="ets_declaration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safticket",
            name="ets_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ETS_VALUATION", "Valorisation ETS"),
                    ("OUTSIDE_ETS", "Hors ETS (schéma volontaire)"),
                    ("NOT_CONCERNED", "Non concerné"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="safticket",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[("PIPELINE", "PIPELINE"), ("TRUCK", "TRUCK"), ("TRAIN", "TRAIN"), ("BARGE", "BARGE")],
                max_length=64,
                null=True,
            ),
        ),
    ]
