# Generated by Django 5.0.6 on 2025-02-11 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0024_alter_safticket_ets_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safticket",
            name="ets_declaration_date",
        ),
    ]
