# Generated by Django 5.0.6 on 2025-07-21 15:53

from django.db import migrations


def clean_dgac_admin_rights(apps, schema_editor):
    Entity = apps.get_model("core", "Entity")
    UserRights = apps.get_model("core", "UserRights")
    User = apps.get_model("authtools.User")

    dgac_rights = UserRights.objects.filter(entity__name="DGAC", user__email__endswith="@aviation-civile.gouv.fr")
    dgac_users = User.objects.filter(is_active=True, pk__in=dgac_rights.values_list("user_id", flat=True))
    airlines = Entity.objects.filter(entity_type="Compagnie aérienne")

    dgac_airline_rights = UserRights.objects.filter(user__in=dgac_users, entity__in=airlines).values_list("pk", flat=True)
    UserRights.objects.filter(pk__in=dgac_airline_rights).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0025_remove_safticket_ets_declaration_date"),
    ]

    operations = [
        migrations.RunPython(clean_dgac_admin_rights, migrations.RunPython.noop),
    ]
