# Generated by Django 5.2.2 on 2025-07-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_alter_entity_entity_type"),
        ("saf", "0026_clean_dgac_admin_rights"),
        ("transactions", "0015_alter_site_collation"),
    ]

    operations = [
        migrations.AddField(
            model_name="safticket",
            name="origin_lot",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_saf_ticket",
                to="core.carburelot",
            ),
        ),
        migrations.AddField(
            model_name="safticket",
            name="origin_lot_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_saf_ticket",
                to="transactions.site",
            ),
        ),
        migrations.AddField(
            model_name="safticketsource",
            name="origin_lot",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_saf_ticket_source",
                to="core.carburelot",
            ),
        ),
        migrations.AddField(
            model_name="safticketsource",
            name="origin_lot_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_saf_ticket_source",
                to="transactions.site",
            ),
        ),
    ]
