# Generated by Django 5.2.2 on 2025-07-30 13:12

from django.db import migrations


def propagate_saf_origin(apps, schema_editor):
    from core.traceability import bulk_update_traceability_nodes, get_traceability_nodes

    CarbureLot = apps.get_model("core", "CarbureLot")

    saf_lots = CarbureLot.objects.filter(safticketsource__isnull=False)

    nodes = get_traceability_nodes(saf_lots)

    updated_nodes = []
    for node in nodes:
        updated_nodes += node.propagate()

    bulk_update_traceability_nodes(updated_nodes)


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0027_safticket_origin_lot_safticket_origin_lot_site_and_more"),
    ]

    operations = [
        migrations.RunPython(propagate_saf_origin, migrations.RunPython.noop),
    ]
