# Generated by Django 5.2.2 on 2025-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0028_propagate_saf_origin_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="safticket",
            name="pos_poc_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
