# Generated by Django 5.2.2 on 2025-11-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0029_safticket_pos_poc_number"),
        ("transactions", "0016_split_site_into_concrete_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safticket",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRUCK", "Routier"),
                    ("BARGE", "Barge"),
                    ("TRAIN", "Train"),
                    ("PIPELINE", "Oléoduc"),
                    ("PIPELINE_DMM", "Oléoduc DMM"),
                    ("PIPELINE_LHP", "Oléoduc LHP"),
                    ("PIPELINE_ODC", "Oléoduc ODC"),
                    ("PIPELINE_SPMR", "Oléoduc SPMR"),
                    ("PIPELINE_SPSE", "Oléoduc SPSE"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SafLogistics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("has_intermediary_depot", models.BooleanField(default=False)),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("TRUCK", "Routier"),
                            ("BARGE", "Barge"),
                            ("TRAIN", "Train"),
                            ("PIPELINE", "Oléoduc"),
                            ("PIPELINE_DMM", "Oléoduc DMM"),
                            ("PIPELINE_LHP", "Oléoduc LHP"),
                            ("PIPELINE_ODC", "Oléoduc ODC"),
                            ("PIPELINE_SPMR", "Oléoduc SPMR"),
                            ("PIPELINE_SPSE", "Oléoduc SPSE"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "destination_airport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airport_from_depot_routes",
                        to="transactions.airport",
                    ),
                ),
                (
                    "origin_depot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depot_to_airport_routes",
                        to="transactions.depot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logistique SAF",
                "verbose_name_plural": "Logistiques SAF",
                "db_table": "saf_logistics",
                "ordering": ["created_at"],
            },
        ),
    ]
