# Generated by Django 5.2.2 on 2025-12-14 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0029_safticket_pos_poc_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safticket",
            name="pos_poc_number",
        ),
    ]
