# Generated by Django 5.2.2 on 2025-12-17 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0030_alter_safticket_shipping_method_saflogistics"),
        ("saf", "0030_remove_safticket_pos_poc_number"),
    ]

    operations = []
