# Generated by Django 5.2.2 on 2025-12-14 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0030_alter_safticket_shipping_method_saflogistics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safticket",
            name="pos_poc_number",
        ),
    ]
