# Generated by Django 5.2.2 on 2026-02-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saf", "0031_merge_20251217_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saflogistics",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("TRUCK", "Routier"),
                    ("BARGE", "Barge"),
                    ("TRAIN", "Train"),
                    ("SHIP", "Bateau"),
                    ("PIPELINE", "Oléoduc"),
                    ("PIPELINE_DMM", "Oléoduc DMM"),
                    ("PIPELINE_LHP", "Oléoduc LHP"),
                    ("PIPELINE_ODC", "Oléoduc ODC"),
                    ("PIPELINE_SPMR", "Oléoduc SPMR"),
                    ("PIPELINE_SPSE", "Oléoduc SPSE"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="safticket",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRUCK", "Routier"),
                    ("BARGE", "Barge"),
                    ("TRAIN", "Train"),
                    ("SHIP", "Bateau"),
                    ("PIPELINE", "Oléoduc"),
                    ("PIPELINE_DMM", "Oléoduc DMM"),
                    ("PIPELINE_LHP", "Oléoduc LHP"),
                    ("PIPELINE_ODC", "Oléoduc ODC"),
                    ("PIPELINE_SPMR", "Oléoduc SPMR"),
                    ("PIPELINE_SPSE", "Oléoduc SPSE"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
