# Generated by Django 5.2.2 on 2026-05-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_change_feedstock_collation"),
        ("saf", "0032_alter_saflogistics_shipping_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="safticket",
            name="export_country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saf_export_country",
                to="core.pays",
            ),
        ),
        migrations.AddField(
            model_name="safticket",
            name="unknown_airline_client",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="safticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("ACCEPTED", "Accepté"),
                    ("REJECTED", "Refusé"),
                    ("EXPORTED", "Exporté"),
                ],
                default="PENDING",
                max_length=24,
            ),
        ),
    ]
