# Generated by Django 3.0.2 on 2020-01-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200124_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuserrights',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlatformUser'),
        ),
    ]
