# Generated by Django 4.1.1 on 2022-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="has_saf_tickets",
            field=models.BooleanField(default=False),
        ),
    ]
