# Generated by Django 3.0.2 on 2020-01-27 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200124_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlatformUser',
            new_name='UserDetails',
        ),
        migrations.RenameModel(
            old_name='PlatformUserRights',
            new_name='UserRights',
        ),
    ]
