# Generated by Django 4.1.1 on 2022-10-20 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_entity_has_saf_tickets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="has_saf_tickets",
            new_name="has_saf",
        ),
    ]
