# Generated by Django 3.0.3 on 2020-02-23 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200204_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiliereProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Filiere de Production',
                'verbose_name_plural': 'Filieres de Production',
                'db_table': 'filieres_production',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pays', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'db_table': 'pays',
            },
        ),
        migrations.CreateModel(
            name='TypeBiocarburant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Type de Biocarburant',
                'verbose_name_plural': 'Types de Biocarburants',
                'db_table': 'type_biocarburants',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot', models.CharField(blank=True, max_length=64)),
                ('num_dae', models.CharField(blank=True, max_length=64)),
                ('date_entree', models.DateField(blank=True)),
                ('volume', models.IntegerField(default=0)),
                ('categorie', models.CharField(max_length=64)),
                ('systeme_fournisseur', models.CharField(max_length=64)),
                ('respect_crit_durabilite', models.BooleanField(default=False)),
                ('ges_transport', models.FloatField(blank=True)),
                ('ges_distribution', models.FloatField(blank=True)),
                ('ges_fossile', models.FloatField(blank=True)),
                ('date_mise_en_service', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Validated', 'Validated'), ('Declared', 'Declared')], default='Draft', max_length=64)),
                ('filiere_production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.FiliereProduction')),
                ('pays_origine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays_origine', to='core.Pays')),
                ('pays_production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays_production', to='core.Pays')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'lots',
            },
        ),
    ]
