# Generated by Django 4.1.1 on 2022-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_has_saf_tickets_entity_has_saf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carburenotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("CORRECTION_REQUEST", "CORRECTION_REQUEST"),
                    ("CORRECTION_DONE", "CORRECTION_DONE"),
                    ("LOTS_REJECTED", "LOTS_REJECTED"),
                    ("LOTS_RECEIVED", "LOTS_RECEIVED"),
                    ("LOTS_RECALLED", "LOTS_RECALLED"),
                    ("CERTIFICATE_EXPIRED", "CERTIFICATE_EXPIRED"),
                    ("DECLARATION_VALIDATED", "DECLARATION_VALIDATED"),
                    ("DECLARATION_CANCELLED", "DECLARATION_CANCELLED"),
                    ("DECLARATION_REMINDER", "DECLARATION_REMINDER"),
                    ("SAF_TICKET_REJECTED", "SAF_TICKET_REJECTED"),
                    ("SAF_TICKET_ACCEPTED", "SAF_TICKET_ACCEPTED"),
                    ("SAF_TICKET_RECEIVED", "SAF_TICKET_RECEIVED"),
                ],
                max_length=32,
            ),
        ),
    ]
