# Generated by Django 3.0.3 on 2020-02-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userpreferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='current_entity',
            new_name='default_entity',
        ),
    ]
