# Generated by Django 3.0.3 on 2020-02-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200223_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Entity'),
        ),
    ]
