# Generated by Django 3.0.3 on 2020-02-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
        ('core', '0009_lot_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='attestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producers.AttestationProducer'),
        ),
    ]
