# Generated by Django 3.0.3 on 2020-02-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lot_attestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated', to='core.Entity'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer', to='core.Entity'),
        ),
    ]
