# Generated by Django 3.0.3 on 2020-02-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200224_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='ges_distribution',
            new_name='ges_transport_distrib',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='ges_transport',
        ),
    ]
