# Generated by Django 4.1.7 on 2023-06-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="has_elec",
            field=models.BooleanField(default=False),
        ),
    ]
