# Generated by Django 3.0.3 on 2020-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200312_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='volume2',
            field=models.IntegerField(default=0),
        ),
    ]
