# Generated by Django 4.1.7 on 2023-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_entity_has_elec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaladminrights",
            name="right",
            field=models.CharField(
                choices=[
                    ("DCA", "DCA"),
                    ("AGRIMER", "AGRIMER"),
                    ("TIRIB", "TIRIB"),
                    ("AIRLINE", "AIRLINE"),
                    ("ELEC", "ELEC"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
