# Generated by Django 4.1.7 on 2023-08-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_entity_has_elec"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrights",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente de validation"),
                    ("ACCEPTED", "Accepté"),
                    ("REJECTED", "Refusé"),
                    ("REVOKED", "Révoqué"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
