# Generated by Django 3.0.3 on 2020-03-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_lot_volume2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='matiere_premiere2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TypeBiocarburant'),
        ),
    ]
