# Generated by Django 4.1.7 on 2023-08-17 13:34

from django.db import migrations


def set_user_rights_status(apps, schema_editor):
    UserRights = apps.get_model("core", "UserRights")
    UserRightsRequests = apps.get_model("core", "UserRightsRequests")

    user_rights = list(UserRights.objects.all())
    user_rights_requests = list(UserRightsRequests.objects.all())

    for user_right in user_rights:
        for user_right_request in user_rights_requests:
            if user_right_request.user_id == user_right.user_id and user_right_request.entity_id == user_right.entity_id:
                user_right.status = user_right_request.status

    UserRights.objects.bulk_update(user_rights, ["status"])


def clear_user_rights_status(apps, schema_editor):
    UserRights = apps.get_model("core", "UserRights")
    UserRights.objects.all().update(status="")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_userrights_status"),
    ]

    operations = [
        migrations.RunPython(set_user_rights_status, reverse_code=clear_user_rights_status),
    ]
