# Generated by Django 4.1.7 on 2024-01-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_carburenotification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carburelot",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "UNKNOWN"),
                    ("RFC", "RFC"),
                    ("STOCK", "STOCK"),
                    ("BLENDING", "BLENDING"),
                    ("EXPORT", "EXPORT"),
                    ("TRADING", "TRADING"),
                    ("PROCESSING", "PROCESSING"),
                    ("DIRECT", "DIRECT"),
                    ("FLUSHED", "FLUSHED"),
                    ("CONSUMPTION", "CONSUMPTION"),
                ],
                default="UNKNOWN",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("Producteur", "Producteur"),
                    ("Opérateur", "Opérateur"),
                    ("Administration", "Administration"),
                    ("Trader", "Trader"),
                    ("Auditor", "Auditeur"),
                    ("Administration Externe", "Administration Externe"),
                    ("Compagnie aérienne", "Compagnie aérienne"),
                    ("Unknown", "Unknown"),
                    ("Power Station", "Centrale électrique"),
                ],
                default="Unknown",
                max_length=64,
            ),
        ),
    ]
