# Generated by Django 3.0.3 on 2020-03-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0010_auto_20200304_1639'),
        ('core', '0018_auto_20200312_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeBiocarburant',
            new_name='Biocarburant',
        ),
        migrations.AlterModelOptions(
            name='biocarburant',
            options={'verbose_name': 'Biocarburant', 'verbose_name_plural': 'Biocarburants'},
        ),
        migrations.AlterModelTable(
            name='biocarburant',
            table='biocarburants',
        ),
    ]
