# Generated by Django 4.1.7 on 2024-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="electrical_efficiency",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="depot",
            name="thermal_efficiency",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="depot",
            name="useful_temperature",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="depot_type",
            field=models.CharField(
                choices=[
                    ("OTHER", "Autre"),
                    ("EFS", "EFS"),
                    ("EFPE", "EFPE"),
                    ("OIL DEPOT", "OIL DEPOT"),
                    ("BIOFUEL DEPOT", "BIOFUEL DEPOT"),
                    ("HEAT PLANT", "HEAT PLANT"),
                    ("POWER PLANT", "POWER PLANT"),
                    ("COGENERATION PLANT", "COGENERATION PLANT"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
    ]
