# Generated by Django 3.0.3 on 2020-03-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200312_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocarburant',
            name='code',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='code',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
