# Generated by Django 4.1.7 on 2024-02-08 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_depot_electrical_efficiency_depot_thermal_efficiency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depot",
            name="electrical_efficiency",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Entre 0 et 1",
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="depot",
            name="thermal_efficiency",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Entre 0 et 1",
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="depot",
            name="useful_temperature",
            field=models.FloatField(blank=True, default=None, help_text="En degrés Celsius", null=True),
        ),
    ]
