# Generated by Django 3.0.3 on 2020-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200319_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
