# Generated by Django 4.1.7 on 2024-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_depot_electrical_efficiency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="activity_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="entity",
            name="sustainability_officer_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
    ]
