# Generated by Django 3.0.3 on 2020-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200319_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='ea_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
