# Generated by Django 3.0.3 on 2020-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200320_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='carbure_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('Draft', 'Brouillon'), ('Validated', 'Validé')], default='Draft', max_length=64),
        ),
    ]
