# Generated by Django 4.1.7 on 2024-03-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_entity_activity_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="country",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.pays"),
        ),
    ]
