# Generated by Django 4.1.7 on 2024-03-26 14:13

from django.db import migrations


def get_old_countries_values(apps, schema_editor):
    Pays = apps.get_model("core", "Pays")
    countries = Pays.objects.all()

    Entity = apps.get_model("core", "Entity")
    entities = Entity.objects.all()

    for entity in entities:
        for country in countries:
            old_name = entity.registered_country.lower()
            if (
                old_name == country.name.lower()
                or old_name.lower() == country.code_pays.lower()
                or old_name.lower() == country.name_en.lower()
            ):
                entity.country = country
        print(f"Entity {entity.registered_country} > {entity.country}")
    Entity.objects.bulk_update(entities, ["country"])


def reverse_get_old_countries_values(apps, schema_editor):
    Entity = apps.get_model("core", "Entity")
    Entity.objects.all().update(country=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_entity_country"),
    ]

    operations = [
        migrations.RunPython(get_old_countries_values, reverse_code=reverse_get_old_countries_values),
    ]
