# Generated by Django 3.0.3 on 2020-03-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200326_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='e',
        ),
    ]
