# Generated by Django 4.1.7 on 2024-03-26 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_remove_entity_registered_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="country",
            new_name="registered_country",
        ),
    ]
