# Generated by Django 4.1.7 on 2024-03-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_rename_country_entity_registered_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="registered_address",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="entity",
            name="registered_city",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="entity",
            name="registered_zipcode",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
