# Generated by Django 3.0.3 on 2020-03-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_lot_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHGValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=256, null=True)),
                ('field', models.CharField(choices=[('eec', 'eec'), ('ep', 'ep'), ('etd', 'etd'), ('xxx', 'xxx')], default='xxx', max_length=8)),
                ('is_default_value', models.BooleanField(default=False)),
                ('is_typical_value', models.BooleanField(default=False)),
                ('value', models.FloatField(default=0.0)),
                ('biocarburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Biocarburant')),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MatierePremiere')),
            ],
            options={
                'verbose_name': 'Valeur GES de référence',
                'verbose_name_plural': 'Valeurs GES de référence',
                'db_table': 'ghg_values',
            },
        ),
    ]
