# Generated by Django 4.1.7 on 2024-03-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_entity_registered_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
