# Generated by Django 3.0.3 on 2020-03-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_ghgvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghgvalues',
            name='matiere_premiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MatierePremiere'),
        ),
    ]
