# Generated by Django 3.0.3 on 2020-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200327_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghgvalues',
            name='field',
        ),
        migrations.RemoveField(
            model_name='ghgvalues',
            name='is_default_value',
        ),
        migrations.RemoveField(
            model_name='ghgvalues',
            name='is_typical_value',
        ),
        migrations.RemoveField(
            model_name='ghgvalues',
            name='value',
        ),
        migrations.AddField(
            model_name='ghgvalues',
            name='eec_default',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ghgvalues',
            name='eec_typical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ghgvalues',
            name='ep_default',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ghgvalues',
            name='ep_typical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ghgvalues',
            name='etd_default',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ghgvalues',
            name='etd_typical',
            field=models.FloatField(default=0.0),
        ),
    ]
