# Generated by Django 4.1.7 on 2024-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_entity_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="vat_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="entity",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
