# Generated by Django 4.1.7 on 2024-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_entity_vat_number_entity_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("Producteur", "Producteur"),
                    ("Opérateur", "Opérateur"),
                    ("Administration", "Administration"),
                    ("Trader", "Trader"),
                    ("Auditor", "Auditeur"),
                    ("Administration Externe", "Administration Externe"),
                    ("Charge Point Operator", "Charge Point Operator"),
                    ("Compagnie aérienne", "Compagnie aérienne"),
                    ("Unknown", "Unknown"),
                    ("Power or Heat Producer", "Producteur d'électricité ou de chaleur"),
                ],
                default="Unknown",
                max_length=64,
            ),
        ),
    ]
