# Generated by Django 4.1.7 on 2024-04-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carburenotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("CORRECTION_REQUEST", "CORRECTION_REQUEST"),
                    ("CORRECTION_DONE", "CORRECTION_DONE"),
                    ("LOTS_REJECTED", "LOTS_REJECTED"),
                    ("LOTS_RECEIVED", "LOTS_RECEIVED"),
                    ("LOTS_RECALLED", "LOTS_RECALLED"),
                    ("CERTIFICATE_EXPIRED", "CERTIFICATE_EXPIRED"),
                    ("CERTIFICATE_REJECTED", "CERTIFICATE_REJECTED"),
                    ("DECLARATION_VALIDATED", "DECLARATION_VALIDATED"),
                    ("DECLARATION_CANCELLED", "DECLARATION_CANCELLED"),
                    ("METER_READINGS_APP_STARTED", "METER_READINGS_APP_STARTED"),
                    ("METER_READINGS_APP_ENDING_SOON", "METER_READINGS_APP_ENDING_SOON"),
                    ("DECLARATION_REMINDER", "DECLARATION_REMINDER"),
                    ("SAF_TICKET_REJECTED", "SAF_TICKET_REJECTED"),
                    ("SAF_TICKET_ACCEPTED", "SAF_TICKET_ACCEPTED"),
                    ("SAF_TICKET_RECEIVED", "SAF_TICKET_RECEIVED"),
                    ("LOTS_UPDATED_BY_ADMIN", "LOTS_UPDATED_BY_ADMIN"),
                    ("LOTS_DELETED_BY_ADMIN", "LOTS_DELETED_BY_ADMIN"),
                    ("ELEC_TRANSFER_CERTIFICATE", "ELEC_TRANSFER_CERTIFICATE"),
                ],
                max_length=32,
            ),
        ),
    ]
