# Generated by Django 3.0.3 on 2020-04-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_lot_ea_delivery_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='dae',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
