# Generated by Django 5.0.6 on 2024-07-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_carburenotification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
