# Generated by Django 5.0.6 on 2024-07-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_depot_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="entity",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.entity"),
        ),
    ]
