# Generated by Django 5.0.6 on 2024-09-27 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_depot_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitydepot",
            name="blender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blender_old",
                to="core.entity",
            ),
        ),
    ]
