# Generated by Django 3.0.3 on 2020-04-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_lotcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotcomment',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Entity'),
        ),
    ]
