# Generated by Django 5.0.6 on 2024-09-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_entitydepot_blender"),
        ("transactions", "0005_move_data_to_site_model_backup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carburelot",
            name="carbure_delivery_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carbure_delivery_site",
                to="transactions.site",
            ),
        ),
        migrations.AlterField(
            model_name="carburelot",
            name="carbure_dispatch_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carbure_dispatch_site",
                to="transactions.site",
            ),
        ),
        migrations.AlterField(
            model_name="carburelot",
            name="carbure_production_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.site",
            ),
        ),
        migrations.AlterField(
            model_name="carburestock",
            name="carbure_production_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_production_site",
                to="transactions.site",
            ),
        ),
        migrations.AlterField(
            model_name="carburestock",
            name="depot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.site",
            ),
        ),
    ]
