# Generated by Django 3.0.3 on 2020-04-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200424_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='ea_override',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='ea_overriden',
        ),
        migrations.AlterField(
            model_name='lot',
            name='ea_delivery_status',
            field=models.CharField(choices=[('N', 'N/A'), ('A', 'Accepté'), ('R', 'Refusé'), ('AC', 'En attente de correction'), ('AA', 'En attente de validation')], default='N', max_length=64),
        ),
        migrations.CreateModel(
            name='LotError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('error', models.CharField(max_length=256)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lot')),
            ],
            options={
                'verbose_name': 'LotError',
                'verbose_name_plural': 'LotErrors',
                'db_table': 'lots_errors',
            },
        ),
    ]
