# Generated by Django 5.0.6 on 2024-12-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_depot_depot_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matierepremiere",
            name="category",
            field=models.CharField(
                choices=[
                    ("CONV", "Conventionnel"),
                    ("ANN-IX-A", "ANNEXE IX-A"),
                    ("ANN-IX-B", "ANNEXE IX-B"),
                    ("TALLOL", "Tallol"),
                    ("OTHER", "Autre"),
                    ("EP2AM", "EP2AM"),
                ],
                default="CONV",
                max_length=32,
            ),
        ),
    ]
