# Generated by Django 5.0.6 on 2025-02-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_matierepremiere_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaladminrights",
            name="right",
            field=models.CharField(
                choices=[
                    ("DCA", "DCA"),
                    ("AGRIMER", "AGRIMER"),
                    ("TIRIB", "TIRIB"),
                    ("AIRLINE", "AIRLINE"),
                    ("ELEC", "ELEC"),
                    ("TRANSFERRED_ELEC", "TRANSFERRED_ELEC"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
