# Generated by Django 3.0.3 on 2020-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200507_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='ea_delivery_status',
            field=models.CharField(choices=[('N', 'En Attente'), ('A', 'Accepté'), ('R', 'Refusé'), ('AC', 'À corriger'), ('AA', 'Corrigé')], default='N', max_length=64),
        ),
    ]
