# Generated by Django 5.0.6 on 2025-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_externaladminrights_right"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="accise_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="entity",
            name="is_tiruert_liable",
            field=models.BooleanField(default=False),
        ),
    ]
