# Generated by Django 3.0.3 on 2020-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocarburant',
            name='masse_volumique',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='biocarburant',
            name='pci_kg',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='biocarburant',
            name='pci_litre',
            field=models.BooleanField(default=0),
        ),
    ]
