# Generated by Django 3.0.3 on 2020-06-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='ea_delivery_site_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Depot'),
        ),
    ]
