# Generated by Django 5.0.6 on 2025-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_matierepremiere_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="biocarburant",
            name="renewable_energy_share",
            field=models.FloatField(blank=True, default=1.0, help_text="saisir 0,50 pour 50%", null=True),
        ),
    ]
