# Generated by Django 3.0.3 on 2020-06-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200605_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biocarburant',
            name='masse_volumique',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biocarburant',
            name='pci_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biocarburant',
            name='pci_litre',
            field=models.FloatField(default=0),
        ),
    ]
