# Generated by Django 3.0.3 on 2020-06-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200604_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottransaction',
            old_name='undelivery_site',
            new_name='unknown_delivery_site',
        ),
        migrations.RemoveField(
            model_name='lottransaction',
            name='export_hors_ue',
        ),
        migrations.RemoveField(
            model_name='lottransaction',
            name='export_ue',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='client_id',
        ),
        migrations.AddField(
            model_name='lottransaction',
            name='unknown_delivery_site_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_delivery_site_country', to='core.Pays'),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='unknown_production_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_production_site_country', to='core.Pays'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='TransactionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('error', models.CharField(max_length=256)),
                ('tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LotTransaction')),
            ],
            options={
                'verbose_name': 'TransactionError',
                'verbose_name_plural': 'TransactionsErrors',
                'db_table': 'tx_errors',
            },
        ),
    ]
