# Generated by Django 3.0.3 on 2020-06-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200604_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotV2Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('error', models.CharField(max_length=256)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LotV2')),
            ],
            options={
                'verbose_name': 'LotV2Error',
                'verbose_name_plural': 'LotV2Errors',
                'db_table': 'lotsv2_errors',
            },
        ),
    ]
