# Generated by Django 5.0.6 on 2025-05-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_carburelotevent_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="carburestockevent",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.entity",
            ),
        ),
    ]
