# Generated by Django 5.0.6 on 2025-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_carburestockevent_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("Producteur", "Producteur"),
                    ("Opérateur", "Opérateur"),
                    ("Administration", "Administration"),
                    ("Trader", "Trader"),
                    ("Auditor", "Auditeur"),
                    ("Administration Externe", "Administration Externe"),
                    ("Charge Point Operator", "Charge Point Operator"),
                    ("Compagnie aérienne", "Compagnie aérienne"),
                    ("Unknown", "Unknown"),
                    (
                        "Power or Heat Producer",
                        "Producteur d'électricité ou de chaleur",
                    ),
                    ("SAF Trader", "Trader de SAF"),
                ],
                default="Unknown",
                max_length=64,
            ),
        ),
    ]
