# Generated by Django 3.0.3 on 2020-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_lotv2error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotv2',
            name='unknown_producer',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lotv2',
            name='unknown_production_site',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
