# Generated by Django 3.0.3 on 2020-06-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200604_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottransaction',
            name='unknown_vendor',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
