# Generated by Django 5.2.2 on 2025-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="is_red_ii",
            field=models.BooleanField(default=False),
        ),
    ]
