# Generated by Django 3.0.7 on 2020-06-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200604_1724'),
        ('core', '0042_auto_20200605_1800'),
    ]

    operations = [
    ]
