# Generated by Django 5.2.2 on 2025-09-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaladminrights",
            name="right",
            field=models.CharField(
                choices=[
                    ("DCA", "DCA"),
                    ("AGRIMER", "AGRIMER"),
                    ("TIRIB", "TIRIB"),
                    ("AIRLINE", "AIRLINE"),
                    ("ELEC", "ELEC"),
                    ("TRANSFERRED_ELEC", "TRANSFERRED_ELEC"),
                    ("BIOFUEL", "BIOFUEL"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
