# Generated by Django 5.2.2 on 2025-10-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_dept", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "db_table": "departements",
                "ordering": ["code_dept"],
            },
        ),
    ]
