# Generated by Django 3.0.7 on 2020-06-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_lotv2_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotv2',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Entity'),
        ),
        migrations.AlterField(
            model_name='lotv2',
            name='unknown_production_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_production_site_country', to='core.Pays'),
        ),
    ]
