# Generated by Django 5.2.2 on 2025-10-23 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_alter_externaladminrights_right"),
        ("core", "0048_department"),
    ]

    operations = []
