# Generated by Django 5.2.2 on 2025-10-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_merge_20251023_2042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaladminrights",
            name="right",
            field=models.CharField(
                choices=[
                    ("DCA", "DCA"),
                    ("AGRIMER", "AGRIMER"),
                    ("TIRIB", "TIRIB"),
                    ("AIRLINE", "AIRLINE"),
                    ("ELEC", "ELEC"),
                    ("TRANSFERRED_ELEC", "TRANSFERRED_ELEC"),
                    ("BIOFUEL", "BIOFUEL"),
                    ("DREAL", "DREAL"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ExternalAdminDepartments",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="external_admins", to="core.department"
                    ),
                ),
                (
                    "external_admin_right",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_departments",
                        to="core.externaladminrights",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Admin Department",
                "verbose_name_plural": "External Admin Departments",
                "db_table": "ext_admin_departments",
                "unique_together": {("external_admin_right", "department")},
            },
        ),
    ]
