# Generated by Django 3.0.7 on 2020-06-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200611_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottransaction',
            name='unknown_delivery_site_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_delivery_site_country', to='core.Pays'),
        ),
    ]
