# Generated by Django 3.0.7 on 2020-06-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200611_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pays'),
        ),
    ]
