# Generated by Django 5.2.2 on 2025-11-03 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_alter_externaladminrights_right_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityDepartments",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entities", to="core.department"
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="departments", to="core.entity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Departement",
                "db_table": "entity_department",
                "unique_together": {("entity", "department")},
            },
        ),
        migrations.DeleteModel(
            name="ExternalAdminDepartments",
        ),
    ]
