# Generated by Django 5.2.2 on 2025-11-10 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_entitydepartments_delete_externaladmindepartments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EntityDepartments",
        ),
    ]
