# Generated by Django 3.0.7 on 2020-06-15 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_lotv2_added_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
