# Generated by Django 5.2.2 on 2025-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_entity_entity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="is_master",
            field=models.BooleanField(
                default=False, help_text="Indique si l'entité est maître (dans le cas de plusieurs CPO avec le même SIREN)"
            ),
        ),
    ]
