# Generated by Django 5.2.2 on 2025-11-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_entity_is_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericcertificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("SYSTEME_NATIONAL", "SYSTEME_NATIONAL"),
                    ("ISCC", "ISCC"),
                    ("REDCERT", "REDCERT"),
                    ("2BS", "2BS"),
                    ("KZR_INIG", "KZR_INIG"),
                ],
                max_length=32,
            ),
        ),
    ]
