# Generated by Django 3.0.7 on 2020-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200615_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Producteur', 'Producteur'), ('Opérateur', 'Opérateur'), ('Administration', 'Administration'), ('Trader', 'Trader'), ('Unknown', 'Unknown')], default='Unknown', max_length=64),
        ),
    ]
