# Generated by Django 5.2.2 on 2025-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_genericcertificate_certificate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="carburelot",
            name="pos_number",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
