# Generated by Django 5.2.2 on 2025-12-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_genericcertificate_certificate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
