# Generated by Django 3.0.7 on 2020-06-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200616_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='fused_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotv2_fused_with', to='core.LotV2'),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='is_fused',
            field=models.BooleanField(default=False),
        ),
    ]
