# Generated by Django 5.2.2 on 2025-12-17 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_carburelot_pos_number"),
        ("core", "0056_entity_closed_at"),
    ]

    operations = []
