# Generated by Django 3.0.7 on 2020-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20200616_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotv2',
            name='unknown_production_site_com_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
