# Generated by Django 5.2.2 on 2026-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_merge_20251217_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="carburelot",
            name="udb_transaction_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
