# Generated by Django 5.2.2 on 2026-01-06 16:23

from django.db import migrations, models
from django.db.models import Case, CharField, DateField, F, Value, When
from django.utils import timezone


def fill_certificate_status(apps, schema_editor):
    GenericCertificate = apps.get_model("core", "GenericCertificate")

    today = timezone.localdate()

    status_case = Case(
        When(valid_from__gt=today, then=Value("PENDING")),
        When(valid_until__lt=today, then=Value("EXPIRED")),
        default=Value("VALID"),
        output_field=CharField(),
    )

    last_status_update_case = Case(
        When(valid_until__lt=today, then=F("valid_until")),
        default=Value(today),
        output_field=DateField(),
    )

    GenericCertificate.objects.update(
        status=status_case,
        last_status_update=last_status_update_case,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_merge_20251217_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericcertificate",
            name="last_status_update",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="genericcertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("VALID", "Valide"),
                    ("SUSPENDED", "Suspendu"),
                    ("WITHDRAWN", "Retiré"),
                    ("TERMINATED", "Interrompu"),
                    ("EXPIRED", "Expiré"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.RunPython(fill_certificate_status, migrations.RunPython.noop),
    ]
