# Generated by Django 5.2.2 on 2026-01-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_merge_20251217_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericcertificate",
            name="last_status_update",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="genericcertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("VALID", "Valide"),
                    ("SUSPENDED", "Suspendu"),
                    ("WITHDRAWN", "Retiré"),
                    ("TERMINATED", "Interrompu"),
                    ("EXPIRED", "Expiré"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
