# Generated by Django 3.0.7 on 2020-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_transactioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncomment',
            name='topic',
            field=models.CharField(choices=[('SUSTAINABILITY', 'Durabilité'), ('TX', 'Transaction'), ('BOTH', 'Les deux')], default='BOTH', max_length=24),
        ),
    ]
