# Generated by Django 5.2.2 on 2026-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_carburelot_udb_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carburelot",
            name="pos_number",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
