# Generated by Django 5.2.2 on 2026-01-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_genericcertificate_last_status_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericcertificate",
            name="last_status_update",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="genericcertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("VALID", "Valide"),
                    ("SUSPENDED", "Suspendu"),
                    ("WITHDRAWN", "Retiré"),
                    ("TERMINATED", "Interrompu"),
                    ("EXPIRED", "Expiré"),
                ],
                max_length=16,
            ),
        ),
    ]
