# Generated by Django 5.2.2 on 2026-01-19 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_carburelot_udb_transaction_id"),
        ("core", "0059_alter_genericcertificate_last_status_update_and_more"),
    ]

    operations = []
