# Generated by Django 5.2.2 on 2026-02-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_alter_carburelot_pos_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="matierepremiere",
            name="is_biofuel_feedstock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="matierepremiere",
            name="is_methanogenic",
            field=models.BooleanField(default=False),
        ),
    ]
