# Generated by Django 3.0.7 on 2020-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_transactioncomment_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottransaction',
            name='champ_libre',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
