# Generated by Django 5.2.2 on 2026-01-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_merge_20260119_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericcertificate",
            name="suspended_dates",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="genericcertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("VALID", "Valide"),
                    ("SUSPENDED", "Suspendu"),
                    ("WITHDRAWN", "Retiré"),
                    ("TERMINATED", "Interrompu"),
                    ("EXPIRED", "Expiré"),
                ],
                max_length=16,
            ),
        ),
    ]
