# Generated by Django 5.2.2 on 2026-02-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_matierepremiere_is_biofuel_feedstock_and_more"),
        ("feedstocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matierepremiere",
            name="classification",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="feedstocks.classification"
            ),
        ),
        migrations.AlterField(
            model_name="matierepremiere",
            name="category",
            field=models.CharField(
                choices=[
                    ("CONV", "Conventionnel"),
                    ("ANN-IX-A", "ANNEXE IX-A"),
                    ("ANN-IX-B", "ANNEXE IX-B"),
                    ("TALLOL", "Tallol"),
                    ("OTHER", "Autre"),
                    ("EP2AM", "EP2AM"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="matierepremiere",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="matierepremiere",
            name="name_en",
            field=models.CharField(max_length=256),
        ),
    ]
