# Generated by Django 3.0.7 on 2020-07-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200708_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='data_origin_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_origin_entity', to='core.Entity'),
        ),
    ]
