# Generated by Django 5.2.2 on 2026-02-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_matierepremiere_classification_and_more"),
        ("transactions", "0017_update_site_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entitydepot",
            name="depot",
        ),
        migrations.RemoveField(
            model_name="entitydepot",
            name="blender",
        ),
        migrations.RemoveField(
            model_name="entitydepot",
            name="entity",
        ),
        migrations.AlterField(
            model_name="carburelot",
            name="carbure_delivery_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carbure_delivery_site",
                to="transactions.depot",
            ),
        ),
        migrations.AlterField(
            model_name="carburelot",
            name="carbure_dispatch_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carbure_dispatch_site",
                to="transactions.depot",
            ),
        ),
        migrations.AlterField(
            model_name="carburelot",
            name="carbure_production_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.productionsite",
            ),
        ),
        migrations.AlterField(
            model_name="carburestock",
            name="carbure_production_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_production_site",
                to="transactions.productionsite",
            ),
        ),
        migrations.AlterField(
            model_name="carburestock",
            name="depot",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="transactions.depot"
            ),
        ),
        migrations.DeleteModel(
            name="Depot",
        ),
        migrations.DeleteModel(
            name="EntityDepot",
        ),
    ]
