# Generated by Django 3.0.7 on 2020-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_lotv2_data_origin_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='is_in_europe',
            field=models.BooleanField(default=False),
        ),
    ]
