# Generated by Django 5.2.2 on 2026-03-10 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_genericcertificate_suspended_dates_and_more"),
        ("core", "0062_remove_entitydepot_depot_remove_entitydepot_blender_and_more"),
    ]

    operations = []
