# Generated by Django 5.2.2 on 2026-03-10 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_merge_20260310_1640"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericcertificate",
            name="suspended_dates",
        ),
    ]
