# Generated by Django 5.2.2 on 2026-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_declarationperiod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="declarationperiod",
            options={"verbose_name": "Période de déclaration", "verbose_name_plural": "Périodes de déclaration"},
        ),
        migrations.AddField(
            model_name="declarationperiod",
            name="app",
            field=models.CharField(
                choices=[("BIOMETHANE", "BIOMETHANE"), ("TIRUERT", "TIRUERT")], default="BIOMETHANE", max_length=20
            ),
        ),
        migrations.AlterModelTable(
            name="declarationperiod",
            table="declaration_periods",
        ),
    ]
