# Generated by Django 5.2.2 on 2026-03-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_remove_genericcertificate_suspended_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_region", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Région",
                "verbose_name_plural": "Régions",
                "db_table": "regions",
                "ordering": ["code_region"],
            },
        ),
        migrations.AlterField(
            model_name="department",
            name="code_dept",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name="department",
            name="region",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.region"),
        ),
    ]
