# Generated by Django 5.2.2 on 2026-02-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_alter_declarationperiod_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declarationperiod",
            name="year",
            field=models.IntegerField(),
        ),
    ]
