# Generated by Django 3.0.7 on 2020-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200805_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_col', models.CharField(blank=True, max_length=32, null=True)),
                ('condition', models.CharField(choices=[('EQ', 'Equals'), ('GT', 'Greater Than'), ('GTE', 'Greater Than or Equal'), ('LT', 'Less Than'), ('LTE', 'Less Than or Equal'), ('DIFF', 'Is Different than'), ('IN', 'Is In'), ('NIN', 'Is Not In')], default='EQ', max_length=64)),
                ('condition_value', models.CharField(blank=True, max_length=256, null=True)),
                ('check_col', models.CharField(blank=True, max_length=32, null=True)),
                ('check', models.CharField(choices=[('EQ', 'Equals'), ('GT', 'Greater Than'), ('GTE', 'Greater Than or Equal'), ('LT', 'Less Than'), ('LTE', 'Less Than or Equal'), ('DIFF', 'Is Different than'), ('IN', 'Is In'), ('NIN', 'Is Not In')], default='EQ', max_length=64)),
                ('check_value', models.CharField(blank=True, max_length=256, null=True)),
                ('warning_to_user', models.BooleanField(default=False)),
                ('warning_to_admin', models.BooleanField(default=False)),
                ('block_validation', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, default='', max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Règle Métier',
                'verbose_name_plural': 'Règles Métier',
                'db_table': 'check_rules',
            },
        ),
    ]
