# Generated by Django 3.0.7 on 2020-09-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20200902_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loterror',
            name='lot',
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={},
        ),
        migrations.DeleteModel(
            name='LotComment',
        ),
        migrations.DeleteModel(
            name='LotError',
        ),
    ]
