# Generated by Django 3.0.7 on 2020-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200902_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottransaction',
            name='is_mac',
            field=models.BooleanField(default=False),
        ),
    ]
