# Generated by Django 3.0.7 on 2020-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_lottransaction_is_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='depot_type',
            field=models.CharField(choices=[('EFS', 'EFS'), ('EFPE', 'EFPE'), ('OTHER', 'Autre')], default='OTHER', max_length=32),
        ),
    ]
