# Generated by Django 3.0.7 on 2020-09-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_depot_depot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='blocking_sanity_checked_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='nonblocking_sanity_checked_passed',
            field=models.BooleanField(default=False),
        ),
    ]
