# Generated by Django 5.2.2 on 2026-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_alter_declarationperiod_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaladminrights",
            name="right",
            field=models.CharField(
                choices=[
                    ("DCA", "DCA"),
                    ("AGRIMER", "AGRIMER"),
                    ("TIRIB", "TIRIB"),
                    ("AIRLINE", "AIRLINE"),
                    ("ELEC", "ELEC"),
                    ("TRANSFERRED_ELEC", "TRANSFERRED_ELEC"),
                    ("BIOFUEL", "BIOFUEL"),
                    ("DREAL", "DREAL"),
                    ("ADEME", "ADEME"),
                    ("DGDDI", "DGDDI"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
