# Generated by Django 5.2.2 on 2026-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_alter_externaladminrights_right"),
    ]

    operations = [
        migrations.AddField(
            model_name="matierepremiere",
            name="is_industrial_waste",
            field=models.BooleanField(default=False),
        ),
    ]
