# Generated by Django 3.0.7 on 2020-09-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_lotvalidationerror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotvalidationerror',
            name='rule',
        ),
        migrations.AddField(
            model_name='lotvalidationerror',
            name='block_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotvalidationerror',
            name='message',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lotvalidationerror',
            name='rule_triggered',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lotvalidationerror',
            name='warning_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotvalidationerror',
            name='warning_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
