# Generated by Django 5.2.2 on 2026-05-04 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_matierepremiere_is_industrial_waste"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Change collation for entire matieres_premieres table to case-insensitive, accent-insensitive
                "ALTER TABLE matieres_premieres CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;",
            ],
            reverse_sql=[
                # Revert to original collation if needed
                "ALTER TABLE matieres_premieres CONVERT TO CHARACTER SET latin1 COLLATE latin1_swedish_ci;",
            ],
        ),
    ]
