# Generated by Django 3.0.7 on 2020-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_lotvalidationerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottransaction',
            name='dae',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
