# Generated by Django 5.2.2 on 2026-06-22 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_change_feedstock_collation"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Change collation for entire entities table to case-insensitive, accent-insensitive
                "ALTER TABLE entities CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;",
            ],
            reverse_sql=[
                # Revert to original collation if needed
                "ALTER TABLE entities CONVERT TO CHARACTER SET latin1 COLLATE latin1_swedish_ci;",
            ],
        ),
    ]
