# Generated by Django 3.0.7 on 2020-09-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200916_1319'),
        ('core', '0072_auto_20200915_1355'),
    ]

    operations = [
    ]
