# Generated by Django 5.2.2 on 2026-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_change_entities_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matierepremiere",
            name="category",
            field=models.CharField(
                choices=[
                    ("CONV", "Conventionnel"),
                    ("ANN-IX-A", "ANNEXE IX-A"),
                    ("ANN-IX-B", "ANNEXE IX-B"),
                    ("TALLOL", "Tallol"),
                    ("OTHER", "Autre"),
                    ("EP2AM", "EP2AM"),
                    ("CAT3", "Graisses de catégorie 3"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
