# Generated by Django 3.0.7 on 2020-09-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_merge_20200916_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocarburant',
            name='is_alcool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biocarburant',
            name='is_graisse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='compatible_alcool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='compatible_graisse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lotvalidationerror',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
