# Generated by Django 5.2.2 on 2026-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_alter_matierepremiere_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericcertificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("SYSTEME_NATIONAL", "SYSTEME_NATIONAL"),
                    ("ISCC", "ISCC"),
                    ("REDCERT", "REDCERT"),
                    ("2BS", "2BS"),
                    ("KZR_INIG", "KZR_INIG"),
                    ("CERTIFHY", "CERTIFHY"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="genericcertificate",
            name="certificate_id",
            field=models.CharField(max_length=96),
        ),
    ]
