# Generated by Django 3.0.7 on 2020-09-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_lotvalidationerror_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='is_double_compte',
            field=models.BooleanField(default=False),
        ),
    ]
