# Generated by Django 5.2.2 on 2026-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_alter_genericcertificate_certificate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="carburelot",
            name="usage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROAD", "ROAD"),
                    ("HEATING", "HEATING"),
                    ("AGRICULTURE", "AGRICULTURE"),
                    ("CONSTRUCTION", "CONSTRUCTION"),
                    ("MARITIME", "MARITIME"),
                    ("INLAND_WATERWAY", "INLAND_WATERWAY"),
                    ("RAIL", "RAIL"),
                    ("FISHING", "FISHING"),
                    ("OTHER", "OTHER"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="carburelot",
            name="usage_precision",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="externaladminrights",
            name="right",
            field=models.CharField(
                choices=[
                    ("DCA", "DCA"),
                    ("AGRIMER", "AGRIMER"),
                    ("TIRIB", "TIRIB"),
                    ("AIRLINE", "AIRLINE"),
                    ("ELEC", "ELEC"),
                    ("TRANSFERRED_ELEC", "TRANSFERRED_ELEC"),
                    ("BIOFUEL", "BIOFUEL"),
                    ("DREAL", "DREAL"),
                    ("ADEME", "ADEME"),
                    ("DGDDI", "DGDDI"),
                    ("DGDDI_NATIONAL", "DGDDI_NATIONAL"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
