# Generated by Django 3.0.7 on 2020-09-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_matierepremiere_is_double_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
