# Generated by Django 5.2.2 on 2026-08-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_carburelot_usage_carburelot_usage_precision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("Producteur", "Producteur"),
                    ("Opérateur", "Opérateur"),
                    ("Administration", "Administration"),
                    ("Trader", "Trader"),
                    ("Auditor", "Auditeur"),
                    ("Administration Externe", "Administration Externe"),
                    ("Charge Point Operator", "Charge Point Operator"),
                    ("Compagnie aérienne", "Compagnie aérienne"),
                    ("Unknown", "Unknown"),
                    ("Power or Heat Producer", "Producteur d'électricité ou de chaleur"),
                    ("SAF Trader", "Trader de SAF"),
                    ("Producteur de biométhane", "Producteur de biométhane"),
                    ("Fournisseur de biométhane", "Fournisseur de biométhane"),
                    ("HRS", "Distributeur d'hydrogène pour la mobilité"),
                ],
                default="Unknown",
                max_length=64,
            ),
        ),
    ]
