# Generated by Django 5.2.2 on 2026-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericcertificate",
            name="scope",
            field=models.TextField(null=True),
        ),
    ]
