# Generated by Django 5.2.2 on 2026-08-24 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_alter_entity_entity_type"),
        ("core", "0078_alter_genericcertificate_scope"),
    ]

    operations = []
