# Generated by Django 3.0.7 on 2020-10-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20200924_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISCCCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=64)),
                ('certificate_holder', models.CharField(max_length=256)),
                ('addons', models.CharField(max_length=256)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('issuing_cb', models.CharField(default='', max_length=256)),
                ('location', models.CharField(default='', max_length=256)),
            ],
            options={
                'verbose_name': 'ISCC Certificate',
                'verbose_name_plural': 'ISCC Certificates',
                'db_table': 'iscc_certificates',
            },
        ),
        migrations.CreateModel(
            name='ISCCScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'ISCC Scope',
                'verbose_name_plural': 'ISCC Scopes',
                'db_table': 'iscc_scopes',
            },
        ),
        migrations.CreateModel(
            name='ISCCCertificateScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ISCCCertificate')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ISCCScope')),
            ],
            options={
                'verbose_name': 'ISCC Certificate Scope',
                'verbose_name_plural': 'ISCC Certificate Scopes',
                'db_table': 'iscc_certificates_scopes',
            },
        ),
        migrations.CreateModel(
            name='ISCCCertificateRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material', models.CharField(max_length=32)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ISCCCertificate')),
            ],
            options={
                'verbose_name': 'ISCC Certificate Raw Material',
                'verbose_name_plural': 'ISCC Certificate Raw Materials',
                'db_table': 'iscc_certificates_raw_materials',
            },
        ),
    ]
