# Generated by Django 5.2.2 on 2026-08-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_merge_20260824_1605"),
    ]

    operations = [
        migrations.AddField(
            model_name="biocarburant",
            name="compatible_gpl",
            field=models.BooleanField(default=False),
        ),
    ]
