# Generated by Django 5.2.2 on 2026-08-24 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_alter_externaladminrights_right"),
        ("core", "0079_merge_20260824_1605"),
    ]

    operations = []
