# Generated by Django 3.0.7 on 2020-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20201007_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBSCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=64)),
                ('certificate_holder', models.CharField(max_length=256)),
                ('holder_address', models.CharField(max_length=256)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('certification_type', models.CharField(default='', max_length=256)),
            ],
            options={
                'verbose_name': '2BS Certificate',
                'verbose_name_plural': '2BS Certificates',
                'db_table': 'dbs_certificates',
            },
        ),
    ]
