# Generated by Django 5.2.2 on 2026-09-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_merge_20260824_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biocarburant",
            name="description",
            field=models.CharField(max_length=320),
        ),
    ]
