# Generated by Django 5.2.2 on 2026-09-09 10:33

from django.db import connection, migrations


def sql_result(request):
    with connection.cursor() as cursor:
        cursor.execute(request)
        result = cursor.fetchall()

    return result


def remove_check_clauses_validating_json_format(_apps, _schema_editor):
    q = (
        "select tc.table_name, cc.constraint_name from information_schema.check_constraints as cc "
        "join information_schema.table_constraints as tc "
        "on tc.constraint_schema = cc.constraint_schema and tc.constraint_name = cc.constraint_name "
        "where cc.constraint_schema = database() and cc.check_clause like 'json_valid%'"
    )
    tables_and_constraints = sql_result(q)
    for t, c in tables_and_constraints:
        sql_result(f"alter table {t} drop constraint {c}")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_merge_20260824_1747"),
    ]

    operations = [
        migrations.RunPython(remove_check_clauses_validating_json_format, migrations.RunPython.noop),
    ]
