# Generated by Django 5.2.2 on 2026-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_merge_20260824_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matierepremiere",
            name="code",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
