# Generated by Django 5.2.2 on 2026-09-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_merge_20260824_1747"),
        ("transactions", "0021_alter_site_site_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carburelot",
            name="carbure_dispatch_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatched_biofuel_lots",
                to="transactions.site",
            ),
        ),
    ]
