# Generated by Django 3.0.7 on 2020-10-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_dbscertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityISCCTradingCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ISCCCertificate')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Certificat de Trading ISCC',
                'verbose_name_plural': 'Certificats de Trading ISCC',
                'db_table': 'entity_iscc_trading_certificates',
            },
        ),
        migrations.CreateModel(
            name='EntityDBSTradingCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DBSCertificate')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Certificat de Trading 2BS',
                'verbose_name_plural': 'Certificats de Trading 2BS',
                'db_table': 'entity_2bs_trading_certificates',
            },
        ),
    ]
