# Generated by Django 5.2.2 on 2026-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_biocarburant_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="biocarburant",
            name="compatible_gpl",
            field=models.BooleanField(default=False),
        ),
    ]
