# Generated by Django 5.2.2 on 2026-09-10 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_biocarburant_description"),
        ("core", "0081_remove_json_check_constraint_on_carbure_certificates"),
    ]

    operations = []
