# Generated by Django 5.2.2 on 2026-09-10 12:54

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models

import core.models.file


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_remove_json_check_constraint_on_carbure_certificates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.FileField(
                        max_length=255,
                        storage=storages.backends.s3.S3Storage(
                            default_acl="private", file_overwrite=True, querystring_auth=True
                        ),
                        upload_to=core.models.file.stored_file_upload_to,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="stored_files", to="core.entity"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="stored_files", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier",
                "verbose_name_plural": "Fichiers",
                "db_table": "file",
                "ordering": ["-created_at"],
            },
        ),
    ]
