# Generated by Django 3.0.7 on 2020-10-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_entitydbstradingcertificate_entityiscctradingcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='has_mac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='has_trading',
            field=models.BooleanField(default=False),
        ),
    ]
