# Generated by Django 5.2.2 on 2026-09-10 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_matierepremiere_code"),
        ("core", "0082_merge_20260910_1458"),
    ]

    operations = []
