# Generated by Django 5.2.2 on 2026-09-10 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_biocarburant_compatible_gpl"),
        ("core", "0083_merge_20260910_1626"),
    ]

    operations = []
