# Generated by Django 5.2.2 on 2026-09-16 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_storedfile"),
        ("core", "0084_merge_20260910_1745"),
    ]

    operations = []
