# Generated by Django 3.0.7 on 2020-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_lottransaction_is_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBSScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_type', models.CharField(default='', max_length=512)),
            ],
            options={
                'verbose_name': '2BS Scope',
                'verbose_name_plural': '2BS Scopes',
                'db_table': 'dbs_scopes',
            },
        ),
        migrations.AlterField(
            model_name='dbscertificate',
            name='certification_type',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='dbscertificate',
            name='holder_address',
            field=models.CharField(max_length=512),
        ),
    ]
