# Generated by Django 5.2.2 on 2026-09-16 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_rename_carburelot_usage_heating_to_combustible"),
        ("core", "0084_merge_20260910_1745"),
    ]

    operations = []
