# Generated by Django 5.2.2 on 2026-09-22 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_merge_0082_storedfile_0084_merge_20260910_1745"),
        ("core", "0085_merge_20260916_1334"),
    ]

    operations = []
