# Generated by Django 5.2.2 on 2026-09-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_merge_20260916_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="biocarburant",
            name="compatible_maritime",
            field=models.BooleanField(default=False),
        ),
    ]
