# Generated by Django 5.2.2 on 2026-09-23 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_biocarburant_compatible_maritime"),
        ("core", "0086_merge_20260922_1549"),
    ]

    operations = []
