# Generated by Django 3.0.7 on 2020-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_dbscertificatescope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotv2error',
            name='field',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='transactionerror',
            name='field',
            field=models.CharField(max_length=64),
        ),
    ]
