# Generated by Django 5.2.2 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_merge_20260923_1103"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="has_biogpl",
            field=models.BooleanField(default=False),
        ),
    ]
