# Generated by Django 3.0.7 on 2020-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20201109_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='is_huile_vegetale',
            field=models.BooleanField(default=False),
        ),
    ]
