# Generated by Django 5.2.2 on 2026-09-30 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_carburelot_carbure_dispatch_site"),
        ("core", "0088_alter_externaladminrights_right"),
    ]

    operations = []
