# Generated by Django 3.0.7 on 2020-11-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0020_auto_20201118_1222'),
        ('core', '0088_matierepremiere_is_huile_vegetale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSiteCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ISCC', 'ISCC'), ('2BS', '2BS')], default='Pending', max_length=32)),
                ('certificate_2bs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EntityDBSTradingCertificate')),
                ('certificate_iscc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EntityISCCTradingCertificate')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
                ('production_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producers.ProductionSite')),
            ],
            options={
                'verbose_name': 'Certificat de site de production',
                'verbose_name_plural': 'Certificats de sites de productions',
                'db_table': 'production_sites_certificates',
            },
        ),
    ]
