# Generated by Django 3.0.7 on 2020-11-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_matierepremiere_is_huile_vegetale'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='address',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depot',
            name='ownership_type',
            field=models.CharField(choices=[('OWN', 'Propre'), ('THIRD_PARTY', 'Tiers')], default='THIRD_PARTY', max_length=32),
        ),
        migrations.AddField(
            model_name='depot',
            name='postal_code',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
