# Generated by Django 3.0.7 on 2020-11-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20201118_1234'),
        ('core', '0089_productionsitecertificate'),
    ]

    operations = [
    ]
