# Generated by Django 3.0.7 on 2020-11-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_merge_20201118_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='national_system_certificate',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
