# Generated by Django 3.0.7 on 2020-11-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20201120_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitydbstradingcertificate',
            name='has_been_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entityiscctradingcertificate',
            name='has_been_updated',
            field=models.BooleanField(default=False),
        ),
    ]
