# Generated by Django 3.0.7 on 2020-12-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20201202_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDepot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('OWN', 'Propre'), ('THIRD_PARTY', 'Tiers')], default='THIRD_PARTY', max_length=32)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Depot')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Dépôt Entité',
                'verbose_name_plural': 'Dépôts Entité',
                'db_table': 'entity_depot',
            },
        ),
        migrations.DeleteModel(
            name='OperatorDepot',
        ),
    ]
