# Generated by Django 3.0.7 on 2021-01-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_auto_20210118_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': ' Déclaration de Durabilité',
                'verbose_name_plural': ' Déclarations de Durabilité',
                'db_table': 'declarations',
            },
        ),
    ]
