# Generated by Django 3.0.7 on 2021-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_sustainabilitydeclaration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lotv2',
            index=models.Index(fields=['added_by'], name='lots_v2_added_b_a00961_idx'),
        ),
    ]
