# Generated by Django 3.0.7 on 2021-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20210125_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabilitydeclaration',
            name='declared',
            field=models.BooleanField(default=False),
        ),
    ]
