# Generated by Django 3.0.7 on 2021-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_controlmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='category',
            field=models.CharField(choices=[('CONV', 'Conventionnel'), ('ANN-IX-A', 'ANNEXE IX-A'), ('ANN-IX-B', 'ANNEXE IX-B'), ('OTHER', 'Autre')], default='CONV', max_length=32),
        ),
    ]
