# Generated by Django 3.0.7 on 2021-02-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20210210_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotvalidationerror',
            name='acked_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotvalidationerror',
            name='highlighted_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
