# Generated by Django 3.0.7 on 2021-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_sustainabilitydeclaration_reminder_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='entity',
            name='registered_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entity',
            name='registration_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sustainability_officer',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sustainability_officer_phone_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
