# Generated by Django 3.0.7 on 2021-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20210219_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottransaction',
            name='champ_libre',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
