# Generated by Django 3.0.7 on 2021-02-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_lotvalidationerror_warning_to_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotv2',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
