# Generated by Django 3.0.7 on 2021-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20210226_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottransaction',
            name='vendor_certificate',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
