# Generated by Django 3.0.7 on 2021-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_lottransaction_vendor_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='is_transformed',
            field=models.BooleanField(default=False),
        ),
    ]
