# Generated by Django 3.0.7 on 2021-03-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_lotv2_is_transformed'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitydepot',
            name='blender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blender', to='core.Entity'),
        ),
        migrations.AddField(
            model_name='entitydepot',
            name='blending_is_outsourced',
            field=models.BooleanField(default=False),
        ),
    ]
