# Generated by Django 3.0.7 on 2021-03-04 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0117_auto_20210303_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETBETransformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ethanol', models.FloatField(default=0.0)),
                ('volume_etbe', models.FloatField(default=0.0)),
                ('volume_denaturant', models.FloatField(default=0.0)),
                ('volume_fossile', models.FloatField(default=0.0)),
                ('volume_pertes', models.FloatField(default=0.0)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Entity')),
                ('added_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_stock', to='core.LotTransaction')),
                ('previous_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_stock', to='core.LotTransaction')),
            ],
            options={
                'verbose_name': 'Transformation ETBE',
                'verbose_name_plural': 'Transformations ETBE',
                'db_table': 'etbe_transformations',
            },
        ),
    ]
