# Generated by Django 3.0.7 on 2021-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_etbetransformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='carbure_production_site_reference',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='unknown_vendor',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='unknown_vendor_certificate',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
