# Generated by Django 3.0.7 on 2021-03-17 16:25

from django.db import migrations

def transfer_unknown_vendor(apps, schema_editor):
    LotTransaction = apps.get_model('core', 'LotTransaction')

    for t in LotTransaction.objects.exclude(unknown_vendor=''):
        t.lot.unknown_vendor = t.unknown_vendor
        t.lot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20210317_1725'),
    ]

    operations = [
        migrations.RunPython(transfer_unknown_vendor),
    ]
