# Generated by Django 3.0.7 on 2021-03-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20210317_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottransaction',
            old_name='vendor_certificate',
            new_name='carbure_vendor_certificate',
        ),
        migrations.RemoveField(
            model_name='lottransaction',
            name='unknown_vendor',
        ),
        migrations.RemoveField(
            model_name='lottransaction',
            name='vendor_is_in_carbure',
        ),
    ]
