# Generated by Django 3.0.7 on 2021-03-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20210317_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotv2',
            old_name='unknown_vendor',
            new_name='unknown_supplier',
        ),
        migrations.RenameField(
            model_name='lotv2',
            old_name='unknown_vendor_certificate',
            new_name='unknown_supplier_certificate',
        ),
    ]
