# Generated by Django 3.0.7 on 2021-03-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20210317_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='REDCertBiomassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('description_fr', models.CharField(max_length=256)),
                ('description_en', models.CharField(max_length=256)),
                ('description_de', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'REDCert Biomass Type',
                'verbose_name_plural': 'REDCert Biomass Types',
                'db_table': 'redcert_biomass_types',
            },
        ),
        migrations.CreateModel(
            name='REDCertCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=64)),
                ('certificate_holder', models.CharField(max_length=256)),
                ('city', models.CharField(default='', max_length=256)),
                ('zip_code', models.CharField(default='', max_length=12)),
                ('country_raw', models.CharField(default='', max_length=32)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('certificator', models.CharField(default='', max_length=256)),
                ('certificate_type', models.CharField(default='', max_length=256)),
                ('status', models.CharField(default='', max_length=32)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pays')),
            ],
            options={
                'verbose_name': 'REDCert Certificate',
                'verbose_name_plural': 'REDCert Certificates',
                'db_table': 'redcert_certificates',
            },
        ),
        migrations.CreateModel(
            name='REDCertScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=8)),
                ('description_fr', models.CharField(max_length=256)),
                ('description_en', models.CharField(max_length=256)),
                ('description_de', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'REDCert Scope',
                'verbose_name_plural': 'REDCert Scopes',
                'db_table': 'redcert_scopes',
            },
        ),
        migrations.AlterField(
            model_name='productionsitecertificate',
            name='type',
            field=models.CharField(choices=[('ISCC', 'ISCC'), ('2BS', '2BS'), ('REDCERT', 'REDCERT')], default='Pending', max_length=32),
        ),
        migrations.CreateModel(
            name='REDCertCertificateScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.REDCertCertificate')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.REDCertScope')),
            ],
            options={
                'verbose_name': 'REDCert Certificate Scope',
                'verbose_name_plural': 'REDCert Certificate Scopes',
                'db_table': 'redcert_certificates_scopes',
            },
        ),
        migrations.CreateModel(
            name='EntityREDCertTradingCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_updated', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.REDCertCertificate')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Certificat de Trading REDCert',
                'verbose_name_plural': 'Certificats de Trading REDCert',
                'db_table': 'entity_redcert_trading_certificates',
            },
        ),
        migrations.AddField(
            model_name='productionsitecertificate',
            name='certificate_redcert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EntityREDCertTradingCertificate'),
        ),
    ]
