# Generated by Django 3.0.7 on 2021-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20210319_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redcertbiomasstype',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
