# Generated by Django 3.0.7 on 2021-03-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20210319_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='REDCertCertificateBiomass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biomass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.REDCertBiomassType')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.REDCertCertificate')),
            ],
            options={
                'verbose_name': 'REDCert Certificate Biomass',
                'verbose_name_plural': 'REDCert Certificate Biomass',
                'db_table': 'redcert_certificates_biomass',
            },
        ),
    ]
