# Generated by Django 3.0.7 on 2021-03-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_auto_20210323_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydepot',
            name='ownership_type',
            field=models.CharField(choices=[('OWN', 'Propre'), ('THIRD_PARTY', 'Tiers'), ('PROCESSING', 'Processing')], default='THIRD_PARTY', max_length=32),
        ),
    ]
