# Generated by Django 3.2 on 2021-04-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('core', '0127_auto_20210324_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsitecertificate',
            name='certificate_sn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.entitysntradingcertificate'),
        ),
        migrations.AlterField(
            model_name='productionsitecertificate',
            name='type',
            field=models.CharField(choices=[('ISCC', 'ISCC'), ('2BS', '2BS'), ('REDCERT', 'REDCERT'), ('SN', 'SN')], default='Pending', max_length=32),
        ),
    ]
