# Generated by Django 3.2 on 2021-04-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_auto_20210419_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='national_system_certificate',
        ),
    ]
