# Generated by Django 3.2 on 2021-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_remove_entity_national_system_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottransaction',
            name='generated_by_carbure',
            field=models.BooleanField(default=False),
        ),
    ]
