# Generated by Django 3.2 on 2021-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_lottransaction_generated_by_carbure'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='remaining_volume',
            field=models.FloatField(default=0.0),
        ),
    ]
