# Generated by Django 3.2 on 2021-04-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_auto_20210428_1439'),
        ('core', '0131_lotv2_remaining_volume'),
    ]

    operations = [
    ]
