# Generated by Django 3.2 on 2021-04-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20210428_1439'),
    ]

    operations = [
    ]
