# Generated by Django 3.2 on 2021-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_auto_20210429_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etbetransformation',
            name='volume_fossile',
        ),
        migrations.RemoveField(
            model_name='etbetransformation',
            name='volume_pertes',
        ),
        migrations.AddField(
            model_name='etbetransformation',
            name='volume_etbe_eligible',
            field=models.FloatField(default=0.0),
        ),
    ]
