# Generated by Django 3.2 on 2021-04-30 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20210429_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottransaction',
            name='parent_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lottransaction'),
        ),
    ]
