# Generated by Django 3.2 on 2021-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_lottransaction_parent_tx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrights',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrights',
            name='role',
            field=models.CharField(choices=[('RO', 'Lecture Seule'), ('RW', 'Lecture/Écriture'), ('ADMIN', 'Administrateur'), ('AUDITOR', 'Auditeur')], default='RO', max_length=32),
        ),
        migrations.AddField(
            model_name='userrightsrequests',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrightsrequests',
            name='role',
            field=models.CharField(choices=[('RO', 'Lecture Seule'), ('RW', 'Lecture/Écriture'), ('ADMIN', 'Administrateur'), ('AUDITOR', 'Auditeur')], default='RO', max_length=32),
        ),
    ]
