# Generated by Django 3.2 on 2021-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_alter_matierepremiere_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottransaction',
            name='is_stock',
            field=models.BooleanField(default=False),
        ),
    ]
