# Generated by Django 3.2 on 2021-05-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_lottransaction_is_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_to_creator', models.BooleanField(default=False)),
                ('display_to_recipient', models.BooleanField(default=False)),
                ('display_to_admin', models.BooleanField(default=False)),
                ('display_to_auditor', models.BooleanField(default=False)),
                ('acked_by_creator', models.BooleanField(default=False)),
                ('acked_by_recipient', models.BooleanField(default=False)),
                ('acked_by_admin', models.BooleanField(default=False)),
                ('acked_by_auditor', models.BooleanField(default=False)),
                ('highlighted_by_admin', models.BooleanField(default=False)),
                ('highlighted_by_auditor', models.BooleanField(default=False)),
                ('is_blocking', models.BooleanField(default=False)),
                ('field', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('error', models.CharField(max_length=256)),
                ('extra', models.CharField(max_length=256)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lotv2')),
                ('tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lottransaction')),
            ],
            options={
                'verbose_name': 'Generic Error',
                'verbose_name_plural': 'Generic Errors',
                'db_table': 'generic_errors',
            },
        ),
    ]
