# Generated by Django 3.2 on 2021-05-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_genericerror'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckRule',
        ),
        migrations.DeleteModel(
            name='GHGValues',
        ),
    ]
