# Generated by Django 3.2 on 2021-05-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_auto_20210510_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottransaction',
            name='delivery_status',
            field=models.CharField(choices=[('N', 'En Attente'), ('A', 'Accepté'), ('R', 'Refusé'), ('AC', 'À corriger'), ('AA', 'Corrigé'), ('F', 'Déclaré')], default='N', max_length=64),
        ),
        migrations.AlterField(
            model_name='lotv2',
            name='status',
            field=models.CharField(choices=[('Draft', 'Brouillon'), ('Validated', 'Validé'), ('Declared', 'Déclaré')], default='Draft', max_length=64),
        ),
    ]
