# Generated by Django 3.2 on 2021-05-14 14:43

from django.db import migrations, models
import django.db.models.deletion

def transfer_errors(apps, schema_editor):
    GenericError = apps.get_model("core", "GenericError")    
    LotV2Error = apps.get_model("core", "LotV2Error")
    TransactionError = apps.get_model("core", "TransactionError")
    LotValidationError = apps.get_model("core", "LotValidationError")    
    db_alias = schema_editor.connection.alias

    le = LotValidationError.objects.using(db_alias).all()
    for e in le:
        d = {}
        if e.block_validation:
            d['is_blocking'] = True
        d['extra'] = e.message
        print('Migrating LotValidationError id %d to GenericError...' % (e.id))
        if not e.tx:
            continue
        GenericError.objects.update_or_create(tx=e.tx, error=e.rule_triggered, defaults=d)
    LotV2Error.objects.using(db_alias).all().delete()
    TransactionError.objects.using(db_alias).all().delete()
    LotValidationError.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_alter_entity_sustainability_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericerror',
            name='lot',
        ),
        migrations.AlterField(
            model_name='genericerror',
            name='extra',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='genericerror',
            name='field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='genericerror',
            name='tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lottransaction'),
        ),
        migrations.RunPython(transfer_errors),
    ]
