# Generated by Django 3.2 on 2021-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20210514_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericerror',
            name='fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
