# Generated by Django 3.2 on 2021-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20210520_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotv2',
            name='status',
            field=models.CharField(choices=[('Draft', 'Brouillon'), ('Validated', 'Validé')], default='Draft', max_length=64),
        ),
    ]
