# Generated by Django 3.2 on 2021-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_transactionupdatehistory_modified_by_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericerror',
            name='fields',
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Producteur', 'Producteur'), ('Opérateur', 'Opérateur'), ('Administration', 'Administration'), ('Trader', 'Trader'), ('Auditor', 'Auditeur'), ('Unknown', 'Unknown')], default='Unknown', max_length=64),
        ),
    ]
