# Generated by Django 3.2 on 2021-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20210526_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericerror',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
