# Generated by Django 3.2 on 2021-05-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_auto_20210527_1708'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lottransaction',
            index=models.Index(fields=['unknown_client'], name='transaction_unknown_711932_idx'),
        ),
        migrations.AddIndex(
            model_name='lottransaction',
            index=models.Index(fields=['is_forwarded'], name='transaction_is_forw_1ca55a_idx'),
        ),
        migrations.AddIndex(
            model_name='lottransaction',
            index=models.Index(fields=['is_mac'], name='transaction_is_mac_84515f_idx'),
        ),
        migrations.AddIndex(
            model_name='lottransaction',
            index=models.Index(fields=['carbure_delivery_site'], name='transaction_carbure_fead82_idx'),
        ),
        migrations.AddIndex(
            model_name='lottransaction',
            index=models.Index(fields=['unknown_delivery_site'], name='transaction_unknown_05604b_idx'),
        ),
        migrations.AddIndex(
            model_name='lotv2',
            index=models.Index(fields=['biocarburant'], name='lots_v2_biocarb_9ff256_idx'),
        ),
        migrations.AddIndex(
            model_name='lotv2',
            index=models.Index(fields=['matiere_premiere'], name='lots_v2_matiere_030cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='lotv2',
            index=models.Index(fields=['pays_origine'], name='lots_v2_pays_or_0ac02b_idx'),
        ),
        migrations.AddIndex(
            model_name='lotv2',
            index=models.Index(fields=['carbure_production_site'], name='lots_v2_carbure_6595be_idx'),
        ),
        migrations.AddIndex(
            model_name='lotv2',
            index=models.Index(fields=['unknown_production_site'], name='lots_v2_unknown_14a9ed_idx'),
        ),
    ]
