# Generated by Django 3.2 on 2021-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_auto_20210528_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottransaction',
            name='champ_libre',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
