# Generated by Django 3.2 on 2021-05-31 18:39

from django.db import migrations, models
import hashlib

def update_entity_hash(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Entity = apps.get_model('core', 'Entity')
    for entity in Entity.objects.all():
        data = entity.name + entity.entity_type + entity.date_added.strftime('%Y%m%d')
        hash = hashlib.md5(data.encode('utf-8')).hexdigest()
        entity.hash = hash
        entity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20210531_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.RunPython(update_entity_hash),        
    ]
