# Generated by Django 3.2 on 2021-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_entity_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='trading_certificate',
        ),
        migrations.AddField(
            model_name='entity',
            name='default_certificate',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
