# Generated by Django 3.2 on 2021-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20210601_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='hidden_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='hidden_by_auditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='highlighted_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='highlighted_by_auditor',
            field=models.BooleanField(default=False),
        ),
    ]
