# Generated by Django 3.2 on 2021-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_auto_20210602_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotv2',
            name='hidden_by_admin',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='hidden_by_auditor',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='highlighted_by_admin',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='highlighted_by_auditor',
        ),
        migrations.AddField(
            model_name='lottransaction',
            name='hidden_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lottransaction',
            name='hidden_by_auditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lottransaction',
            name='highlighted_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lottransaction',
            name='highlighted_by_auditor',
            field=models.BooleanField(default=False),
        ),
    ]
