# Generated by Django 3.2 on 2021-06-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_auto_20210602_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('notif_type', models.CharField(choices=[('CORRECTION_REQUEST', 'CORRECTION_REQUEST'), ('CORRECTION_DONE', 'CORRECTION_DONE'), ('LOT_CHANGED', 'LOT_CHANGED'), ('LOT_REJECTED', 'LOT_REJECTED'), ('LOT_PENDING', 'LOT_PENDING'), ('DEADLINE_APPROACHING', 'DEADLINE_APPROACHING'), ('DOCUMENTATION_REQUESTED', 'DOCUMENTATION_REQUESTED')], default='', max_length=32)),
                ('sent', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
                ('linked_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lottransaction')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'db_table': 'email_notifications',
            },
        ),
    ]
