# Generated by Django 3.2 on 2021-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_emailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocarburant',
            name='compatible_diesel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biocarburant',
            name='compatible_essence',
            field=models.BooleanField(default=False),
        ),
    ]
