# Generated by Django 3.2 on 2021-06-17 15:36

from django.db import migrations, models

def update_lot_year(apps, schema_editor):
    LotV2 = apps.get_model('core', 'LotV2')
    for lot in LotV2.objects.all():
        if lot.period:
            lot.year = int(lot.period[0:4])
            lot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_auto_20210609_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(update_lot_year),
    ]
