# Generated by Django 3.2 on 2021-06-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_lotv2_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottransaction',
            name='delivery_status',
            field=models.CharField(choices=[('N', 'En attente'), ('A', 'Accepté'), ('R', 'Refusé'), ('AC', 'À corriger'), ('AA', 'Corrigé'), ('F', 'Déclaré')], default='N', max_length=64),
        ),
    ]
