# Generated by Django 3.2 on 2021-06-22 12:28

from django.db import migrations, models


def save_bc_english_names(apps, schema_editor):
    biofuels = {
        'B100': 'B100',
        'BG': 'Biogas',
        'BGS': 'Synthetic biodiesel (non HVO)',
        'BT': 'Butanol',
        'ED95': 'ED95\'s ethanol',
        'EMAG': 'FAME',
        'EMHA': 'AFME',
        'EMHU': 'UCOME',
        'EMHV': 'VOME',
        'ETBE': 'ETBE',
        'ETH': 'Ethanol',
        'HCU': 'UCO Oil',
        'HOC': 'Hydrotreated oil - Jet',
        'HOE': 'Hydrotreated oil - Gasoline',
        'HOG': 'Hydrotreated oil - Diesel',
        'HVOC': 'Hydrotreated vegetable oil - Jet',
        'HVOE': 'Hydrotreated vegetable oil - Gasoline',
        'HVOG': 'Hydrotreated vegetable oil - Diesel',
        'HVP': 'Pure vegetable oil',
        'MT': 'Methanol',
        'MTBE': 'MTBE',
        'TAEE': 'TAEE'
    }

    Biocarburant = apps.get_model('core', 'Biocarburant')
    for bc in Biocarburant.objects.all():
        bc.name_en = biofuels[bc.code]
        bc.save()


def save_mp_english_names(apps, schema_editor):
    feedstocks = {
        'ALGUES': 'Algae',
        'AMIDON_RESIDUEL': 'Starch slury',
        'BAGASSE': 'Bagasse',
        'BALLES': 'Husks',
        'BETTERAVE': 'Beet',
        'BLE': 'Wheat',
        'BOUES_EPURATION': 'Sewage Sludge',
        'BRAI_TALLOL': 'Tall oil pitch',
        'CANNE_A_SUCRE': 'Sugar cane',
        'COLZA': 'Rapeseed',
        'COQUES': 'Nut shells',
        'DECHETS_BOIS': 'Wood waste',
        'DECHETS_INDUSTRIELS': 'Industrial waste',
        'DECHETS_MUNICIPAUX_MELANGE': 'Municipal wast',
        'DECHETS_ORGANIQUES_MENAGERS': 'Households biowaste',
        'EFFLUENTS_HUILERIES_PALME_RAFLE': 'Palm oil mill efluent',
        'EP2': 'Molasses',
        'FUMIER_HUMIDE': 'Manure',
        'FUMIER_SEC': 'Dry manure',
        'GLYCERINE_BRUTE': 'Crude glycerine',
        'HUILES_OU_GRAISSES_ANIMALES_CAT1_CAT2': 'CI/CII Animal fat',
        'HUILES_OU_GRAISSES_ANIMALES_CAT3': 'CIII Animal fat',
        'HUILE_ALIMENTAIRE_USAGEE': 'used cooking oil',
        'HUILE_PALME': 'Palm oil',
        'LIES_DE_VIN': 'Wine lies',
        'MAIS': 'Corn',
        'MARC_DE_RAISIN': 'Grape marcs',
        'MAT_CELLULOSIQUE_NON_ALIMENTAIRE': 'Non-food cellulosic material',
        'MAT_LIGNO_CELLULOSIQUE': 'Ligno-cellulosic material',
        'ORGE': 'Barley',
        'PAILLE': 'Straw',
        'RAPES': 'Cobs',
        'RESIDUS_DE_BIERE': 'Beer sludge',
        'RESIDUS_VINIQUES': 'Wine sludge',
        'SEIGLE': 'Rye',
        'SOJA': 'Soy',
        'TALLOL': 'Tall oil',
        'TOURNESOL': 'Sunflower',
        'TRITICALE': 'Triticale'
    }

    MatierePremiere = apps.get_model('core', 'MatierePremiere')
    for mp in MatierePremiere.objects.all():
        mp.name_en = feedstocks[mp.code]
        mp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_alter_lottransaction_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocarburant',
            name='name_en',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='name_en',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(save_bc_english_names),
        migrations.RunPython(save_mp_english_names),
    ]
