# Generated by Django 3.2 on 2021-06-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_alter_lottransaction_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocarburant',
            name='name_en',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='name_en',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
