# Generated by Django 3.2 on 2021-06-22 12:28

from django.db import migrations, models
import json


def save_bc_english_names(apps, schema_editor):
    biofuels_json = open('front/public/locales/en/biofuels.json', 'r')
    biofuels = json.load(biofuels_json)

    Biocarburant = apps.get_model('core', 'Biocarburant')

    for bc in Biocarburant.objects.all():
        bc.name_en = biofuels[bc.code]
        bc.save()


def save_mp_english_names(apps, schema_editor):
    feedstocks_json = open('front/public/locales/en/feedstocks.json', 'r')
    feedstocks = json.load(feedstocks_json)

    MatierePremiere = apps.get_model('core', 'MatierePremiere')

    for mp in MatierePremiere.objects.all():
        mp.name_en = feedstocks[mp.code]
        mp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_alter_lottransaction_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocarburant',
            name='name_en',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='name_en',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(save_bc_english_names),
        migrations.RunPython(save_mp_english_names),
    ]
