# Generated by Django 3.2.4 on 2021-06-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_auto_20210622_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='send_copy_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notif_type',
            field=models.CharField(choices=[('CORRECTION_REQUEST', 'CORRECTION_REQUEST'), ('CORRECTION_DONE', 'CORRECTION_DONE'), ('LOT_CHANGED', 'LOT_CHANGED'), ('LOT_REJECTED', 'LOT_REJECTED'), ('LOT_PENDING', 'LOT_PENDING'), ('DEADLINE_APPROACHING', 'DEADLINE_APPROACHING'), ('DOCUMENTATION_REQUESTED', 'DOCUMENTATION_REQUESTED'), ('DECLARATION_INVALIDATED', 'DECLARATION_INVALIDATED'), ('DECLARATION_VALIDATED', 'DECLARATION_VALIDATED')], default='', max_length=32),
        ),
    ]
