# Generated by Django 3.2.4 on 2021-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_depot_gps_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('delivery_point', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('distance', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Distance',
                'verbose_name_plural': 'Distances',
                'db_table': 'transaction_distances',
            },
        ),
    ]
