# Generated by Django 3.2.4 on 2021-06-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_transactiondistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
