# Generated by Django 3.2 on 2021-07-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_entity_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BIOFUEL_DELIVERY', 'BIOFUEL_DELIVERY'), ('MAC', 'MAC'), ('DIRECT_DELIVERY', 'DIRECT_DELIVERY')], default='BIOFUEL_DELIVERY', max_length=32),
        ),
    ]
