# Generated by Django 3.2 on 2021-07-02 14:22

from django.db import migrations
import datetime
from core.common import calculate_ghg

def recalc_ges_red2(apps, schema_editor):
    LotTransaction = apps.get_model('core', 'LotTransaction')
    july = datetime.date(year=2021, month=7, day=1)
    txs = LotTransaction.objects.filter(delivery_date__gte=july)
    
    for tx in txs:
        calculate_ghg(tx.lot, tx)
        tx.lot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_lottransaction_transaction_type'),
    ]

    operations = [
        migrations.RunPython(recalc_ges_red2),        
    ]
