# Generated by Django 3.2.4 on 2021-07-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_auto_20210702_1622'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lotv2',
            index=models.Index(fields=['year'], name='lots_v2_year_87d135_idx'),
        ),
    ]
