# Generated by Django 3.2.4 on 2021-07-26 11:38
import hashlib
from django.db import migrations

def update_entity_hash(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Entity = apps.get_model('core', 'Entity')
    for entity in Entity.objects.all():
        if entity.hash:
            continue
        data = entity.name + entity.entity_type + entity.date_added.strftime('%Y%m%d')
        hash = hashlib.md5(data.encode('utf-8')).hexdigest()
        entity.hash = hash
        entity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_lotv2_lots_v2_year_87d135_idx'),
    ]

    operations = [
        migrations.RunPython(update_entity_hash),        
    ]
