# Generated by Django 3.2.4 on 2021-07-27 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20210726_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTransactionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lottransaction')),
            ],
            options={
                'verbose_name': 'AdminTransactionComment',
                'verbose_name_plural': 'AdminTransactionComments',
                'db_table': 'admin_tx_comments',
            },
        ),
    ]
