# Generated by Django 3.2.4 on 2021-07-27 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_admintransactioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransactioncomment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
