# Generated by Django 3.2.4 on 2021-08-10 12:07

from django.db import migrations
from django.db.models import F, Q

def update_stocks(apps, schema_editor):
    LotV2 = apps.get_model('core', 'LotV2')
    lots = LotV2.objects.filter(year=2021).filter(Q(remaining_volume__lt=F('volume')))
    for lot in lots:
        lot.remaining_volume = round(lot.remaining_volume, 2)
        lot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_admintransactioncomment_datetime'),
    ]

    operations = [
        migrations.RunPython(update_stocks),        
    ]
