# Generated by Django 3.2.4 on 2021-08-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20210810_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='notif_type',
            field=models.CharField(choices=[('CORRECTION_REQUEST', 'CORRECTION_REQUEST'), ('CORRECTION_DONE', 'CORRECTION_DONE'), ('LOT_REJECTED', 'LOT_REJECTED'), ('LOT_PENDING', 'LOT_PENDING'), ('DECLARATION_INVALIDATED', 'DECLARATION_INVALIDATED'), ('DECLARATION_VALIDATED', 'DECLARATION_VALIDATED')], default='', max_length=32),
        ),
    ]
