# Generated by Django 3.2.4 on 2021-08-10 14:44

from django.db import migrations

def cleanup_notifs(apps, schema_editor):
    Entity = apps.get_model('core', 'Entity')
    EmailNotification = apps.get_model('core', 'EmailNotification')

    EmailNotification.objects.filter(entity__isnull=True).delete()
    EmailNotification.objects.filter(entity__notifications_enabled=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_alter_emailnotification_notif_type'),
    ]

    operations = [
        migrations.RunPython(cleanup_notifs),        
    ]
