# Generated by Django 3.2.4 on 2021-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_auto_20210810_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransactioncomment',
            name='is_visible_by_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admintransactioncomment',
            name='is_visible_by_auditor',
            field=models.BooleanField(default=False),
        ),
    ]
