# Generated by Django 3.2.4 on 2021-08-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_auto_20210811_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotv2',
            name='ghg_reduction_red_ii',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lotv2',
            name='ghg_reference_red_ii',
            field=models.FloatField(default=0.0),
        ),
    ]
