# Generated by Django 3.2.4 on 2021-08-27 08:26

from django.db import migrations
import datetime

july1st2021 = datetime.date(year=2021, month=7, day=1)

def set_red_ii_ghg_values(apps, schema_editor):
    LotTransaction = apps.get_model('core', 'LotTransaction')    
    for tx in LotTransaction.objects.filter(lot__status='Validated', delivery_date__gte=july1st2021):
        tx.lot.ghg_reference_red_ii = 94.0
        tx.lot.ghg_reduction_red_ii = round((1.0 - (tx.lot.ghg_total / tx.lot.ghg_reference_red_ii)) * 100.0, 2)
        tx.lot.save()
        


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_auto_20210827_1024'),
    ]

    operations = [
        migrations.RunPython(set_red_ii_ghg_values),
    ]
