# Generated by Django 3.2.4 on 2021-09-27 15:44

from django.db import migrations

def set_red_ii_ghg_savings(apps, schema_editor):
    LotV2 = apps.get_model('core', 'LotV2')    
    for lot in LotV2.objects.all():
        lot.ghg_reference_red_ii = 94.0
        lot.ghg_reduction_red_ii = round((1.0 - (lot.ghg_total / lot.ghg_reference_red_ii)) * 100.0, 2)
        lot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_auto_20210922_1452'),
    ]

    operations = [
    ]
