# Generated by Django 3.2.4 on 2021-10-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_lottransaction_potential_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransactioncomment',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
        ),
    ]
