# Generated by Django 3.2.8 on 2021-10-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_admintransactioncomment_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottransaction',
            name='child_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='core.lottransaction'),
        ),
        migrations.AlterField(
            model_name='lottransaction',
            name='parent_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='core.lottransaction'),
        ),
    ]
