# Generated by Django 3.2.8 on 2021-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_auto_20211022_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocarburant',
            name='dgddi_category',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='accise',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='dgddi_category',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
