# Generated by Django 3.2.8 on 2021-11-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_auto_20211105_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericerror',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carburelot'),
        ),
        migrations.AlterField(
            model_name='carburelot',
            name='transport_document_reference',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='carburelotevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('VALIDATED', 'VALIDATED'), ('FIX_REQUESTED', 'FIX_REQUESTED'), ('MARKED_AS_FIXED', 'MARKED_AS_FIXED'), ('FIX_ACCEPTED', 'FIX_ACCEPTED'), ('ACCEPTED', 'ACCEPTED'), ('DECLARED', 'DECLARED'), ('DELETED', 'DELETED'), ('RESTORED', 'RESTORED'), ('SPLIT', 'SPLIT'), ('UNSPLIT', 'UNSPLIT'), ('CONVERT', 'CONVERT'), ('UNCONVERT', 'UNCONVERT')], max_length=32),
        ),
        migrations.AlterField(
            model_name='genericerror',
            name='tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lottransaction'),
        ),
    ]
