# Generated by Django 3.2.8 on 2021-11-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_auto_20211106_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carburelot',
            options={'verbose_name': 'CarbureLot', 'verbose_name_plural': 'CarbureLots'},
        ),
        migrations.AlterField(
            model_name='carburelot',
            name='transport_document_reference',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='carburelotevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('VALIDATED', 'VALIDATED'), ('FIX_REQUESTED', 'FIX_REQUESTED'), ('MARKED_AS_FIXED', 'MARKED_AS_FIXED'), ('FIX_ACCEPTED', 'FIX_ACCEPTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('RECALLED', 'RECALLED'), ('DECLARED', 'DECLARED'), ('DELETED', 'DELETED'), ('RESTORED', 'RESTORED'), ('SPLIT', 'SPLIT'), ('UNSPLIT', 'UNSPLIT'), ('CONVERT', 'CONVERT'), ('UNCONVERT', 'UNCONVERT')], max_length=32),
        ),
        migrations.CreateModel(
            name='CarbureNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_dt', models.DateTimeField(auto_now_add=True)),
                ('send_copy_to_admin', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_dt', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carburelotevent')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
            ],
            options={
                'verbose_name': 'Carbure Email Notification',
                'verbose_name_plural': 'Cabure Email Notifications',
                'db_table': 'carbure_notifications',
            },
        ),
        migrations.AddIndex(
            model_name='carburenotification',
            index=models.Index(fields=['is_sent'], name='carbure_not_is_sent_e22c04_idx'),
        ),
    ]
