# Generated by Django 3.2.8 on 2022-01-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_auto_20211230_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='carburelot',
            name='carbure_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbure_vendor', to='core.entity'),
        ),
        migrations.AddField(
            model_name='carburelot',
            name='vendor_certificate',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='carburelot',
            name='vendor_certificate_type',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
