# Generated by Django 3.2.8 on 2021-11-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburelot',
            name='delivery_type',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('RFC', 'RFC'), ('STOCK', 'STOCK'), ('BLENDING', 'BLENDING'), ('EXPORT', 'EXPORT'), ('TRADING', 'TRADING'), ('PROCESSING', 'PROCESSING'), ('DIRECT', 'DIRECT'), ('FLUSHED', 'FLUSHED')], default='UNKNOWN', max_length=64),
        ),
        migrations.AlterField(
            model_name='carburelotevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('VALIDATED', 'VALIDATED'), ('FIX_REQUESTED', 'FIX_REQUESTED'), ('MARKED_AS_FIXED', 'MARKED_AS_FIXED'), ('FIX_ACCEPTED', 'FIX_ACCEPTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('RECALLED', 'RECALLED'), ('DECLARED', 'DECLARED'), ('DELETED', 'DELETED'), ('DECLCANCEL', 'DECLCANCEL'), ('RESTORED', 'RESTORED'), ('SPLIT', 'SPLIT'), ('UNSPLIT', 'UNSPLIT'), ('CONVERT', 'CONVERT'), ('UNCONVERT', 'UNCONVERT')], max_length=32),
        ),
        migrations.AlterField(
            model_name='carburelotevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
