# Generated by Django 3.2.8 on 2021-11-19 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0193_auto_20211119_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburelotevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('VALIDATED', 'VALIDATED'), ('FIX_REQUESTED', 'FIX_REQUESTED'), ('MARKED_AS_FIXED', 'MARKED_AS_FIXED'), ('FIX_ACCEPTED', 'FIX_ACCEPTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('RECALLED', 'RECALLED'), ('DECLARED', 'DECLARED'), ('DELETED', 'DELETED'), ('DECLCANCEL', 'DECLCANCEL'), ('RESTORED', 'RESTORED')], max_length=32),
        ),
        migrations.CreateModel(
            name='CarbureStockEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('SPLIT', 'SPLIT'), ('UNSPLIT', 'UNSPLIT'), ('FLUSHED', 'FLUSHED'), ('TRANSFORMED', 'TRANSFORMED'), ('UNTRANSFORMED', 'UNTRANSFORMED')], max_length=32)),
                ('event_dt', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carburestock')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CarbureStockEvent',
                'verbose_name_plural': 'CarbureStockEvents',
                'db_table': 'carbure_stock_events',
            },
        ),
        migrations.AddIndex(
            model_name='carburestockevent',
            index=models.Index(fields=['stock'], name='carbure_sto_stock_i_d107a1_idx'),
        ),
    ]
