# Generated by Django 3.2.8 on 2022-01-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_auto_20220103_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcertificate',
            name='has_been_updated',
            field=models.BooleanField(default=False),
        ),
    ]
