# Generated by Django 3.2.8 on 2022-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_genericcertificate_has_been_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericcertificate',
            name='has_been_updated',
        ),
        migrations.AddField(
            model_name='entitycertificate',
            name='has_been_updated',
            field=models.BooleanField(default=False),
        ),
    ]
