# Generated by Django 4.0.2 on 2022-02-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_auto_20220121_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburelot',
            name='delivery_type',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('RFC', 'RFC'), ('STOCK', 'STOCK'), ('BLENDING', 'BLENDING'), ('EXPORT', 'EXPORT'), ('TRADING', 'TRADING'), ('PROCESSING', 'PROCESSING'), ('DIRECT', 'DIRECT'), ('FLUSHED', 'FLUSHED'), ('NATIONAL', 'NATIONAL')], default='UNKNOWN', max_length=64),
        ),
    ]
