# Generated by Django 3.2.8 on 2021-11-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_auto_20211119_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CarbureEntityCertificates',
                'verbose_name_plural': 'CarbureEntityCertificates',
                'db_table': 'carbure_entity_certificates',
            },
        ),
        migrations.CreateModel(
            name='GenericCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('SYSTEME_NATIONAL', 'SYSTEME_NATIONAL'), ('ISCC', 'ISCC'), ('REDCERT', 'REDCERT'), ('2BS', '2BS')], max_length=32)),
                ('certificate_holder', models.CharField(max_length=256)),
                ('certificate_issuer', models.CharField(max_length=256)),
                ('address', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('download_link', models.CharField(default=None, max_length=512, null=True)),
                ('scope', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'CarbureCertificates',
                'verbose_name_plural': 'CarbureCertificates',
                'db_table': 'carbure_certificates',
            },
        ),
        migrations.AddIndex(
            model_name='genericcertificate',
            index=models.Index(fields=['certificate_type'], name='carbure_cer_certifi_e5a0bd_idx'),
        ),
        migrations.AddField(
            model_name='entitycertificate',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genericcertificate'),
        ),
        migrations.AddField(
            model_name='entitycertificate',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
        ),
        migrations.AddIndex(
            model_name='entitycertificate',
            index=models.Index(fields=['entity'], name='carbure_ent_entity__461638_idx'),
        ),
    ]
