# Generated by Django 3.2.10 on 2022-02-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_alter_carburelot_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburelot',
            name='delivery_type',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('RFC', 'RFC'), ('STOCK', 'STOCK'), ('BLENDING', 'BLENDING'), ('EXPORT', 'EXPORT'), ('TRADING', 'TRADING'), ('PROCESSING', 'PROCESSING'), ('DIRECT', 'DIRECT'), ('FLUSHED', 'FLUSHED')], default='UNKNOWN', max_length=64),
        ),
    ]
