# Generated by Django 3.2.8 on 2021-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_auto_20211122_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcertificate',
            name='input',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='genericcertificate',
            name='output',
            field=models.JSONField(null=True),
        ),
    ]
