# Generated by Django 3.2.8 on 2021-11-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_auto_20211122_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcertificate',
            name='certificate_id',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
