# Generated by Django 4.0.2 on 2022-02-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_alter_carburelot_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carburelot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
