# Generated by Django 3.2.8 on 2021-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_genericcertificate_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcertificate',
            name='certificate_holder',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='genericcertificate',
            name='certificate_issuer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
