# Generated by Django 4.0.2 on 2022-03-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_carburelot_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='tx',
        ),
        migrations.RemoveField(
            model_name='controlfiles',
            name='control',
        ),
        migrations.RemoveField(
            model_name='controlmessages',
            name='control',
        ),
        migrations.RemoveField(
            model_name='controlmessages',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='controlmessages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='linked_declaration',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='linked_tx',
        ),
        migrations.RemoveField(
            model_name='etbetransformation',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='etbetransformation',
            name='added_by_user',
        ),
        migrations.RemoveField(
            model_name='etbetransformation',
            name='new_stock',
        ),
        migrations.RemoveField(
            model_name='etbetransformation',
            name='previous_stock',
        ),
        migrations.RemoveField(
            model_name='transactioncomment',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='transactioncomment',
            name='tx',
        ),
        migrations.RemoveField(
            model_name='transactionupdatehistory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='transactionupdatehistory',
            name='modified_by_entity',
        ),
        migrations.RemoveField(
            model_name='transactionupdatehistory',
            name='tx',
        ),
        migrations.RemoveField(
            model_name='genericerror',
            name='tx',
        ),
        migrations.DeleteModel(
            name='AdminTransactionComment',
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.DeleteModel(
            name='ControlFiles',
        ),
        migrations.DeleteModel(
            name='ControlMessages',
        ),
        migrations.DeleteModel(
            name='EmailNotification',
        ),
        migrations.DeleteModel(
            name='ETBETransformation',
        ),
        migrations.DeleteModel(
            name='TransactionComment',
        ),
        migrations.DeleteModel(
            name='TransactionUpdateHistory',
        ),
    ]
