# Generated by Django 3.2.8 on 2021-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_auto_20211122_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcertificate',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
