# Generated by Django 4.0.2 on 2022-03-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_remove_control_tx_remove_controlfiles_control_and_more'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS massbalance_out_transactions_lines;"),
        migrations.RunSQL("DROP TABLE IF EXISTS massbalance_out_transactions;"),
        migrations.RunSQL("DROP TABLE IF EXISTS check_rules;"),
    ]
