# Generated by Django 4.0.2 on 2022-03-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_auto_20220315_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='added_by_user',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='biocarburant',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='carbure_producer',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='carbure_production_site',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='data_origin_entity',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='fused_with',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='matiere_premiere',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='parent_lot',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='pays_origine',
        ),
        migrations.RemoveField(
            model_name='lotv2',
            name='unknown_production_country',
        ),
        migrations.DeleteModel(
            name='LotTransaction',
        ),
        migrations.DeleteModel(
            name='LotV2',
        ),
    ]
