# Generated by Django 4.0.2 on 2022-03-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_delete_lot_remove_lotv2_added_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarbureNotification',
        ),
    ]
