# Generated by Django 4.0.2 on 2022-03-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_delete_carburenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbureNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('type', models.CharField(choices=[('CORRECTION_REQUEST', 'CORRECTION_REQUEST'), ('CORRECTION_DONE', 'CORRECTION_DONE'), ('LOTS_REJECTED', 'LOTS_REJECTED'), ('CERTIFICATE_EXPIRED', 'CERTIFICATE_EXPIRED'), ('DECLARATION_VALIDATED', 'DECLARATION_VALIDATED'), ('DECLARATION_CANCELLED', 'DECLARATION_CANCELLED')], max_length=32)),
                ('acked', models.BooleanField(default=False)),
                ('send_by_email', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
            ],
            options={
                'verbose_name': 'CarbureNotification',
                'verbose_name_plural': 'CarbureNotifications',
                'db_table': 'carbure_notifications',
            },
        ),
        migrations.AddIndex(
            model_name='carburenotification',
            index=models.Index(fields=['dest_id'], name='carbure_not_dest_id_4ac7b3_idx'),
        ),
    ]
