# Generated by Django 4.0.2 on 2022-03-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_alter_carburenotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carburenotification',
            name='notify_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
