# Generated by Django 4.0.2 on 2022-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_alter_carburenotification_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburenotification',
            name='type',
            field=models.CharField(choices=[('CORRECTION_REQUEST', 'CORRECTION_REQUEST'), ('CORRECTION_DONE', 'CORRECTION_DONE'), ('LOTS_REJECTED', 'LOTS_REJECTED'), ('LOTS_RECEIVED', 'LOTS_RECEIVED'), ('LOTS_RECALLED', 'LOTS_RECALLED'), ('CERTIFICATE_EXPIRED', 'CERTIFICATE_EXPIRED'), ('DECLARATION_VALIDATED', 'DECLARATION_VALIDATED'), ('DECLARATION_CANCELLED', 'DECLARATION_CANCELLED')], max_length=32),
        ),
    ]
