# Generated by Django 4.0.2 on 2022-05-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_carburelot_audit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carburelot',
            name='data_reliability_score',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.CreateModel(
            name='CarbureLotReliabilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=1)),
                ('item', models.CharField(choices=[('CUSTOMS_AND_CARBURE_MATCH', 'CUSTOMS_AND_CARBURE_MATCH'), ('DATA_SOURCE_IS_PRODUCER', 'DATA_SOURCE_IS_PRODUCER'), ('LOT_DECLARED', 'LOT_DECLARED'), ('CERTIFICATES_CHECKED', 'CERTIFICATES_CHECKED'), ('ANOMALIES', 'ANOMALIES')], default='Unknown', max_length=32)),
                ('comment', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carburelot')),
            ],
            options={
                'verbose_name': 'CarbureLotReliabilityScore',
                'verbose_name_plural': 'CarbureLotReliabilityScores',
                'db_table': 'carbure_lots_scores',
            },
        ),
        migrations.AddIndex(
            model_name='carburelotreliabilityscore',
            index=models.Index(fields=['lot'], name='carbure_lot_lot_id_e75cc9_idx'),
        ),
    ]
