# Generated by Django 4.0.2 on 2022-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_carburelot_data_reliability_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburelotreliabilityscore',
            name='item',
            field=models.CharField(choices=[('CUSTOMS_AND_CARBURE_MATCH', 'CUSTOMS_AND_CARBURE_MATCH'), ('DATA_SOURCE_IS_PRODUCER', 'DATA_SOURCE_IS_PRODUCER'), ('LOT_DECLARED', 'LOT_DECLARED'), ('PRODUCER_CERTIFICATE_CHECKED', 'PRODUCER_CERTIFICATE_CHECKED'), ('SUPPLIER_CERTIFICATE_CHECKED', 'SUPPLIER_CERTIFICATE_CHECKED'), ('SUPPLIER_CERTIFICATE_EXISTS', 'SUPPLIER_CERTIFICATE_EXISTS'), ('FEEDSTOCK_REGISTERED', 'FEEDSTOCK_REGISTERED'), ('BIOFUEL_REGISTERED', 'BIOFUEL_REGISTERED'), ('DELIVERY_SITE_REGISTERED', 'DELIVERY_SITE_REGISTERED')], default='Unknown', max_length=32),
        ),
    ]
