# Generated by Django 4.0.2 on 2022-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_alter_carburelotreliabilityscore_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburelotreliabilityscore',
            name='max_score',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='carburelotreliabilityscore',
            name='score',
            field=models.FloatField(default=1),
        ),
    ]
