# Generated by Django 4.0.2 on 2022-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_alter_carburelotreliabilityscore_max_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carburelotreliabilityscore',
            name='comment',
        ),
        migrations.AddField(
            model_name='carburelotreliabilityscore',
            name='meta',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='carburelotreliabilityscore',
            name='item',
            field=models.CharField(choices=[('CUSTOMS_AND_CARBURE_MATCH', 'CUSTOMS_AND_CARBURE_MATCH'), ('DATA_SOURCE_IS_PRODUCER', 'DATA_SOURCE_IS_PRODUCER'), ('LOT_DECLARED', 'LOT_DECLARED'), ('ANOMALIES_CERTIFICATES', 'ANOMALIES_CERTIFICATES'), ('ANOMALIES_CONFIGURATION', 'ANOMALIES_CONFIGURATION')], default='Unknown', max_length=32),
        ),
    ]
