# Generated by Django 4.0.2 on 2022-06-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_remove_carburelotreliabilityscore_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carburelot',
            name='ml_scoring',
            field=models.FloatField(default=0.0),
        ),
    ]
