# Generated by Django 4.0.2 on 2022-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_remove_carburelotreliabilityscore_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='preferred_unit',
            field=models.CharField(choices=[('l', 'litres'), ('kg', 'kg'), ('MJ', 'MJ')], default='l', max_length=64),
        ),
    ]
