# Generated by Django 4.0.2 on 2022-06-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_carburelot_ml_scoring'),
        ('core', '0216_entity_preferred_unit'),
    ]

    operations = [
    ]
