# Generated by Django 4.0.2 on 2022-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_merge_20220614_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biocarburant',
            options={'ordering': ['name'], 'verbose_name': 'Biocarburant', 'verbose_name_plural': 'Biocarburants'},
        ),
        migrations.AlterModelOptions(
            name='depot',
            options={'ordering': ['name'], 'verbose_name': 'Dépôt', 'verbose_name_plural': 'Dépôts'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='matierepremiere',
            options={'ordering': ['name'], 'verbose_name': 'Matiere Premiere', 'verbose_name_plural': 'Matieres Premieres'},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'ordering': ['name'], 'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.AlterField(
            model_name='carburelotevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('VALIDATED', 'VALIDATED'), ('FIX_REQUESTED', 'FIX_REQUESTED'), ('MARKED_AS_FIXED', 'MARKED_AS_FIXED'), ('FIX_ACCEPTED', 'FIX_ACCEPTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('RECALLED', 'RECALLED'), ('DECLARED', 'DECLARED'), ('DELETED', 'DELETED'), ('DECLCANCEL', 'DECLCANCEL'), ('RESTORED', 'RESTORED'), ('CANCELLED', 'CANCELLED')], max_length=32),
        ),
        migrations.AlterField(
            model_name='carburenotification',
            name='type',
            field=models.CharField(choices=[('CORRECTION_REQUEST', 'CORRECTION_REQUEST'), ('CORRECTION_DONE', 'CORRECTION_DONE'), ('LOTS_REJECTED', 'LOTS_REJECTED'), ('LOTS_RECEIVED', 'LOTS_RECEIVED'), ('LOTS_RECALLED', 'LOTS_RECALLED'), ('CERTIFICATE_EXPIRED', 'CERTIFICATE_EXPIRED'), ('DECLARATION_VALIDATED', 'DECLARATION_VALIDATED'), ('DECLARATION_CANCELLED', 'DECLARATION_CANCELLED'), ('DECLARATION_REMINDER', 'DECLARATION_REMINDER')], max_length=32),
        ),
    ]
