# Generated by Django 4.0.2 on 2022-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_alter_biocarburant_options_alter_depot_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['year', 'lot_status'], name='carbure_lot_year_26abfd_idx'),
        ),
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['year', 'period', 'lot_status'], name='carbure_lot_year_636d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='genericerror',
            index=models.Index(fields=['lot'], name='generic_err_lot_id_be0e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='genericerror',
            index=models.Index(fields=['lot', 'acked_by_admin', 'display_to_admin'], name='generic_err_lot_id_226bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='genericerror',
            index=models.Index(fields=['lot', 'acked_by_creator', 'display_to_creator'], name='generic_err_lot_id_5144e1_idx'),
        ),
        migrations.AddIndex(
            model_name='genericerror',
            index=models.Index(fields=['lot', 'acked_by_recipient', 'display_to_recipient'], name='generic_err_lot_id_c3d7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='genericerror',
            index=models.Index(fields=['lot', 'acked_by_auditor', 'display_to_auditor'], name='generic_err_lot_id_f3894c_idx'),
        ),
    ]
