# Generated by Django 4.0.2 on 2022-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_carburelot_carbure_lot_year_26abfd_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['period'], name='carbure_lot_period_03dfac_idx'),
        ),
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['biofuel'], name='carbure_lot_biofuel_abbb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['feedstock'], name='carbure_lot_feedsto_d8cad3_idx'),
        ),
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['carbure_supplier'], name='carbure_lot_carbure_7a9f07_idx'),
        ),
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['carbure_client'], name='carbure_lot_carbure_612b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['carbure_delivery_site'], name='carbure_lot_carbure_a60b71_idx'),
        ),
        migrations.AddIndex(
            model_name='carburelot',
            index=models.Index(fields=['carbure_production_site'], name='carbure_lot_carbure_060fe8_idx'),
        ),
    ]
