# Generated by Django 4.0.2 on 2022-08-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0220_carburelot_carbure_lot_period_03dfac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
