# Generated by Django 4.1.1 on 2023-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LockedYear",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("locked", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Locked Year",
                "verbose_name_plural": "Locked Years",
                "db_table": "locked_years",
            },
        ),
        migrations.AddIndex(
            model_name="lockedyear",
            index=models.Index(fields=["year"], name="locked_year_year_7a312c_idx"),
        ),
    ]
