# Generated by Django 4.1.7 on 2024-02-08 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LockedYear",
            new_name="YearConfig",
        ),
        migrations.AlterModelOptions(
            name="yearconfig",
            options={"verbose_name": "Configuration annuelle", "verbose_name_plural": "Configurations annuelles"},
        ),
        migrations.RenameIndex(
            model_name="yearconfig",
            new_name="year_config_year_75936e_idx",
            old_name="locked_year_year_7a312c_idx",
        ),
        migrations.AlterModelTable(
            name="yearconfig",
            table="year_config",
        ),
    ]
