# Generated by Django 4.1.7 on 2024-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_rename_lockedyear_yearconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearconfig",
            name="renewable_share",
            field=models.FloatField(blank=True, help_text="En pourcentage (ex: 24.92)", null=True),
        ),
        migrations.AlterField(
            model_name="yearconfig",
            name="locked",
            field=models.BooleanField(default=True, help_text="Bloquer les déclarations"),
        ),
    ]
