# Generated by Django 5.0.6 on 2024-11-04 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_move_data_to_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depot",
            fields=[],
            options={
                "verbose_name": "Dépôt",
                "verbose_name_plural": "Dépôts",
                "ordering": ["name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transactions.site",),
        ),
        migrations.CreateModel(
            name="ProductionSite",
            fields=[],
            options={
                "verbose_name": "Site de Production",
                "verbose_name_plural": "Sites de Production",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transactions.site",),
        ),
    ]
