# Generated by Django 5.0.6 on 2024-12-05 09:25

from django.db import migrations, models


def update_site_type(apps, schema_editor):
    Site = apps.get_model("transactions", "Site")
    Site.objects.filter(site_type="PRODUCTION SITE").update(site_type="PRODUCTION BIOLIQUID")


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_depot_productionsite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="site_type",
            field=models.CharField(
                choices=[
                    ("OTHER", "Autre"),
                    ("EFS", "EFS"),
                    ("EFPE", "EFPE"),
                    ("OIL DEPOT", "OIL DEPOT"),
                    ("BIOFUEL DEPOT", "BIOFUEL DEPOT"),
                    ("HEAT PLANT", "HEAT PLANT"),
                    ("POWER PLANT", "POWER PLANT"),
                    ("COGENERATION PLANT", "COGENERATION PLANT"),
                    ("PRODUCTION BIOLIQUID", "PRODUCTION BIOLIQUID"),
                    ("EFCA", "EFCA"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
        migrations.RunPython(update_site_type),
    ]
