# Generated by Django 5.0.6 on 2025-01-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0009_alter_site_site_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="icao_code",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
