# Generated by Django 5.0.6 on 2025-01-29 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0010_site_icao_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[],
            options={
                "verbose_name": "Aéroport",
                "verbose_name_plural": "Aéroports",
                "ordering": ["name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transactions.site",),
        ),
    ]
