# Generated by Django 5.0.6 on 2025-02-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0011_airport"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="is_ue_airport",
            field=models.BooleanField(default=True),
        ),
    ]
