# Generated by Django 5.0.6 on 2025-03-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0012_site_is_ue_airport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearconfig",
            name="renewable_share",
            field=models.FloatField(default=25, help_text="En pourcentage (ex: 24.92)"),
        ),
    ]
