# Generated by Django 5.0.6 on 2025-03-12 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0013_alter_yearconfig_renewable_share"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentToUpdate",
        ),
    ]
