# Generated by Django 5.2.2 on 2026-02-11 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0016_split_site_into_concrete_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["name"], "verbose_name": "Site", "verbose_name_plural": "Sites"},
        ),
    ]
