# Generated by Django 5.2.2 on 2026-06-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_change_feedstock_collation"),
        ("transactions", "0018_alter_site_site_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.CharField(blank=True, max_length=256, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="site",
            name="city",
            field=models.CharField(blank=True, max_length=128, verbose_name="Commune"),
        ),
        migrations.AlterField(
            model_name="site",
            name="country",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.pays", verbose_name="Pays"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="gps_coordinates",
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="Coordonnées GPS"),
        ),
        migrations.AlterField(
            model_name="site",
            name="postal_code",
            field=models.CharField(blank=True, max_length=32, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="site",
            name="site_siret",
            field=models.CharField(blank=True, max_length=64, verbose_name="SIRET"),
        ),
    ]
