# Generated by Django 5.2.2 on 2026-07-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0019_alter_site_address_alter_site_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="commissioning_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de mise en service"),
        ),
    ]
