# Generated by Django 5.2.2 on 2026-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0020_site_commissioning_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="site_type",
            field=models.CharField(
                choices=[
                    ("OTHER", "Autre"),
                    ("EFS", "EFS"),
                    ("EFPE", "EFPE"),
                    ("OIL DEPOT", "OIL DEPOT"),
                    ("BIOFUEL DEPOT", "BIOFUEL DEPOT"),
                    ("HEAT PLANT", "HEAT PLANT"),
                    ("POWER PLANT", "POWER PLANT"),
                    ("COGENERATION PLANT", "COGENERATION PLANT"),
                    ("PRODUCTION BIOLIQUID", "PRODUCTION BIOLIQUID"),
                    ("PRODUCTION BIOGAZ", "PRODUCTION BIOGAZ"),
                    ("EFCA", "EFCA"),
                    ("AIRPORT", "AIRPORT"),
                    ("H2 REFUELING STATION", "H2 REFUELING STATION"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
    ]
