# Generated by Django 5.2.2 on 2026-08-05 09:19

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0077_alter_externaladminrights_right"),
        ("transactions", "0021_alter_site_site_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "db_table": "material",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pos_id", models.CharField(max_length=48, unique=True, verbose_name="N° de POS")),
                ("industry", models.CharField(choices=[("H2", "Hydrogène")], max_length=16, verbose_name="Filière")),
                ("type", models.CharField(choices=[("INIT", "INIT")], max_length=16, verbose_name="Type d'action")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=13, verbose_name="Quantité de matière")),
                ("shipping_date", models.DateField(verbose_name="Date d'expédition")),
                ("shipping_distance", models.IntegerField(verbose_name="Distance de livraison")),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("ROAD", "Transport routier"),
                            ("PIPELINE", "Pipeline"),
                            ("RAILROAD", "Rail"),
                            ("SEA", "Transport maritime"),
                        ],
                        max_length=16,
                        verbose_name="Mode de transport",
                    ),
                ),
                ("ei", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7)),
                ("ep", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7)),
                ("etd", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7)),
                ("eu", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7)),
                ("eccs", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7)),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.entity",
                        verbose_name="Entité détentrice de la quantité de l'action",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="traceability.action",
                        verbose_name="Action parente",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="transactions.site", verbose_name="Site"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="traceability.material", verbose_name="Matière"
                    ),
                ),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
                "db_table": "action",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ActionStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("PENDING", "PENDING"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("BLOCKED", "BLOCKED"),
                            ("DELETED", "DELETED"),
                        ],
                        max_length=16,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_statuses",
                        to="traceability.action",
                        verbose_name="Action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statut d'action",
                "verbose_name_plural": "Statuts d'action",
                "db_table": "action_status",
                "ordering": ["id"],
            },
        ),
    ]
