# Generated by Django 5.2.2 on 2026-08-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="traceability.action",
                verbose_name="Action parente",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="code",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
