# Generated by Django 5.2.2 on 2026-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0002_alter_action_parent_alter_material_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"verbose_name": "Action", "verbose_name_plural": "Actions"},
        ),
    ]
