# Generated by Django 5.2.2 on 2026-08-26 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0003_alter_action_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["id"], "verbose_name": "Action", "verbose_name_plural": "Actions"},
        ),
    ]
