# Generated by Django 5.2.2 on 2026-08-31 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_merge_20260824_1747"),
        ("traceability", "0004_alter_action_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="core.genericcertificate",
                verbose_name="Certificat du producteur",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="pos_id",
            field=models.CharField(
                error_messages={"unique": "Ce N° de POS existe déjà."},
                max_length=48,
                unique=True,
                verbose_name="N° de POS",
            ),
        ),
    ]
