# Generated by Django 5.2.2 on 2026-09-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_merge_20260824_1747"),
        ("traceability", "0005_action_certificate_alter_action_pos_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="core.genericcertificate",
                verbose_name="Certificat",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="shipping_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expédition"),
        ),
        migrations.AlterField(
            model_name="action",
            name="shipping_distance",
            field=models.IntegerField(blank=True, null=True, verbose_name="Distance de livraison"),
        ),
        migrations.AlterField(
            model_name="action",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROAD", "Transport routier"),
                    ("PIPELINE", "Pipeline"),
                    ("RAILROAD", "Rail"),
                    ("SEA", "Transport maritime"),
                ],
                max_length=16,
                verbose_name="Mode de transport",
            ),
        ),
    ]
