# Generated by Django 5.2.2 on 2026-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0006_alter_action_certificate_alter_action_shipping_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="type",
            field=models.CharField(
                choices=[("INIT", "INIT"), ("VALORIZE", "VALORIZE")], max_length=16, verbose_name="Type d'action"
            ),
        ),
    ]
