# Generated by Django 5.2.2 on 2026-09-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0007_alter_action_type"),
        ("transactions", "0021_alter_site_site_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="material",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="traceability.material", verbose_name="Matière"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="site",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="transactions.site", verbose_name="Site"
            ),
        ),
    ]
