# Generated by Django 5.2.2 on 2026-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0008_alter_action_material_alter_action_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROAD", "Transport routier"),
                    ("PIPELINE", "Pipeline"),
                    ("RAILROAD", "Rail"),
                    ("SEA", "Transport maritime"),
                ],
                max_length=16,
                null=True,
                verbose_name="Mode de transport",
            ),
        ),
    ]
