# Generated by Django 5.2.2 on 2026-09-09 12:58

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0009_alter_action_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="eccr",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7),
        ),
        migrations.AddField(
            model_name="action",
            name="eec",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7),
        ),
        migrations.AddField(
            model_name="action",
            name="el",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7),
        ),
        migrations.AddField(
            model_name="action",
            name="esca",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7),
        ),
    ]
