# Generated by Django 5.2.2 on 2026-09-16 07:00

from django.db import migrations, models


def backfill_action_units(apps, schema_editor):
    Action = apps.get_model("traceability", "Action")
    Action.objects.filter(type="INIT").update(unit="kg")
    Action.objects.filter(type="VALORIZE").update(unit="MJ")


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0010_action_eccr_action_eec_action_el_action_esca"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="unit",
            field=models.CharField(
                choices=[("l", "litres"), ("kg", "kg"), ("MJ", "MJ")],
                max_length=8,
                null=True,
                verbose_name="Unité",
            ),
        ),
        migrations.RunPython(backfill_action_units, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="action",
            name="unit",
            field=models.CharField(
                choices=[("l", "litres"), ("kg", "kg"), ("MJ", "MJ")],
                max_length=8,
                verbose_name="Unité",
            ),
        ),
    ]
