# Generated by Django 5.2.2 on 2026-09-10 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_storedfile"),
        ("traceability", "0010_action_eccr_action_eec_action_el_action_esca"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="core.storedfile",
                verbose_name="Fichier",
            ),
        ),
    ]
