# Generated by Django 5.2.2 on 2026-10-05 07:44

from django.db import migrations, models


def set_existing_materials_unit_to_kg(apps, schema_editor):
    """At this point the catalogue only contains H2 materials, stored in kg."""
    Material = apps.get_model("traceability", "Material")
    Material.objects.update(unit="kg")


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0011_action_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="density",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True, verbose_name="Masse volumique (kg/l)"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="lhv",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name="PCI (MJ/kg)"),
        ),
        migrations.AddField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[("l", "litres"), ("kg", "kg"), ("MJ", "MJ")],
                max_length=8,
                null=True,
                verbose_name="Unité",
            ),
        ),
        migrations.RunPython(set_existing_materials_unit_to_kg, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[("l", "litres"), ("kg", "kg"), ("MJ", "MJ")],
                max_length=8,
                verbose_name="Unité",
            ),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.CheckConstraint(
                condition=models.Q(("lhv__isnull", True), ("lhv__gt", 0), _connector="OR"),
                name="material_lhv_null_or_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.CheckConstraint(
                condition=models.Q(("density__isnull", True), ("density__gt", 0), _connector="OR"),
                name="material_density_null_or_positive",
            ),
        ),
    ]
