# Generated by Django 5.2.2 on 2026-10-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0012_material_unit_lhv_density"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="code",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
