# Generated by Django 5.2.2 on 2026-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0012_material_lhv_density"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="density",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True, verbose_name="Masse volumique (kg/l)"
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="lhv",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name="PCI (MJ/kg)"),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(("lhv__isnull", True), ("lhv__gt", 0), _connector="OR"),
                name="action_lhv_null_or_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(("density__isnull", True), ("density__gt", 0), _connector="OR"),
                name="action_density_null_or_positive",
            ),
        ),
    ]
