# Generated by Django 5.2.2 on 2025-11-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityScope",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "entity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scopes", to="core.entity"),
                ),
            ],
            options={
                "verbose_name": "Entity Scope",
                "verbose_name_plural": "Entity Scopes",
                "db_table": "entity_scopes",
            },
        ),
        migrations.AddIndex(
            model_name="entityscope",
            index=models.Index(fields=["entity", "content_type"], name="entity_scop_entity__df2278_idx"),
        ),
        migrations.AddIndex(
            model_name="entityscope",
            index=models.Index(fields=["content_type", "object_id"], name="entity_scop_content_dd8fd1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="entityscope",
            unique_together={("entity", "content_type", "object_id")},
        ),
    ]
