# Generated by Django 5.2.2 on 2025-11-13 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_add_entityscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityScopeDepartment",
            fields=[],
            options={
                "verbose_name": "Entity Department Scope",
                "verbose_name_plural": "Entity Department Scopes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("entity.entityscope",),
        ),
        migrations.CreateModel(
            name="EntityScopeDepot",
            fields=[],
            options={
                "verbose_name": "Entity Depot Scope",
                "verbose_name_plural": "Entity Depot Scopes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("entity.entityscope",),
        ),
    ]
