# Generated by Django 3.0.3 on 2020-02-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20200223_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('deadline', models.DateField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Attestation de Durabilité',
                'verbose_name_plural': 'Attestations de Durabilité',
                'db_table': 'producer_attestations',
            },
        ),
    ]
