# Generated by Django 4.1.7 on 2023-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionsite",
            name="dc_number",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
    ]
