# Generated by Django 3.0.3 on 2020-03-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200303_1216'),
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('identifiant', models.CharField(max_length=64)),
                ('num_accise', models.CharField(max_length=64)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Site de Production',
                'verbose_name_plural': 'Sites de Production',
                'db_table': 'producer_sites',
            },
        ),
    ]
