# Generated by Django 3.0.3 on 2020-03-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200303_1216'),
        ('producers', '0002_productionsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateField()),
                ('certificate', models.FileField(upload_to='')),
                ('matiere_premiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MatierePremiere')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'db_table': 'producer_certificates',
            },
        ),
    ]
