# Generated by Django 4.1.7 on 2023-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0002_productionsite_dc_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionsite",
            name="dc_number",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
    ]
