# Generated by Django 5.0.6 on 2024-09-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0003_alter_productionsite_dc_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionsiteinput",
            name="production_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="producers.productionsite",
            ),
        ),
        migrations.AlterField(
            model_name="productionsiteoutput",
            name="production_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="producers.productionsite",
            ),
        ),
    ]
