# Generated by Django 3.0.3 on 2020-03-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_producercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='producercertificate',
            name='status',
            field=models.CharField(choices=[('Pending', 'En Attente de validation'), ('Valid', 'Validé'), ('Expired', 'Expiré'), ('Invalid', 'Invalide')], default='En Attente', max_length=32),
        ),
    ]
