# Generated by Django 5.0.6 on 2024-09-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0004_alter_productionsiteinput_production_site_and_more"),
        ("transactions", "0005_move_data_to_site_model_backup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionsiteinput",
            name="production_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.site",
            ),
        ),
        migrations.AlterField(
            model_name="productionsiteoutput",
            name="production_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.site",
            ),
        ),
    ]
