# Generated by Django 3.0.3 on 2020-03-04 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_producercertificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producercertificate',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producercertificate',
            name='status',
            field=models.CharField(choices=[('Pending', 'En Attente de validation'), ('Valid', 'Validé'), ('Expired', 'Expiré'), ('Invalid', 'Invalide')], default='Pending', max_length=32),
        ),
    ]
