# Generated by Django 3.0.3 on 2020-03-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0005_auto_20200304_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='producercertificate',
            name='certificate_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
