# Generated by Django 3.0.3 on 2020-03-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200303_1216'),
        ('producers', '0006_producercertificate_certificate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producercertificate',
            name='matiere_premiere',
        ),
        migrations.RemoveField(
            model_name='productionsite',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='productionsite',
            name='num_accise',
        ),
        migrations.AddField(
            model_name='producercertificate',
            name='production_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producers.ProductionSite'),
        ),
        migrations.AlterField(
            model_name='producercertificate',
            name='status',
            field=models.CharField(choices=[('Pending', 'En Attente de validation'), ('Valid', 'Validé'), ('Expired', 'Expiré')], default='Pending', max_length=32),
        ),
        migrations.CreateModel(
            name='ProductionSiteOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ges_option', models.CharField(choices=[('Default', 'Valeurs par défaut'), ('Actual', 'Valeurs réelles'), ('NUTS2', 'NUTS2')], default='Default', max_length=12)),
                ('iscc_eu_wpa', models.CharField(choices=[('Yes', 'Oui'), ('No', 'Non')], default='No', max_length=3)),
                ('biocarburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TypeBiocarburant')),
                ('production_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producers.ProductionSite')),
            ],
            options={
                'verbose_name': 'Site de Production - Biocarburant',
                'verbose_name_plural': 'Sites de Production - Biocarburants',
                'db_table': 'production_sites_output',
            },
        ),
        migrations.CreateModel(
            name='ProductionSiteInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MatierePremiere')),
                ('production_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producers.ProductionSite')),
            ],
            options={
                'verbose_name': 'Site de Production - Filiere',
                'verbose_name_plural': 'Sites de Production - Filieres',
                'db_table': 'production_sites_input',
            },
        ),
    ]
