# Generated by Django 5.2.2 on 2025-12-17 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0006_alter_productionsiteinput_production_site_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductionSite",
        ),
    ]
