# Generated by Django 5.2.2 on 2026-02-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0007_delete_productionsite"),
        ("transactions", "0017_update_site_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionsiteinput",
            name="production_site",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="transactions.productionsite"),
        ),
        migrations.AlterField(
            model_name="productionsiteoutput",
            name="production_site",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="transactions.productionsite"),
        ),
    ]
