# Generated by Django 3.0.3 on 2020-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0007_auto_20200304_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionsiteoutput',
            name='iscc_eu_wpa',
        ),
        migrations.AddField(
            model_name='productionsiteinput',
            name='eligible_double_comptage',
            field=models.CharField(choices=[('Yes', 'Oui'), ('No', 'Non')], default='No', max_length=3),
        ),
    ]
