# Generated by Django 3.0.3 on 2020-03-04 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200303_1216'),
        ('producers', '0008_auto_20200304_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsite',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Pays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionsite',
            name='date_mise_en_service',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
