# Generated by Django 3.0.3 on 2020-03-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0009_auto_20200304_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsiteinput',
            name='eligible_double_comptage',
            field=models.BooleanField(default=False),
        ),
    ]
