# Generated by Django 3.0.3 on 2020-03-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0011_auto_20200313_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionsiteoutput',
            name='ges_option',
        ),
        migrations.AddField(
            model_name='productionsite',
            name='ges_option',
            field=models.CharField(choices=[('Default', 'Valeurs par défaut'), ('Actual', 'Valeurs réelles')], default='Default', max_length=12),
        ),
    ]
