# Generated by Django 3.0.3 on 2020-06-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0015_delete_attestationproducer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsite',
            name='dc_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
