# Generated by Django 3.0.7 on 2020-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0016_productionsite_dc_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsite',
            name='dc_reference',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
