# Generated by Django 3.0.7 on 2020-11-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0017_auto_20200708_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsite',
            name='manager_email',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionsite',
            name='manager_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionsite',
            name='manager_phone',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionsite',
            name='postal_code',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionsite',
            name='site_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
