# Generated by Django 3.0.7 on 2020-11-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0018_auto_20201117_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsite',
            name='city',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
