# Generated by Django 3.0.7 on 2020-11-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0019_productionsite_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsite',
            name='ges_option',
            field=models.CharField(choices=[('Default', 'Valeurs par défaut'), ('Actual', 'Valeurs réelles'), ('NUTS2', 'Valeurs NUTS2')], default='Default', max_length=12),
        ),
    ]
