# Generated by Django 3.0.7 on 2021-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0020_auto_20201118_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsite',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='productionsite',
            name='manager_email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='productionsite',
            name='manager_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='productionsite',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='productionsite',
            name='postal_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='productionsite',
            name='site_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
