# Generated by Django 3.2 on 2021-06-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0021_auto_20210219_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProducerCertificate',
        ),
    ]
