# Generated by Django 3.2.4 on 2021-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0022_delete_producercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsite',
            name='gps_coordinates',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
