# Generated by Django 3.2.4 on 2021-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0023_productionsite_gps_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsite',
            name='address',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
