# Generated by Django 4.0.2 on 2022-06-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0024_productionsite_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionsite',
            options={'ordering': ['name'], 'verbose_name': 'Site de Production', 'verbose_name_plural': 'Sites de Production'},
        ),
    ]
