# Generated by Django 5.0.6 on 2025-04-02 14:25

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authtools", "0003_auto_20160128_0912"),
    ]

    operations = [
        migrations.CreateModel(
            name="InactiveUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authtools.user",),
        ),
    ]
