- hosts: new
  remote_user: root
  gather_facts: no
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python3-minimal)
    - setup: # gather_facts
  vars:
    username: deploy
    password: "{{ deploy_password }}"
    public_key: ~/.ssh/id_rsa.pub
  roles:
   - sudo
   - user
   - reboot
   
