# Generated by Django 3.2.4 on 2021-08-13 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0182_auto_20210811_1603'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dae', models.CharField(blank=True, default='', max_length=128)),
                ('client_is_in_carbure', models.BooleanField(default=True)),
                ('unknown_client', models.CharField(blank=True, default='', max_length=64)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_site_is_in_carbure', models.BooleanField(default=True)),
                ('unknown_delivery_site', models.CharField(blank=True, default='', max_length=64)),
                ('volume', models.FloatField(default=0.0)),
                ('biofuel_category', models.CharField(choices=[('ETHANOL', 'ETHANOL'), ('BIODIESEL', 'BIODIESEL'), ('OTHER', 'OTHER')], default='OTHER', max_length=32)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('creation_method', models.CharField(choices=[('USER', 'USER'), ('AUTO', 'AUTO'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=32)),
                ('is_sent', models.BooleanField(default=False)),
                ('carbure_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mb_pending_tx_client', to='core.entity')),
                ('carbure_delivery_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mb_pending_tx_destination_depot', to='core.depot')),
                ('carbure_storage_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mb_pending_tx_depot_source', to='core.depot')),
                ('created_by_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mb_pending_tx_creator', to='core.entity')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unknown_delivery_site_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pays')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mb_pending_tx_vendor', to='core.entity')),
            ],
            options={
                'verbose_name': 'DAE à remplir',
                'verbose_name_plural': 'DAE à remplir',
                'db_table': 'massbalance_out_transactions',
            },
        ),
        migrations.CreateModel(
            name='OutTransactionVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0.0)),
                ('out_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='massbalance.outtransaction')),
                ('related_stock_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lottransaction')),
            ],
            options={
                'verbose_name': 'DAE - Ligne',
                'verbose_name_plural': 'DAE - Lignes',
                'db_table': 'massbalance_out_transactions_lines',
            },
        ),
        migrations.AddIndex(
            model_name='outtransactionvolume',
            index=models.Index(fields=['out_transaction'], name='massbalance_out_tra_68a162_idx'),
        ),
        migrations.AddIndex(
            model_name='outtransaction',
            index=models.Index(fields=['vendor'], name='massbalance_vendor__64ed51_idx'),
        ),
        migrations.AddIndex(
            model_name='outtransaction',
            index=models.Index(fields=['biofuel_category'], name='massbalance_biofuel_e9d6b2_idx'),
        ),
    ]
