# Generated by Django 3.2.4 on 2021-08-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massbalance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outtransaction',
            old_name='created_by_user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='outtransaction',
            name='created_by_entity',
        ),
    ]
