# Generated by Django 3.2.4 on 2021-08-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massbalance', '0002_auto_20210818_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outtransaction',
            name='client_is_in_carbure',
        ),
        migrations.RemoveField(
            model_name='outtransaction',
            name='delivery_site_is_in_carbure',
        ),
    ]
