# Generated by Django 5.0.6 on 2024-11-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="customs_category",
            field=models.CharField(
                choices=[
                    ("CONV", "Conventionnel"),
                    ("ANN-IX-A", "ANNEXE IX-A"),
                    ("ANN-IX-B", "ANNEXE IX-B"),
                    ("TALLOL", "Tallol"),
                    ("OTHER", "Autre"),
                ],
                default="CONV",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                ],
                max_length=20,
            ),
        ),
    ]
