# Generated by Django 5.0.6 on 2024-12-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0002_alter_operation_customs_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationdetail",
            old_name="energy",
            new_name="volume",
        ),
        migrations.AlterField(
            model_name="operation",
            name="customs_category",
            field=models.CharField(
                choices=[
                    ("CONV", "Conventionnel"),
                    ("ANN-IX-A", "ANNEXE IX-A"),
                    ("ANN-IX-B", "ANNEXE IX-B"),
                    ("TALLOL", "Tallol"),
                    ("OTHER", "Autre"),
                    ("EP2AM", "EP2AM"),
                    ("AM", "AM"),
                ],
                default="CONV",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("CANCELED", "CANCELED"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
