# Generated by Django 5.0.6 on 2024-12-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0003_rename_energy_operationdetail_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                    ("EXPORTATION", "EXPORTATION"),
                    ("DEVALUATION", "DEVALUATION"),
                ],
                max_length=20,
            ),
        ),
    ]
