# Generated by Django 5.0.6 on 2024-12-19 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0004_alter_operation_type"),
        ("transactions", "0008_alter_site_site_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="depot",
        ),
        migrations.AddField(
            model_name="operation",
            name="from_depot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_from_depot",
                to="transactions.depot",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="to_depot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_to_depot",
                to="transactions.depot",
            ),
        ),
    ]
