# Generated by Django 5.0.6 on 2025-01-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_matierepremiere_category"),
        ("tiruert", "0006_rename_saved_ghg_operationdetail_emission_rate_per_mj"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="export_country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_country",
                to="core.pays",
            ),
        ),
    ]
