# Generated by Django 5.0.6 on 2025-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0007_operation_export_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="validity_date",
        ),
        migrations.AddField(
            model_name="operation",
            name="validation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
