# Generated by Django 5.0.6 on 2025-03-10 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0008_remove_operation_validity_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FossilFuelCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("pci_litre", models.FloatField()),
            ],
            options={
                "verbose_name": "Fossil Fuel Category",
                "verbose_name_plural": "Fossil Fuels Categories",
                "db_table": "fossil_fuel_categories",
            },
        ),
        migrations.CreateModel(
            name="FossilFuel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("pci_litre", models.FloatField()),
                (
                    "fuel_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fossil_fuels",
                        to="tiruert.fossilfuelcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fossil Fuel",
                "verbose_name_plural": "Fossil Fuels",
                "db_table": "fossil_fuels",
            },
        ),
        migrations.CreateModel(
            name="Objective",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("MAIN", "MAIN"), ("SECTOR", "SECTOR"), ("BIOFUEL_CATEGORY", "BIOFUEL_CATEGORY")],
                        max_length=255,
                    ),
                ),
                (
                    "customs_category",
                    models.CharField(
                        choices=[
                            ("CONV", "Conventionnel"),
                            ("ANN-IX-A", "ANNEXE IX-A"),
                            ("ANN-IX-B", "ANNEXE IX-B"),
                            ("TALLOL", "Tallol"),
                            ("OTHER", "Autre"),
                            ("EP2AM", "EP2AM"),
                            ("AM", "AM"),
                        ],
                        default="CONV",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField()),
                ("consideration_rate", models.FloatField()),
                ("target", models.FloatField()),
                (
                    "fuel_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objective_fossil_fuels",
                        to="tiruert.fossilfuelcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif Tiruert",
                "verbose_name_plural": "Objectifs Tiruert",
                "db_table": "tiruert_objectives",
            },
        ),
    ]
