# Generated by Django 5.0.6 on 2025-03-12 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_entity_accise_number_entity_is_tiruert_liable"),
        ("tiruert", "0009_fossilfuelcategory_fossilfuel_objective"),
        ("transactions", "0013_alter_yearconfig_renewable_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="fossilfuel",
            name="masse_volumique",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="fossilfuel",
            name="pci_litre",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                    ("EXPORTATION", "EXPORTATION"),
                    ("DEVALUATION", "DEVALUATION"),
                    ("CUSTOMS_CORRECTION", "CUSTOMS_CORRECTION"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MacFossilFuel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.FloatField(default=0.0)),
                ("period", models.IntegerField()),
                (
                    "depot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fossil_fuel_mac",
                        to="transactions.depot",
                    ),
                ),
                (
                    "fuel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mac",
                        to="tiruert.fossilfuel",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fossil_fuel_mac",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fossil Fuel MAC",
                "verbose_name_plural": "Fossil Fuels MACs",
                "db_table": "fossil_fuel_mac",
            },
        ),
    ]
