# Generated by Django 5.0.6 on 2025-03-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0010_fossilfuel_masse_volumique_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fossilfuel",
            old_name="name",
            new_name="label",
        ),
        migrations.AddField(
            model_name="fossilfuel",
            name="nomenclature",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="macfossilfuel",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="macfossilfuel",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="macfossilfuel",
            name="year",
            field=models.IntegerField(),
        ),
    ]
