# Generated by Django 5.0.6 on 2025-03-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0010_fossilfuel_masse_volumique_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fossilfuel",
            old_name="name",
            new_name="label",
        ),
        migrations.AddField(
            model_name="fossilfuel",
            name="nomenclatures",
            field=models.JSONField(default=list),
        ),
    ]
