# Generated by Django 5.0.6 on 2025-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0011_rename_name_fossilfuel_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fossilfuel",
            name="nomenclatures",
        ),
        migrations.AddField(
            model_name="fossilfuel",
            name="nomenclature",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="macfossilfuel",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="macfossilfuel",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
