# Generated by Django 5.0.6 on 2025-03-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_entity_accise_number_entity_is_tiruert_liable"),
        ("tiruert", "0011_rename_name_fossilfuel_label_and_more"),
        ("transactions", "0013_alter_yearconfig_renewable_share"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="macfossilfuel",
            constraint=models.UniqueConstraint(fields=("operator", "fuel", "period"), name="unicity"),
        ),
    ]
