# Generated by Django 5.0.6 on 2025-03-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tiruert",
            "0011_rename_name_fossilfuel_label_fossilfuel_nomenclature_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="objective",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("REACH", "Objectif à atteindre"),
                    ("CAP", "Plafond à ne pas dépasser"),
                ],
                default="REACH",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="consideration_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="objective",
            name="customs_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONV", "Conventionnel"),
                    ("ANN-IX-A", "ANNEXE IX-A"),
                    ("ANN-IX-B", "ANNEXE IX-B"),
                    ("TALLOL", "Tallol"),
                    ("OTHER", "Autre"),
                    ("EP2AM", "EP2AM"),
                    ("AM", "AM"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="fuel_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="objective_fossil_fuels",
                to="tiruert.fossilfuelcategory",
            ),
        ),
    ]
