# Generated by Django 5.0.6 on 2025-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0012_objective_target_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("CANCELED", "CANCELED"),
                    ("DECLARED", "DECLARED"),
                    ("CORRECTED", "CORRECTED"),
                    ("VALIDATED", "VALIDATED"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
