# Generated by Django 5.0.6 on 2025-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0014_alter_objective_customs_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objective",
            name="penalty",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
