# Generated by Django 5.0.6 on 2025-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0015_objective_penalty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objective",
            name="consideration_rate",
            field=models.FloatField(blank=True, help_text="saisir 0,50 pour 50%", null=True),
        ),
        migrations.AlterField(
            model_name="objective",
            name="penalty",
            field=models.IntegerField(blank=True, help_text="en centimes d'euros", null=True),
        ),
        migrations.AlterField(
            model_name="objective",
            name="target",
            field=models.FloatField(blank=True, help_text="saisir 0,50 pour 50%", null=True),
        ),
    ]
