# Generated by Django 5.0.6 on 2025-04-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0016_alter_objective_consideration_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElecOperation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ACQUISITION_FROM_CPO", "ACQUISITION_FROM_CPO"),
                            ("CESSION", "CESSION"),
                            ("TENEUR", "TENEUR"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("CANCELED", "CANCELED"),
                            ("DECLARED", "DECLARED"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.FloatField(default=0)),
                (
                    "credited_entity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credited_elec_operations",
                        to="core.entity",
                    ),
                ),
                (
                    "debited_entity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debited_elec_operations",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération électricité",
                "verbose_name_plural": "Opérations électricité",
                "db_table": "tiruert_elec_operations",
            },
        ),
    ]
