# Generated by Django 5.0.6 on 2025-04-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0016_alter_objective_consideration_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="renewable_energy_share",
            field=models.FloatField(default=1),
        ),
    ]
