# Generated by Django 5.0.6 on 2025-04-08 12:38

from django.db import migrations, transaction

from tiruert.services.elec import update_operator_cpo_acquisition_operations


@transaction.atomic
def create_new_elec_operations(apps, schema_editor):
    Entity = apps.get_model("core", "Entity")
    entities = Entity.objects.filter(entity_type="Opérateur", has_elec=True)

    for operator in entities:
        update_operator_cpo_acquisition_operations(operator)


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0017_elecoperation"),
    ]

    operations = [
        migrations.RunPython(create_new_elec_operations, reverse_code=migrations.RunPython.noop),
    ]
