# Generated by Django 5.0.6 on 2025-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0017_operation_renewable_energy_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="durability_period",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                    ("EXPORTATION", "EXPORTATION"),
                    ("DEVALUATION", "DEVALUATION"),
                    ("CUSTOMS_CORRECTION", "CUSTOMS_CORRECTION"),
                    ("TRANSFERT", "TRANSFERT"),
                ],
                max_length=20,
            ),
        ),
    ]
