# Generated by Django 5.0.6 on 2025-05-04 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0018_generate_acquisition_from_cpo_operations"),
        ("tiruert", "0018_operation_durability_period_alter_operation_type"),
    ]

    operations = []
