# Generated by Django 5.0.6 on 2025-05-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0018_operation_durability_period_alter_operation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objective",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REACH", "Objectif à atteindre"),
                    ("CAP", "Plafond à ne pas dépasser"),
                ],
                max_length=255,
            ),
        ),
    ]
