# Generated by Django 5.0.6 on 2025-05-14 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0019_alter_objective_target_type"),
        ("tiruert", "0019_merge_20250504_1915"),
    ]

    operations = []
