# Generated by Django 5.0.6 on 2025-05-27 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0020_merge_20250514_1728"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objective",
            name="consideration_rate",
        ),
    ]
