# Generated by Django 5.0.6 on 2025-05-27 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0021_remove_objective_consideration_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="FossilFuelCategoryConsiderationRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consideration_rate",
                    models.FloatField(blank=True, help_text="saisir 0,50 pour 50%", null=True),
                ),
                ("year", models.IntegerField()),
                (
                    "category_fuel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consideration_rates",
                        to="tiruert.fossilfuelcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consideration Rate for Fossil Fuel Category",
                "verbose_name_plural": "Condideration Rates for Fossil Fuel Categories",
                "db_table": "fossil_fuel_categories_consideration_rates",
            },
        ),
    ]
