# Generated by Django 5.2.2 on 2025-10-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0024_round_operationdetail_volumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="export_recipient",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                    ("EXPORTATION", "EXPORTATION"),
                    ("EXPEDITION", "EXPEDITION"),
                    ("DEVALUATION", "DEVALUATION"),
                    ("CUSTOMS_CORRECTION", "CUSTOMS_CORRECTION"),
                    ("TRANSFERT", "TRANSFERT"),
                ],
                max_length=20,
            ),
        ),
    ]
