# Generated by Django 5.2.2 on 2026-02-18 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_alter_declarationperiod_year"),
        ("tiruert", "0025_operation_export_recipient_alter_operation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiruertDeclarationPeriod",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.declarationperiod",),
        ),
    ]
