# Generated by Django 5.2.2 on 2026-02-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0026_tiruertdeclarationperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="declaration_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
