# Generated by Django 5.2.2 on 2026-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0027_operation_declaration_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("CANCELED", "CANCELED"),
                    ("DECLARED", "DECLARED"),
                    ("CORRECTED", "CORRECTED"),
                    ("VALIDATED", "VALIDATED"),
                    ("DRAFT", "DRAFT"),
                    ("EXPIRED", "EXPIRED"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
