# Generated by Django 5.2.2 on 2026-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0029_alter_operation_type_add_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="objective_sector",
            field=models.CharField(
                blank=True,
                choices=[("ESSENCE", "ESSENCE"), ("GAZOLE", "GAZOLE"), ("CARBURÉACTEUR", "CARBURÉACTEUR")],
                max_length=20,
                null=True,
            ),
        ),
    ]
