# Generated by Django 5.2.2 on 2026-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_change_feedstock_collation"),
        ("tiruert", "0029_alter_operation_type_add_expiration"),
        ("transactions", "0018_alter_site_site_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="macfossilfuel",
            constraint=models.UniqueConstraint(
                fields=("operator", "fuel", "period"),
                name="unique_mac_fossil_fuel_operator_fuel_period",
            ),
        ),
    ]
