# Generated by Django 5.2.2 on 2026-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0030_operation_objective_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="elecoperation",
            name="objective_sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESSENCE", "ESSENCE"),
                    ("GAZOLE", "GAZOLE"),
                    ("CARBURÉACTEUR", "CARBURÉACTEUR"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
