# Generated by Django 5.2.2 on 2026-06-02 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0030_macfossilfuel_unique_mac_fossil_fuel_operator_fuel_period"),
        ("tiruert", "0031_elecoperation_objective_sector"),
    ]

    operations = []
