# Generated by Django 5.2.2 on 2026-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0032_merge_20260602_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objective",
            name="customs_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONV", "Conventionnel"),
                    ("ANN-IX-A", "ANNEXE IX-A"),
                    ("ANN-IX-B", "ANNEXE IX-B"),
                    ("TALLOL", "Tallol"),
                    ("OTHER", "Autre"),
                    ("EP2AM", "EP2AM"),
                    ("CAT3", "Graisses de catégorie 3"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="customs_category",
            field=models.CharField(
                choices=[
                    ("CONV", "Conventionnel"),
                    ("ANN-IX-A", "ANNEXE IX-A"),
                    ("ANN-IX-B", "ANNEXE IX-B"),
                    ("TALLOL", "Tallol"),
                    ("OTHER", "Autre"),
                    ("EP2AM", "EP2AM"),
                    ("CAT3", "Graisses de catégorie 3"),
                ],
                default="CONV",
                max_length=20,
            ),
        ),
    ]
