# Generated by Django 5.2.2 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0037_alter_operationdetail_lot_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="fossilfuelcategory",
            name="pci_kg",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operation",
            name="objective_sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESSENCE", "ESSENCE"),
                    ("GAZOLE", "GAZOLE"),
                    ("CARBURÉACTEUR", "CARBURÉACTEUR"),
                    ("MARITIME", "MARITIME"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="elecoperation",
            name="objective_sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESSENCE", "ESSENCE"),
                    ("GAZOLE", "GAZOLE"),
                    ("CARBURÉACTEUR", "CARBURÉACTEUR"),
                    ("MARITIME", "MARITIME"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
