# Generated by Django 5.2.2 on 2026-08-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0033_alter_objective_customs_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                    ("EXPORTATION", "EXPORTATION"),
                    ("EXPEDITION", "EXPEDITION"),
                    ("DEVALUATION", "DEVALUATION"),
                    ("CUSTOMS_CORRECTION", "CUSTOMS_CORRECTION"),
                    ("TRANSFERT", "TRANSFERT"),
                    ("EXPIRATION", "EXPIRATION"),
                    ("REPORT", "REPORT"),
                ],
                max_length=20,
            ),
        ),
    ]
