# Generated by Django 5.2.2 on 2026-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0033_alter_objective_customs_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="devaluation_type",
            field=models.CharField(
                blank=True,
                choices=[("LOSS", "Perte"), ("DOWNGRADING", "Déclassement"), ("OTHER", "Autre")],
                max_length=20,
                null=True,
            ),
        ),
    ]
