# Generated by Django 5.2.2 on 2026-08-31 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0034_alter_operation_type"),
        ("tiruert", "0034_operation_devaluation_type"),
    ]

    operations = []
