# Generated by Django 5.2.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("tiruert", "0036_alter_operation_type_add_yearly_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationdetail",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiruert_operation",
                to="core.carburelot",
            ),
        ),
    ]
