# Generated by Django 5.2.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0037_alter_operationdetail_lot_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationdetail",
            name="avoided_emissions_tco2",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                    ("EXPORTATION", "EXPORTATION"),
                    ("EXPEDITION", "EXPEDITION"),
                    ("DEVALUATION", "DEVALUATION"),
                    ("CUSTOMS_CORRECTION", "CUSTOMS_CORRECTION"),
                    ("CORRECTION", "CORRECTION"),
                    ("TRANSFERT", "TRANSFERT"),
                    ("EXPIRATION", "EXPIRATION"),
                    ("REPORT", "REPORT"),
                    ("YEARLY_BALANCE", "YEARLY_BALANCE"),
                ],
                max_length=20,
            ),
        ),
    ]
