# Generated by Django 5.2.2 on 2026-09-10 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0036_alter_elecoperation_objective_sector_and_more"),
        ("tiruert", "0037_alter_operationdetail_lot_nullable"),
    ]

    operations = []
