# Generated by Django 5.2.2 on 2026-09-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0038_merge_20260910_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationdetail",
            name="avoided_emissions_tco2",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("CANCELED", "CANCELED"),
                    ("DECLARED", "DECLARED"),
                    ("CORRECTED", "CORRECTED"),
                    ("VALIDATED", "VALIDATED"),
                    ("DRAFT", "DRAFT"),
                    ("AUTO", "AUTO"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                    ("EXPORTATION", "EXPORTATION"),
                    ("EXPEDITION", "EXPEDITION"),
                    ("DEVALUATION", "DEVALUATION"),
                    ("CUSTOMS_CORRECTION", "CUSTOMS_CORRECTION"),
                    ("CORRECTION", "CORRECTION"),
                    ("TRANSFERT", "TRANSFERT"),
                    ("EXPIRATION", "EXPIRATION"),
                    ("REPORT", "REPORT"),
                    ("YEARLY_BALANCE", "YEARLY_BALANCE"),
                ],
                max_length=20,
            ),
        ),
    ]
