# Generated by Django 5.2.2 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0038_merge_20260910_1745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="objective_sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESSENCE", "ESSENCE"),
                    ("GAZOLE", "GAZOLE"),
                    ("CARBURÉACTEUR", "CARBURÉACTEUR"),
                    ("GPL_C", "GPL_C"),
                    ("MARITIME", "MARITIME"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="elecoperation",
            name="objective_sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESSENCE", "ESSENCE"),
                    ("GAZOLE", "GAZOLE"),
                    ("CARBURÉACTEUR", "CARBURÉACTEUR"),
                    ("GPL_C", "GPL_C"),
                    ("MARITIME", "MARITIME"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
