# Generated by Django 5.2.2 on 2026-09-23 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0039_alter_operation_status"),
        ("tiruert", "0039_maritime_fossil_fuels"),
    ]

    operations = []
