# Generated by Django 5.2.2 on 2026-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiruert", "0039_maritime_fossil_fuels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fossilfuelcategory",
            name="pci_litre",
        ),
        migrations.AddField(
            model_name="fossilfuel",
            name="pci_kg",
            field=models.FloatField(default=0.0),
        ),
    ]
