# Generated by Django 5.2.2 on 2026-09-28 15:05

import django.db.models.deletion
from django.db import migrations, models


def delete_yearly_balance_operations(apps, schema_editor):
    OperationDetail = apps.get_model("tiruert", "OperationDetail")
    Operation = apps.get_model("tiruert", "Operation")

    OperationDetail.objects.filter(operation__type="YEARLY_BALANCE").delete()
    Operation.objects.filter(type="YEARLY_BALANCE").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_alter_externaladminrights_right"),
        ("tiruert", "0040_merge_20260923_1624"),
    ]

    operations = [
        migrations.RunPython(delete_yearly_balance_operations, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("CANCELED", "CANCELED"),
                    ("DECLARED", "DECLARED"),
                    ("CORRECTED", "CORRECTED"),
                    ("VALIDATED", "VALIDATED"),
                    ("DRAFT", "DRAFT"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCORPORATION", "INCORPORATION"),
                    ("CESSION", "CESSION"),
                    ("TENEUR", "TENEUR"),
                    ("LIVRAISON_DIRECTE", "LIVRAISON_DIRECTE"),
                    ("MAC_BIO", "MAC_BIO"),
                    ("EXPORTATION", "EXPORTATION"),
                    ("EXPEDITION", "EXPEDITION"),
                    ("DEVALUATION", "DEVALUATION"),
                    ("CUSTOMS_CORRECTION", "CUSTOMS_CORRECTION"),
                    ("TRANSFERT", "TRANSFERT"),
                    ("EXPIRATION", "EXPIRATION"),
                    ("REPORT", "REPORT"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="operationdetail",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tiruert_operation", to="core.carburelot"
            ),
        ),
    ]
