class SafTicketAssignError:
    MALFORMED_PARAMS = "MALFORMED_PARAMS"
    VOLUME_TOO_BIG = "VOLUME_TOO_BIG"
    TICKET_CREATION_FAILED = "TICKET_CREATION_FAILED"
    TICKET_SOURCE_NOT_FOUND = "TICKET_SOURCE_NOT_FOUND"
    ASSIGNMENT_BEFORE_DELIVERY = "ASSIGNMENT_BEFORE_DELIVERY"
