# Generated by Django 5.2.2 on 2025-07-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneEntityConfigAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "tariff_reference",
                    models.CharField(choices=[(2011, 2011), (2021, 2021), (2022, 2022), (2023, 2023)], max_length=28),
                ),
                (
                    "entity",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="core.entity"),
                ),
                ("installation_category", models.CharField(max_length=128)),
                ("cmax", models.FloatField()),
                ("cmax_annualized", models.BooleanField()),
                ("cmax_annualized_value", models.FloatField()),
                ("pap_contracted", models.FloatField()),
                ("signature_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("general_conditions_file", models.FileField(blank=True, null=True, upload_to="")),
                ("specific_conditions_file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "buyer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="buyer", to="core.entity"),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Contrat d'achat",
                "db_table": "biomethane_entity_config_agreement",
            },
        ),
        migrations.CreateModel(
            name="BiomethaneEntityConfigAmendment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("signature_date", models.DateField()),
                ("effective_date", models.DateField()),
                (
                    "amendment_object",
                    models.CharField(
                        choices=[
                            ("CMAX_PAP_UPDATE", "CMAX_PAP_UPDATE"),
                            ("EFFECTIVE_DATE", "EFFECTIVE_DATE"),
                            ("CMAX_ANNUALIZATION", "CMAX_ANNUALIZATION"),
                            ("INPUT_BONUS_UPDATE", "INPUT_BONUS_UPDATE"),
                            ("L_INDEXATION_UPDATE", "L_INDEXATION_UPDATE"),
                            ("PRODUCER_BUYER_INFO_CHANGE", "PRODUCER_BUYER_INFO_CHANGE"),
                            ("ENERGY_ENVIRONMENTAL_EFFICIENCY_UPDATE", "ENERGY_ENVIRONMENTAL_EFFICIENCY_UPDATE"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=64,
                    ),
                ),
                ("amendment_details", models.TextField(blank=True, null=True)),
                ("amendment_file", models.FileField(upload_to="")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="biomethane.biomethaneentityconfigagreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Avenant",
                "db_table": "biomethane_entity_config_amendment",
            },
        ),
    ]
