# Generated by Django 5.2.2 on 2025-07-31 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0001_initial"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BiomethaneEntityConfigAgreement",
            new_name="BiomethaneEntityConfigContract",
        ),
        migrations.AlterModelTable(
            name="biomethaneentityconfigcontract",
            table="biomethane_entity_config_contract",
        ),
    ]
