# Generated by Django 5.2.2 on 2025-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0002_rename_biomethaneentityconfigagreement_biomethaneentityconfigcontract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="cmax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="cmax_annualized",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="cmax_annualized_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="pap_contracted",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="tariff_reference",
            field=models.CharField(choices=[(2011, 2011), (2020, 2020), (2021, 2021), (2023, 2023)], max_length=28),
        ),
    ]
