# Generated by Django 5.2.2 on 2025-08-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0003_alter_biomethaneentityconfigcontract_cmax_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="installation_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTALLATION_CATEGORY_1", "INSTALLATION_CATEGORY_1"),
                    ("INSTALLATION_CATEGORY_2", "INSTALLATION_CATEGORY_2"),
                    ("INSTALLATION_CATEGORY_3", "INSTALLATION_CATEGORY_3"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="tariff_reference",
            field=models.CharField(
                choices=[("2011", "2011"), ("2020", "2020"), ("2021", "2021"), ("2023", "2023")], max_length=28
            ),
        ),
    ]
