# Generated by Django 5.2.2 on 2025-08-08 07:30

import storages.backends.s3
from django.db import migrations, models

import biomethane.models.biomethane_contract
import biomethane.models.biomethane_contract_amendment


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0004_alter_biomethaneentityconfigcontract_installation_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneentityconfigamendment",
            name="amendment_file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(default_acl="private", file_overwrite=True, querystring_auth=True),
                upload_to=biomethane.models.biomethane_contract_amendment.rename_amendment_file,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneentityconfigamendment",
            name="amendment_object",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="general_conditions_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(default_acl="private", file_overwrite=True, querystring_auth=True),
                upload_to=biomethane.models.biomethane_contract.rename_conditions_file,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneentityconfigcontract",
            name="specific_conditions_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(default_acl="private", file_overwrite=True, querystring_auth=True),
                upload_to=biomethane.models.biomethane_contract.rename_conditions_file,
            ),
        ),
    ]
