# Generated by Django 5.2.2 on 2025-08-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0005_alter_biomethaneentityconfigamendment_amendment_file_and_more"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneInjectionSite",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_identification_number", models.CharField(max_length=32, unique=True)),
                ("is_shared_injection_site", models.BooleanField(default=False)),
                ("meter_number", models.CharField(blank=True, max_length=32, null=True)),
                ("is_different_from_production_site", models.BooleanField(default=False)),
                ("company_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        choices=[("TRANSPORT", "Transport"), ("DISTRIBUTION", "Dristribution")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("network_manager_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomethane_injection_site",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Site d'injection",
                "db_table": "biomethane_injection_site",
            },
        ),
    ]
