# Generated by Django 5.2.2 on 2025-08-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "biomethane",
            "0005_alter_biomethaneentityconfigamendment_amendment_file_and_more",
        ),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BiomethaneEntityConfigContract",
            new_name="BiomethaneContract",
        ),
        migrations.RenameModel(
            old_name="BiomethaneEntityConfigAmendment",
            new_name="BiomethaneContractAmendment",
        ),
        migrations.CreateModel(
            name="BiomethaneDigestateStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("capacity", models.FloatField()),
                ("has_cover", models.BooleanField(default=False)),
                ("has_biogas_recovery", models.BooleanField(default=False)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomethane_digestate_storage",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiomethaneProductionUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=128)),
                ("siret_number", models.CharField(max_length=16)),
                ("company_address", models.CharField(max_length=256)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("AGRICULTURAL_AUTONOMOUS", "Agricole autonome"),
                            ("AGRICULTURAL_TERRITORIAL", "Agricole territorial"),
                            ("INDUSTRIAL_TERRITORIAL", "Industriel territorial"),
                            (
                                "HOUSEHOLD_WASTE_BIOWASTE",
                                "Déchets ménagers et biodéchets",
                            ),
                            ("ISDND", "ISDND"),
                        ],
                        max_length=32,
                    ),
                ),
                ("has_sanitary_approval", models.BooleanField(default=False)),
                ("sanitary_approval_number", models.CharField(max_length=32)),
                ("has_hygienization_exemption", models.BooleanField(default=False)),
                (
                    "hygienization_exemption_type",
                    models.CharField(
                        choices=[("TOTAL", "Totale"), ("PARTIAL", "Partielle")],
                        max_length=16,
                    ),
                ),
                ("icpe_number", models.CharField(max_length=32)),
                (
                    "icpe_regime",
                    models.CharField(
                        choices=[
                            ("AUTHORIZATION", "Autorisation"),
                            ("REGISTRATION", "Enregistrement"),
                            (
                                "DECLARATION_PERIODIC_CONTROLS",
                                "Déclaration (avec contrôles périodiques)",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("LIQUID_PROCESS", "Voie liquide"),
                            ("DRY_PROCESS", "Voie sèche"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "methanization_process",
                    models.CharField(
                        choices=[
                            (
                                "CONTINUOUS_INFINITELY_MIXED",
                                "Continu (infiniment mélangé)",
                            ),
                            ("PLUG_FLOW_SEMI_CONTINUOUS", "En piston (semi-continu)"),
                            ("BATCH_SILOS", "En silos (batch)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("production_efficiency", models.FloatField()),
                ("has_biogas_production_flowmeter", models.BooleanField(default=False)),
                ("has_purification_flowmeter", models.BooleanField(default=False)),
                ("has_flaring_flowmeter", models.BooleanField(default=False)),
                ("has_heating_flowmeter", models.BooleanField(default=False)),
                (
                    "has_purification_electrical_meter",
                    models.BooleanField(default=False),
                ),
                ("has_global_electrical_meter", models.BooleanField(default=False)),
                ("has_hygienization_unit", models.BooleanField(default=False)),
                ("has_co2_valorization_process", models.BooleanField(default=False)),
                ("has_digestate_phase_separation", models.BooleanField(default=False)),
                ("raw_digestate_treatment_steps", models.CharField(max_length=128)),
                ("liquid_phase_treatment_steps", models.CharField(max_length=128)),
                ("solid_phase_treatment_steps", models.CharField(max_length=128)),
                (
                    "digestate_valorization_method",
                    models.CharField(
                        choices=[
                            ("SPREADING", "Épandage"),
                            ("COMPOSTING", "Compostage"),
                            (
                                "INCINERATION_LANDFILLING",
                                "Incinération / Enfouissement",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "spreading_management",
                    models.CharField(
                        choices=[
                            ("DIRECT_SPREADING", "Épandage direct"),
                            ("SPREADING_VIA_PROVIDER", "Épandage via un prestataire"),
                            ("TRANSFER", "Cession"),
                            ("SALE", "Vente"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "digestate_sale_type",
                    models.CharField(
                        choices=[
                            ("DIG_AGRI_SPECIFICATIONS", "Cahier de charges DIG Agri"),
                            ("HOMOLOGATION", "Homologation"),
                            ("STANDARDIZED_PRODUCT", "Produit normé"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomethane_production_units",
                        to="core.entity",
                    ),
                ),
            ],
        ),
    ]
