# Generated by Django 5.2.2 on 2025-08-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "biomethane",
            "0006_rename_biomethaneentityconfigcontract_biomethanecontract_and_more",
        ),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="producer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biomethane_production_unit",
                to="core.entity",
            ),
        ),
    ]
