# Generated by Django 5.2.2 on 2025-08-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0006_rename_biomethaneentityconfigcontract_biomethanecontract_and_more"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biomethanedigestatestorage",
            options={"verbose_name": "Stockage de Digestat"},
        ),
        migrations.AlterModelOptions(
            name="biomethaneproductionunit",
            options={"verbose_name": "Unité de Production de Biométhane"},
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="digestate_valorization_method",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_biogas_production_flowmeter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_flaring_flowmeter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_global_electrical_meter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_heating_flowmeter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_purification_electrical_meter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_purification_flowmeter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="spreading_management",
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="digestate_valorization_methods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="installed_meters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="spreading_management_methods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="company_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="digestate_sale_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIG_AGRI_SPECIFICATIONS", "Cahier de charges DIG Agri"),
                    ("HOMOLOGATION", "Homologation"),
                    ("STANDARDIZED_PRODUCT", "Produit normé"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="hygienization_exemption_type",
            field=models.CharField(
                blank=True, choices=[("TOTAL", "Totale"), ("PARTIAL", "Partielle")], max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="icpe_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="icpe_regime",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTHORIZATION", "Autorisation"),
                    ("REGISTRATION", "Enregistrement"),
                    ("DECLARATION_PERIODIC_CONTROLS", "Déclaration (avec contrôles périodiques)"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="liquid_phase_treatment_steps",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="methanization_process",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTINUOUS_INFINITELY_MIXED", "Continu (infiniment mélangé)"),
                    ("PLUG_FLOW_SEMI_CONTINUOUS", "En piston (semi-continu)"),
                    ("BATCH_SILOS", "En silos (batch)"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="process_type",
            field=models.CharField(
                blank=True,
                choices=[("LIQUID_PROCESS", "Voie liquide"), ("DRY_PROCESS", "Voie sèche")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="producer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="biomethane_production_unit", to="core.entity"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="production_efficiency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="raw_digestate_treatment_steps",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="sanitary_approval_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="siret_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="solid_phase_treatment_steps",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="unit_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGRICULTURAL_AUTONOMOUS", "Agricole autonome"),
                    ("AGRICULTURAL_TERRITORIAL", "Agricole territorial"),
                    ("INDUSTRIAL_TERRITORIAL", "Industriel territorial"),
                    ("HOUSEHOLD_WASTE_BIOWASTE", "Déchets ménagers et biodéchets"),
                    ("ISDND", "ISDND"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterModelTable(
            name="biomethanedigestatestorage",
            table="biomethane_digestate_storage",
        ),
        migrations.AlterModelTable(
            name="biomethaneproductionunit",
            table="biomethane_production_unit",
        ),
        migrations.CreateModel(
            name="BiomethaneInjectionSite",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_identification_number", models.CharField(max_length=32, unique=True)),
                ("is_shared_injection_site", models.BooleanField(default=False)),
                ("meter_number", models.CharField(blank=True, max_length=32, null=True)),
                ("is_different_from_production_site", models.BooleanField(default=False)),
                ("company_address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        choices=[("TRANSPORT", "Transport"), ("DISTRIBUTION", "Dristribution")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("network_manager_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomethane_injection_site",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Site d'injection",
                "db_table": "biomethane_injection_site",
            },
        ),
    ]
