# Generated by Django 5.2.2 on 2025-08-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0006_biomethaneinjectionsite"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BiomethaneEntityConfigContract",
            new_name="BiomethaneContract",
        ),
        migrations.RenameModel(
            old_name="BiomethaneEntityConfigAmendment",
            new_name="BiomethaneContractAmendment",
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="company_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
