# Generated by Django 5.2.2 on 2025-08-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0007_rename_biomethaneentityconfigcontract_biomethanecontract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="company_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
