# Generated by Django 5.2.2 on 2025-08-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0007_alter_biomethaneproductionunit_producer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="company_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="digestate_sale_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIG_AGRI_SPECIFICATIONS", "Cahier de charges DIG Agri"),
                    ("HOMOLOGATION", "Homologation"),
                    ("STANDARDIZED_PRODUCT", "Produit normé"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="digestate_valorization_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SPREADING", "Épandage"),
                    ("COMPOSTING", "Compostage"),
                    ("INCINERATION_LANDFILLING", "Incinération / Enfouissement"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="hygienization_exemption_type",
            field=models.CharField(
                blank=True,
                choices=[("TOTAL", "Totale"), ("PARTIAL", "Partielle")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="icpe_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="icpe_regime",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTHORIZATION", "Autorisation"),
                    ("REGISTRATION", "Enregistrement"),
                    (
                        "DECLARATION_PERIODIC_CONTROLS",
                        "Déclaration (avec contrôles périodiques)",
                    ),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="liquid_phase_treatment_steps",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="methanization_process",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTINUOUS_INFINITELY_MIXED", "Continu (infiniment mélangé)"),
                    ("PLUG_FLOW_SEMI_CONTINUOUS", "En piston (semi-continu)"),
                    ("BATCH_SILOS", "En silos (batch)"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="process_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIQUID_PROCESS", "Voie liquide"),
                    ("DRY_PROCESS", "Voie sèche"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="production_efficiency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="raw_digestate_treatment_steps",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="sanitary_approval_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="siret_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="solid_phase_treatment_steps",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="spreading_management",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT_SPREADING", "Épandage direct"),
                    ("SPREADING_VIA_PROVIDER", "Épandage via un prestataire"),
                    ("TRANSFER", "Cession"),
                    ("SALE", "Vente"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGRICULTURAL_AUTONOMOUS", "Agricole autonome"),
                    ("AGRICULTURAL_TERRITORIAL", "Agricole territorial"),
                    ("INDUSTRIAL_TERRITORIAL", "Industriel territorial"),
                    ("HOUSEHOLD_WASTE_BIOWASTE", "Déchets ménagers et biodéchets"),
                    ("ISDND", "ISDND"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
