# Generated by Django 5.2.2 on 2025-08-25 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0007_alter_biomethanedigestatestorage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biomethanecontractamendment",
            options={"verbose_name": "Biométhane - Avenant au contrat"},
        ),
        migrations.AlterModelTable(
            name="biomethanecontract",
            table="biomethane_contract",
        ),
        migrations.AlterModelTable(
            name="biomethanecontractamendment",
            table="biomethane_contract_amendment",
        ),
    ]
