# Generated by Django 5.2.2 on 2025-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0008_alter_biomethaneproductionunit_company_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="digestate_valorization_method",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_biogas_production_flowmeter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_flaring_flowmeter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_global_electrical_meter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_heating_flowmeter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_purification_electrical_meter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="has_purification_flowmeter",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="spreading_management",
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="digestate_valorization_methods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="installed_meters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="spreading_management_methods",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
