# Generated by Django 5.2.2 on 2025-09-02 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0009_biomethanedigestate_biomethanedigestatespreading"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biomethanecontract",
            old_name="entity",
            new_name="producer",
        ),
        migrations.RenameField(
            model_name="biomethaneinjectionsite",
            old_name="entity",
            new_name="producer",
        ),
    ]
