# Generated by Django 5.2.2 on 2025-08-13 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "biomethane",
            "0009_remove_biomethaneproductionunit_digestate_valorization_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biomethanedigestatestorage",
            options={"verbose_name": "Stockage de Digestat"},
        ),
        migrations.AlterModelOptions(
            name="biomethaneproductionunit",
            options={"verbose_name": "Unité de Production de Biométhane"},
        ),
        migrations.AlterModelTable(
            name="biomethanedigestatestorage",
            table="biomethane_digestate_storage",
        ),
        migrations.AlterModelTable(
            name="biomethaneproductionunit",
            table="biomethane_production_unit",
        ),
    ]
