# Generated by Django 5.2.2 on 2025-09-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0009_biomethanedigestate_biomethanedigestatespreading"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneEnergy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("VALIDATED", "VALIDATED")], default="PENDING", max_length=28
                    ),
                ),
                ("injected_biomethane_gwh_pcs_per_year", models.FloatField(blank=True, null=True)),
                ("injected_biomethane_nm3_per_year", models.FloatField(blank=True, null=True)),
                ("injected_biomethane_ch4_rate_percent", models.FloatField(blank=True, null=True)),
                ("injected_biomethane_pcs_kwh_per_nm3", models.FloatField(blank=True, null=True)),
                ("operating_hours", models.FloatField(blank=True, null=True)),
                ("produced_biogas_nm3_per_year", models.FloatField(blank=True, null=True)),
                ("flared_biogas_nm3_per_year", models.FloatField(blank=True, null=True)),
                ("flaring_operating_hours", models.FloatField(blank=True, null=True)),
                ("attest_no_fossil_for_digester_heating_and_purification", models.BooleanField(default=False)),
                ("energy_used_for_digester_heating", models.CharField(blank=True, max_length=255, null=True)),
                ("fossil_details_for_digester_heating", models.TextField(blank=True, null=True)),
                ("attest_no_fossil_for_installation_needs", models.BooleanField(default=False)),
                ("energy_used_for_installation_needs", models.CharField(blank=True, max_length=255, null=True)),
                ("fossil_details_for_installation_needs", models.TextField(blank=True, null=True)),
                ("purified_biogas_quantity_nm3", models.FloatField(blank=True, null=True)),
                ("purification_electric_consumption_kwe", models.FloatField(blank=True, null=True)),
                ("self_consumed_biogas_nm3", models.FloatField(blank=True, null=True)),
                ("total_unit_electric_consumption_kwe", models.FloatField(blank=True, null=True)),
                ("butane_or_propane_addition", models.FloatField(blank=True, null=True)),
                ("fossil_fuel_consumed_kwh", models.FloatField(blank=True, null=True)),
                ("has_opposition_or_complaints_acceptability", models.BooleanField(default=False)),
                ("estimated_work_days_acceptability", models.IntegerField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="biomethane_energies", to="core.entity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Énergie",
                "db_table": "biomethane_energy",
            },
        ),
    ]
