# Generated by Django 5.2.2 on 2025-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0010_alter_biomethanedigestatestorage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="unit_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
