# Generated by Django 5.2.2 on 2025-08-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0010_alter_biomethanedigestatestorage_options_and_more"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneDigestate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField()),
                ("status", models.CharField(choices=[("PENDING", "PENDING"), ("VALIDATED", "VALIDATED")], max_length=28)),
                ("raw_digestate_tonnage_produced", models.FloatField(blank=True, null=True)),
                ("raw_digestate_dry_matter_rate", models.FloatField(blank=True, null=True)),
                ("solid_digestate_tonnage", models.FloatField(blank=True, null=True)),
                ("liquid_digestate_quantity", models.FloatField(blank=True, null=True)),
                ("average_spreading_valorization_distance", models.FloatField(blank=True, null=True)),
                ("composting_on_site", models.BooleanField(default=False)),
                ("composting_external_platform", models.BooleanField(default=False)),
                ("external_platform_name", models.CharField(blank=True, max_length=255, null=True)),
                ("external_platform_digestate_volume", models.FloatField(blank=True, null=True)),
                ("external_platform_department", models.CharField(blank=True, max_length=3, null=True)),
                ("external_platform_municipality", models.CharField(blank=True, max_length=255, null=True)),
                ("on_site_composted_digestate_volume", models.FloatField(blank=True, null=True)),
                ("annual_eliminated_volume", models.FloatField(blank=True, null=True)),
                ("incinerator_landfill_center_name", models.CharField(blank=True, max_length=255, null=True)),
                ("wwtp_materials_to_incineration", models.FloatField(blank=True, null=True)),
                ("acquiring_companies", models.TextField(blank=True, null=True)),
                ("sold_volume", models.FloatField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="biomethane_digestates", to="core.entity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Digestat",
                "db_table": "biomethane_digestate",
            },
        ),
        migrations.CreateModel(
            name="BiomethaneDigestateSpreading",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("spreading_department", models.CharField(max_length=3)),
                ("spread_quantity", models.FloatField()),
                ("spread_parcels_area", models.FloatField()),
                (
                    "digestate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spreading",
                        to="biomethane.biomethanedigestate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Données d'épandage du digestat",
                "db_table": "biomethane_digestate_spreading",
            },
        ),
    ]
