# Generated by Django 5.2.2 on 2025-09-02 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0010_biomethaneenergy"),
        ("biomethane", "0010_rename_entity_biomethanecontract_producer_and_more"),
    ]

    operations = []
