# Generated by Django 5.2.2 on 2025-08-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0011_biomethanedigestate_biomethanedigestatespreading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanedigestatespreading",
            name="digestate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="spreadings", to="biomethane.biomethanedigestate"
            ),
        ),
    ]
