# Generated by Django 5.2.2 on 2025-09-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0011_merge_20250902_1627"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanecontract",
            name="producer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="biomethane_contract", to="core.entity"
            ),
        ),
    ]
