# Generated by Django 5.2.2 on 2025-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0012_alter_biomethanecontract_producer"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethaneenergy",
            name="has_injection_difficulties_due_to_network_saturation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="biomethaneenergy",
            name="has_malfunctions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="biomethaneenergy",
            name="injection_impossibility_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biomethaneenergy",
            name="malfunction_cumulative_duration_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biomethaneenergy",
            name="malfunction_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biomethaneenergy",
            name="malfunction_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONCEPTION", "Conception"),
                    ("MAINTENANCE", "Entretien/Maintenance"),
                    ("BIOLOGICAL", "Biologique"),
                    ("ACCIDENT", "Accident deversement"),
                    ("PURIFIER", "Épurateur"),
                    ("INJECTION_POST", "Poste d'injection (autre que problématiques de saturation des réseaux)"),
                    ("INPUTS", "Intrants"),
                    ("OTHER", "Autres (à préciser)"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
