# Generated by Django 5.2.2 on 2025-09-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0013_biomethaneenergy_has_injection_difficulties_due_to_network_saturation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneEnergyMonthlyReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.IntegerField()),
                ("injected_volume_nm3", models.FloatField(default=0)),
                ("average_monthly_flow_nm3_per_hour", models.FloatField(default=0)),
                ("injection_hours", models.FloatField(default=0)),
                (
                    "energy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to="biomethane.biomethaneenergy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Énergie - Relevés mensuels Biométhane injecté",
                "db_table": "biomethane_energy_monthly_report",
            },
        ),
    ]
