# Generated by Django 5.2.2 on 2025-09-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0014_biomethaneenergymonthlyreport"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanecontract",
            name="buyer",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="buyer", to="core.entity"
            ),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="tariff_reference",
            field=models.CharField(
                blank=True,
                choices=[("2011", "2011"), ("2020", "2020"), ("2021", "2021"), ("2023", "2023")],
                max_length=28,
                null=True,
            ),
        ),
    ]
