# Generated by Django 5.2.2 on 2025-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0015_alter_biomethanecontract_buyer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="city",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
