# Generated by Django 5.2.2 on 2025-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0016_biomethaneproductionunit_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethanecontract",
            name="tracked_amendment_types",
            field=models.JSONField(default=list),
        ),
    ]
