# Generated by Django 5.2.2 on 2025-09-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0017_biomethanecontract_tracked_amendment_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="department",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
