# Generated by Django 5.2.2 on 2025-09-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0018_biomethaneproductionunit_department"),
        ("core", "0047_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biomethanecontract",
            options={"verbose_name": "Biométhane - Contrat d'achat", "verbose_name_plural": "Biométhane - Contrats d'achat"},
        ),
        migrations.AlterModelOptions(
            name="biomethanecontractamendment",
            options={
                "verbose_name": "Biométhane - Avenant au contrat",
                "verbose_name_plural": "Biométhane - Avenants au contrat",
            },
        ),
        migrations.AlterModelOptions(
            name="biomethanedigestate",
            options={"verbose_name": "Biométhane - Digestat", "verbose_name_plural": "Biométhane - Digestats"},
        ),
        migrations.AlterModelOptions(
            name="biomethanedigestatespreading",
            options={
                "verbose_name": "Biométhane - Données d'épandage du digestat",
                "verbose_name_plural": "Biométhane - Données d'épandage du digestat",
            },
        ),
        migrations.AlterModelOptions(
            name="biomethanedigestatestorage",
            options={
                "verbose_name": "Biométhane - Stockage de Digestat",
                "verbose_name_plural": "Biométhane - Stockages de Digestat",
            },
        ),
        migrations.AlterModelOptions(
            name="biomethaneinjectionsite",
            options={
                "verbose_name": "Biométhane - Site d'injection",
                "verbose_name_plural": "Biométhane - Sites d'injection",
            },
        ),
        migrations.AlterModelOptions(
            name="biomethaneproductionunit",
            options={
                "verbose_name": "Biométhane - Unité de Production",
                "verbose_name_plural": "Biométhane - Unités de Production",
            },
        ),
        migrations.AlterUniqueTogether(
            name="biomethanedigestate",
            unique_together={("producer", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="biomethaneenergy",
            unique_together={("producer", "year")},
        ),
        migrations.CreateModel(
            name="BiomethaneSupplyPlan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(verbose_name="Année")),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="biomethane_supply_plans", to="core.entity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Plan d'approvisionnement",
                "verbose_name_plural": "Biométhane - Plans d'approvisionnement",
                "db_table": "biomethane_supply_plan",
                "unique_together": {("producer", "year")},
            },
        ),
        migrations.CreateModel(
            name="BiomethaneSupplyInput",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("INTERNAL", "Interne"), ("EXTERNAL", "Externe")], max_length=10)),
                (
                    "crop_type",
                    models.CharField(choices=[("MAIN", "Principale"), ("INTERMEDIATE", "Intermédiaire")], max_length=15),
                ),
                (
                    "input_category",
                    models.CharField(
                        choices=[
                            ("LIVESTOCK_EFFLUENTS", "Effluents d'élevage"),
                            ("PRIMARY_CROPS", "Culture principale"),
                            ("INTERMEDIATE_CROPS", "Culture intermédiaire"),
                            ("CIVE", "CIVE"),
                            ("IAA_WASTE_RESIDUES", "Déchets/Résidus d'IAA"),
                        ],
                        max_length=30,
                    ),
                ),
                ("input_type", models.CharField(max_length=100)),
                ("material_unit", models.CharField(choices=[("DRY", "Sèche"), ("WET", "Brute")], max_length=5)),
                ("dry_matter_ratio_percent", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField()),
                ("origin_department", models.CharField(max_length=3)),
                ("average_weighted_distance_km", models.FloatField(blank=True, null=True)),
                ("maximum_distance_km", models.FloatField(blank=True, null=True)),
                (
                    "origin_country",
                    models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.pays"),
                ),
                (
                    "supply_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_inputs",
                        to="biomethane.biomethanesupplyplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Intrant d'approvisionnement",
                "verbose_name_plural": "Biométhane - Intrants d'approvisionnement",
                "db_table": "biomethane_supply_input",
                "ordering": ["supply_plan", "id"],
            },
        ),
    ]
