# Generated by Django 5.2.2 on 2025-10-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0019_alter_biomethanecontract_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="origin_department",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
