# Generated by Django 5.2.2 on 2025-10-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0020_alter_biomethanesupplyinput_origin_department"),
        ("core", "0048_alter_externaladminrights_right"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneAnnualDeclaration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("DECLARED", "DECLARED")], default="PENDING", max_length=20
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="biomethane_declarations", to="core.entity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Biométhane - Déclaration annuelle",
                "verbose_name_plural": "Biométhane - Déclarations annuelles",
                "db_table": "biomethane_annual_declaration",
                "unique_together": {("producer", "year")},
            },
        ),
    ]
