# Generated by Django 5.2.2 on 2025-10-20 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0021_biomethaneannualdeclaration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biomethanedigestate",
            name="status",
        ),
        migrations.RemoveField(
            model_name="biomethaneenergy",
            name="status",
        ),
    ]
