# Generated by Django 5.2.2 on 2025-10-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0022_remove_biomethanedigestate_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneannualdeclaration",
            name="status",
            field=models.CharField(
                choices=[("IN_PROGRESS", "IN_PROGRESS"), ("DECLARED", "DECLARED")], default="IN_PROGRESS", max_length=20
            ),
        ),
    ]
