# Generated by Django 5.2.2 on 2025-11-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0023_alter_biomethaneannualdeclaration_status"),
    ]

    operations = [
        # Remove old CharField
        migrations.RemoveField(
            model_name="biomethaneenergy",
            name="malfunction_types",
        ),
        # Add new JSONField
        migrations.AddField(
            model_name="biomethaneenergy",
            name="malfunction_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
