# Generated by Django 5.2.2 on 2025-10-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0023_alter_biomethaneannualdeclaration_status"),
        ("core", "0049_merge_20251023_2042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="department",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.department"
            ),
        ),
    ]
