# Generated by Django 5.2.2 on 2025-11-05 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0024_alter_biomethaneenergy_malfunction_types"),
        ("biomethane", "0024_alter_biomethaneproductionunit_department"),
    ]

    operations = []
