# Generated by Django 5.2.2 on 2025-12-17 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0025_merge_20251105_1415"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biomethaneannualdeclaration",
            options={"verbose_name": "Déclaration annuelle", "verbose_name_plural": "Déclarations annuelles"},
        ),
        migrations.AlterModelOptions(
            name="biomethanecontract",
            options={"verbose_name": "Contrat d'achat", "verbose_name_plural": "Contrats d'achat"},
        ),
        migrations.AlterModelOptions(
            name="biomethanecontractamendment",
            options={"verbose_name": "Avenant au contrat", "verbose_name_plural": "Avenants au contrat"},
        ),
        migrations.AlterModelOptions(
            name="biomethanedigestate",
            options={"verbose_name": "Digestat", "verbose_name_plural": "Digestats"},
        ),
        migrations.AlterModelOptions(
            name="biomethanedigestatespreading",
            options={
                "verbose_name": "Données d'épandage du digestat",
                "verbose_name_plural": "Données d'épandage du digestat",
            },
        ),
        migrations.AlterModelOptions(
            name="biomethanedigestatestorage",
            options={"verbose_name": "Stockage de Digestat", "verbose_name_plural": "Stockages de Digestat"},
        ),
        migrations.AlterModelOptions(
            name="biomethaneenergy",
            options={"verbose_name": "Énergie"},
        ),
        migrations.AlterModelOptions(
            name="biomethaneenergymonthlyreport",
            options={"verbose_name": "Énergie - Relevés mensuels Biométhane injecté"},
        ),
        migrations.AlterModelOptions(
            name="biomethaneinjectionsite",
            options={"verbose_name": "Site d'injection", "verbose_name_plural": "Sites d'injection"},
        ),
        migrations.AlterModelOptions(
            name="biomethaneproductionunit",
            options={"verbose_name": "Unité de Production", "verbose_name_plural": "Unités de Production"},
        ),
        migrations.AlterModelOptions(
            name="biomethanesupplyinput",
            options={
                "ordering": ["supply_plan", "id"],
                "verbose_name": "Intrant d'approvisionnement",
                "verbose_name_plural": "Intrants d'approvisionnement",
            },
        ),
        migrations.AlterModelOptions(
            name="biomethanesupplyplan",
            options={"verbose_name": "Plan d'approvisionnement", "verbose_name_plural": "Plans d'approvisionnement"},
        ),
    ]
