# Generated by Django 5.2.2 on 2026-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0026_alter_biomethaneannualdeclaration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethaneannualdeclaration",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
