# Generated by Django 5.2.2 on 2026-01-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0026_alter_biomethaneannualdeclaration_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanecontract",
            name="cmax_annualized",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
