# Generated by Django 5.2.2 on 2026-01-13 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0027_alter_biomethanecontract_cmax_annualized"),
        ("biomethane", "0027_biomethaneannualdeclaration_is_open"),
    ]

    operations = []
