# Generated by Django 5.2.2 on 2026-01-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0027_alter_biomethanecontract_cmax_annualized"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethanecontract",
            name="complementary_aid_organisms",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="biomethanecontract",
            name="complementary_aid_other_organism_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="biomethanecontract",
            name="has_complementary_investment_aid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
