# Generated by Django 5.2.2 on 2026-01-14 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0028_biomethanecontract_complementary_aid_organisms_and_more"),
        ("biomethane", "0028_merge_20260113_1058"),
    ]

    operations = []
