# Generated by Django 5.2.2 on 2026-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0028_merge_20260113_1058"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneDeclarationPeriod",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Période de déclaration",
                "verbose_name_plural": "Périodes de déclaration",
                "db_table": "biomethane_declaration_period",
            },
        ),
    ]
