# Generated by Django 5.2.2 on 2026-01-14 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0029_merge_20260114_1141"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biomethaneenergymonthlyreport",
            name="injection_hours",
        ),
    ]
