# Generated by Django 5.2.2 on 2026-01-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0030_remove_biomethaneenergymonthlyreport_injection_hours"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biomethaneenergy",
            old_name="attest_no_fossil_for_digester_heating_and_purification",
            new_name="attest_no_fossil_for_energy",
        ),
        migrations.RenameField(
            model_name="biomethaneenergy",
            old_name="fossil_details_for_digester_heating",
            new_name="energy_details",
        ),
        migrations.RemoveField(
            model_name="biomethaneenergy",
            name="attest_no_fossil_for_installation_needs",
        ),
        migrations.RemoveField(
            model_name="biomethaneenergy",
            name="energy_used_for_digester_heating",
        ),
        migrations.RemoveField(
            model_name="biomethaneenergy",
            name="energy_used_for_installation_needs",
        ),
        migrations.RemoveField(
            model_name="biomethaneenergy",
            name="fossil_details_for_installation_needs",
        ),
        migrations.AddField(
            model_name="biomethaneenergy",
            name="energy_types",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
