# Generated by Django 5.2.2 on 2026-01-15 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0029_biomethanedeclarationperiod"),
        (
            "biomethane",
            "0031_rename_attest_no_fossil_for_digester_heating_and_purification_biomethaneenergy_attest_no_fossil_for_",
        ),
    ]

    operations = []
