# Generated by Django 5.2.2 on 2026-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0033_alter_biomethaneenergy_butane_or_propane_addition"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="insee_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
