# Generated by Django 5.2.2 on 2026-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0034_biomethaneproductionunit_insee_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethaneenergy",
            name="self_consumed_biogas_or_biomethane_kwh",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
