# Generated by Django 5.2.2 on 2026-02-03 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0035_biomethaneenergy_self_consumed_biogas_or_biomethane_kwh"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biomethaneenergy",
            name="injected_biomethane_nm3_per_year",
        ),
        migrations.RemoveField(
            model_name="biomethaneenergy",
            name="operating_hours",
        ),
    ]
