# Generated by Django 5.2.2 on 2026-02-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0035_biomethaneenergy_self_consumed_biogas_or_biomethane_kwh"),
        ("transactions", "0016_alter_site_site_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="city",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="company_address",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="id",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="producer",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="siret_number",
        ),
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="unit_name",
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="site_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="transactions.site",
            ),
            preserve_default=False,
        ),
    ]
