# Generated by Django 5.2.2 on 2026-02-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0036_remove_biomethaneenergy_injected_biomethane_nm3_per_year_and_more"),
        ("core", "0061_matierepremiere_classification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biomethanesupplyinput",
            name="input_category",
        ),
        migrations.RemoveField(
            model_name="biomethanesupplyinput",
            name="input_type",
        ),
        migrations.AddField(
            model_name="biomethanesupplyinput",
            name="input_name",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.MatierePremiere"),
        ),
    ]
