# Generated by Django 5.2.2 on 2026-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0036_remove_biomethaneenergy_injected_biomethane_nm3_per_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biomethaneproductionunit",
            name="digestate_sale_type",
        ),
        migrations.AddField(
            model_name="biomethaneproductionunit",
            name="digestate_sale_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
