# Generated by Django 5.2.2 on 2026-02-11 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0037_remove_biomethaneproductionunit_digestate_sale_type_and_more"),
        ("biomethane", "0037_remove_biomethanesupplyinput_input_category_and_more"),
    ]

    operations = []
