# Generated by Django 5.2.2 on 2026-02-23 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0039_convert_biomethaneproductionunit_to_site_inheritance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biomethanecontract",
            old_name="general_conditions_file",
            new_name="conditions_file",
        ),
        migrations.RemoveField(
            model_name="biomethanecontract",
            name="specific_conditions_file",
        ),
    ]
