# Generated by Django 5.2.2 on 2026-02-18 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0040_move_declarationperiod_to_core"),
        ("core", "0065_alter_declarationperiod_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneDeclarationPeriod",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.declarationperiod",),
        ),
    ]
