# Generated by Django 5.2.2 on 2026-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0040_rename_general_conditions_file_biomethanecontract_conditions_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanecontract",
            name="tracked_amendment_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
