# Generated by Django 5.2.2 on 2026-02-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0041_alter_biomethanecontract_tracked_amendment_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGRICULTURAL_AUTONOMOUS", "Agricole autonome"),
                    ("AGRICULTURAL_TERRITORIAL", "Agricole territorial"),
                    ("INDUSTRIAL_TERRITORIAL", "Industriel territorial"),
                    ("HOUSEHOLD_WASTE_BIOWASTE", "Déchets ménagers et biodéchets"),
                    ("STEP", "STEP"),
                    ("ISDND", "ISDND"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
