# Generated by Django 5.2.2 on 2026-02-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0042_alter_biomethaneproductionunit_unit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethanesupplyinput",
            name="type_cive",
            field=models.CharField(blank=True, choices=[("SUMMER", "Été"), ("WINTER", "Hiver")], max_length=10, null=True),
        ),
    ]
