# Generated by Django 5.2.2 on 2026-02-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0042_alter_biomethaneproductionunit_unit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethanesupplyinput",
            name="type_cive",
            field=models.CharField(blank=True, choices=[("SUMMER", "Été"), ("WINTER", "Hiver")], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="biomethanesupplyinput",
            name="culture_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="biomethanesupplyinput",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE", "Issus de collecteurs privés"),
                    ("LOCAL", "Issus de collectivités locales"),
                    ("BOTH", "Issus des collectivités locales et collecteurs privés"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="biomethanesupplyinput",
            old_name="input_name",
            new_name="feedstock",
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="biomethanesupplyinput",
            name="source",
        ),
        migrations.RemoveField(
            model_name="biomethanesupplyinput",
            name="crop_type",
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="material_unit",
            field=models.CharField(blank=True, choices=[("DRY", "Sèche"), ("WET", "Brute")], max_length=5, null=True),
        ),
    ]
