# Generated by Django 5.2.2 on 2026-03-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0043_add_type_cive_to_supply_input_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[("PRIVATE", "Issus de collecteurs privés"), ("LOCAL", "Issus de collectivités locales")],
                max_length=10,
                null=True,
            ),
        ),
    ]
