# Generated by Django 5.2.2 on 2026-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0043_add_type_cive_to_supply_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethanesupplyinput",
            name="culture_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
