# Generated by Django 5.2.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0043_add_type_cive_to_supply_input_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethanesupplyinput",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("INTERNAL", "Interne"), ("EXTERNAL", "Externe")],
                max_length=10,
                null=True,
            ),
        ),
    ]
