# Generated by Django 5.2.2 on 2026-03-02 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0044_add_source_to_biomethanesupplyinput"),
        ("biomethane", "0044_alter_biomethanesupplyinput_collection_type"),
    ]

    operations = []
