# Generated by Django 5.2.2 on 2026-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0044_add_culture_details_to_supply_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomethanesupplyinput",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE", "Issus de collecteurs privés"),
                    ("LOCAL", "Issus de collectivités locales"),
                    ("BOTH", "Issus des collectivités locales et collecteurs privés"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
