# Generated by Django 5.2.2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0045_add_collection_type_to_supply_input"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biomethanesupplyinput",
            old_name="input_name",
            new_name="feedstock",
        ),
    ]
