# Generated by Django 5.2.2 on 2026-03-04 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0045_biomethanedeclarationperiod"),
        ("biomethane", "0045_merge_20260302_1413"),
    ]

    operations = []
