# Generated by Django 5.2.2 on 2026-02-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0046_rename_input_name_to_feedstock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
