# Generated by Django 5.2.2 on 2026-04-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0047_biomethanedeclarationperiod"),
        ("core", "0069_alter_declarationperiod_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanecontract",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer",
                to="core.entity",
                verbose_name="Acheteur",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="cmax",
            field=models.FloatField(blank=True, null=True, verbose_name="Cmax (Nm³/h)"),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="cmax_annualized",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Annualisation du contrôle de la Cmax"
            ),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="cmax_annualized_value",
            field=models.FloatField(blank=True, null=True, verbose_name="Cmax annualisée (GWhPCS/an)"),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="complementary_aid_organisms",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Aide complémentaire attribuée par"),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="complementary_aid_other_organism_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Précisez le nom du ou des organismes publics ayant octroyé l'aide",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="effective_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de prise d'effet"),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="has_complementary_investment_aid",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name=(
                    "Est-ce que votre installation a bénéficié d'une ou plusieurs "
                    "aide(s) complémentaire(s) à l'investissement?"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="installation_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTALLATION_CATEGORY_1", "INSTALLATION_CATEGORY_1"),
                    ("INSTALLATION_CATEGORY_2", "INSTALLATION_CATEGORY_2"),
                    ("INSTALLATION_CATEGORY_3", "INSTALLATION_CATEGORY_3"),
                ],
                max_length=32,
                null=True,
                verbose_name="Catégorie d'installation",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="pap_contracted",
            field=models.FloatField(blank=True, null=True, verbose_name="PAP contractualisée (GWhPCS/an)"),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="signature_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de signature"),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="tariff_reference",
            field=models.CharField(
                blank=True,
                choices=[("2011", "2011"), ("2020", "2020"), ("2021", "2021"), ("2023", "2023")],
                max_length=28,
                null=True,
                verbose_name="Référence de l'arrêté tarifaire",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="acquiring_companies",
            field=models.TextField(blank=True, null=True, verbose_name="Entreprise(s) acquérant le digestat"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="annual_eliminated_volume",
            field=models.FloatField(blank=True, null=True, verbose_name="Volume annuel éliminé (t)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="average_spreading_valorization_distance",
            field=models.FloatField(blank=True, null=True, verbose_name="Distance moyenne de valorisation d'épandage (km)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="composting_locations",
            field=models.JSONField(default=list, verbose_name="Lieu du compostage"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="external_platform_department",
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name="Département de la plateforme externe"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="external_platform_digestate_volume",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Volume de digestat composté sur la plateforme externe (t)"
            ),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="external_platform_municipality",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Commune de la plateforme externe"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="external_platform_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de la plateforme externe"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="incinerator_landfill_center_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Indiquer le nom de l'incinérateur ou du centre d'enfouissement",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="liquid_digestate_quantity",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantité digestat liquide (t)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="on_site_composted_digestate_volume",
            field=models.FloatField(blank=True, null=True, verbose_name="Volume de digestat composté sur site (t)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="raw_digestate_dry_matter_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="Taux de MS du digestat brut (%)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="raw_digestate_tonnage_produced",
            field=models.FloatField(blank=True, null=True, verbose_name="Tonnage digestat brut produit (t)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="sold_volume",
            field=models.FloatField(blank=True, null=True, verbose_name="Volume vendu (t)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="solid_digestate_tonnage",
            field=models.FloatField(blank=True, null=True, verbose_name="Tonnage de digestat solide (t)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="wwtp_materials_to_incineration",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Quantité de matières totales traitées par la STEP allant en incinération (t)",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="year",
            field=models.IntegerField(verbose_name="Année"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestatespreading",
            name="spread_parcels_area",
            field=models.FloatField(verbose_name="Superficie des parcelles épandues (ha)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestatespreading",
            name="spread_quantity",
            field=models.FloatField(verbose_name="Quantité épandue (t)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestatespreading",
            name="spreading_department",
            field=models.CharField(max_length=3, verbose_name="Département d'épandage"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestatestorage",
            name="capacity",
            field=models.FloatField(verbose_name="Capacité de stockage (m3)"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestatestorage",
            name="has_biogas_recovery",
            field=models.BooleanField(default=False, verbose_name="Récupération du biogaz"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestatestorage",
            name="has_cover",
            field=models.BooleanField(default=False, verbose_name="Couverture du stockage"),
        ),
        migrations.AlterField(
            model_name="biomethanedigestatestorage",
            name="type",
            field=models.CharField(max_length=32, verbose_name="Type de stockage"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="attest_no_fossil_for_energy",
            field=models.BooleanField(
                default=False,
                verbose_name=(
                    "J'atteste que les besoins en énergie cités ci-dessus ne sont pas satisfaits "
                    "par une énergie d'origine fossile"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="butane_or_propane_addition",
            field=models.BooleanField(
                default=False, verbose_name="Addition de butane ou propane lors de l'injection du biométhane dans le réseau"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="energy_details",
            field=models.TextField(blank=True, null=True, verbose_name="Précisions"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="energy_types",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Nature de l'énergie utilisée pour les besoins de l'installation",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="estimated_work_days_acceptability",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre d'ETP estimé pour l'activité de méthanisation sur l'année"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="flared_biogas_nm3_per_year",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantité de biogaz torché (Nm3/an)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="flaring_operating_hours",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nombre d'heures de fonctionnement de la torchère (h)"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="fossil_fuel_consumed_kwh",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantité de combustible fossile consommé (kWh)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="has_injection_difficulties_due_to_network_saturation",
            field=models.BooleanField(
                default=False,
                verbose_name=(
                    "Difficultés pour l'injection dans le réseau de gaz en raison de périodes de saturation des réseaux"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="has_malfunctions",
            field=models.BooleanField(default=False, verbose_name="Y'a t-il eu des dysfonctionnements ?"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="has_opposition_or_complaints_acceptability",
            field=models.BooleanField(
                default=False,
                verbose_name=(
                    "L'exploitation de votre unité de méthanisation fait-elle l'objet "
                    "actuellement d'une opposition ou de plaintes de voisinage ?"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="injected_biomethane_ch4_rate_percent",
            field=models.FloatField(blank=True, null=True, verbose_name="Taux de CH4 dans le biométhane injecté (%)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="injected_biomethane_gwh_pcs_per_year",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantité de biométhane injecté (GWhPCS/an)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="injected_biomethane_pcs_kwh_per_nm3",
            field=models.FloatField(blank=True, null=True, verbose_name="PCS du biométhane injecté (kWh/Nm3)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="injection_impossibility_hours",
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'heures d'impossibilité d'injection (h)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="malfunction_cumulative_duration_days",
            field=models.IntegerField(blank=True, null=True, verbose_name="Durée cumulée du dysfonctionnement (en jours)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="malfunction_details",
            field=models.TextField(blank=True, null=True, verbose_name="Précisions sur les dysfonctionnements"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="malfunction_types",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Types de dysfonctionnement"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="produced_biogas_nm3_per_year",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantité de biogaz produit (Nm3/an)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="total_unit_electric_consumption_kwe",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Consommation électrique soutirée pour l'ensemble de l'unité (kWe)"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="year",
            field=models.IntegerField(verbose_name="Année"),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Commune"),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="company_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Adresse du site d'injection (Numéro et rue)"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="is_different_from_production_site",
            field=models.BooleanField(default=False, verbose_name="Le site d'injection est différent du site de production"),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="is_shared_injection_site",
            field=models.BooleanField(default=False, verbose_name="Raccordement à un site d'injection mutualisé"),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="meter_number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="N° de compteur associé au site d'injection"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="network_manager_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom du gestionnaire de réseau"),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="network_type",
            field=models.CharField(
                blank=True,
                choices=[("TRANSPORT", "Transport"), ("DISTRIBUTION", "Dristribution")],
                max_length=32,
                null=True,
                verbose_name="Type de réseau",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="biomethaneinjectionsite",
            name="unique_identification_number",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Numéro d'identifiant unique du site d'injection"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.department",
                verbose_name="Département",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="digestate_sale_types",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Sous quel(s) statut(s) est valorisé le digestat ?"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="digestate_valorization_methods",
            field=models.JSONField(blank=True, default=list, verbose_name="Mode de valorisation du digestat"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="has_co2_valorization_process",
            field=models.BooleanField(default=False, verbose_name="Existence d'un procédé de valorisation du CO2 ?"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="has_digestate_phase_separation",
            field=models.BooleanField(default=False, verbose_name="Le digestat subit-il une séparation de phase?"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="has_hygienization_exemption",
            field=models.BooleanField(default=False, verbose_name="Disposez vous d'une dérogation à l'hygiénisation?"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="has_hygienization_unit",
            field=models.BooleanField(default=False, verbose_name="Présence d'un hygiénisateur"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="has_sanitary_approval",
            field=models.BooleanField(default=False, verbose_name="Votre site dispose-t-il d'un agrément sanitaire ?"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="hygienization_exemption_type",
            field=models.CharField(
                blank=True,
                choices=[("TOTAL", "Totale"), ("PARTIAL", "Partielle")],
                max_length=16,
                null=True,
                verbose_name="Si oui, dérogation à l'hygiénisation :",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="icpe_number",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="N° ICPE"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="icpe_regime",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTHORIZATION", "Autorisation"),
                    ("REGISTRATION", "Enregistrement"),
                    ("DECLARATION_PERIODIC_CONTROLS", "Déclaration (avec contrôles périodiques)"),
                ],
                max_length=32,
                null=True,
                verbose_name="Régime ICPE",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="insee_code",
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name="Code INSEE"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="installed_meters",
            field=models.JSONField(blank=True, default=list, verbose_name="Débitmètre présent sur votre installation"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="liquid_phase_treatment_steps",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Étape(s) complémentaire(s) de traitement de la phase liquide",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="methanization_process",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTINUOUS_INFINITELY_MIXED", "Continu (infiniment mélangé)"),
                    ("PLUG_FLOW_SEMI_CONTINUOUS", "En piston (semi-continu)"),
                    ("BATCH_SILOS", "En silos (batch)"),
                ],
                max_length=32,
                null=True,
                verbose_name="Procédé méthanisation",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="process_type",
            field=models.CharField(
                blank=True,
                choices=[("LIQUID_PROCESS", "Voie liquide"), ("DRY_PROCESS", "Voie sèche")],
                max_length=16,
                null=True,
                verbose_name="Type de voie",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="production_efficiency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Rendement moyen de l'épurateur de l'installation (%)"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="raw_digestate_treatment_steps",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Étapes complémentaires de traitement du digestat brut"
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="sanitary_approval_number",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="N° Agrément sanitaire"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="solid_phase_treatment_steps",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Étape(s) complémentaire(s) de traitement de la phase solide",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="spreading_management_methods",
            field=models.JSONField(blank=True, default=list, verbose_name="Gestion de l'épandage"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGRICULTURAL_AUTONOMOUS", "Agricole autonome"),
                    ("AGRICULTURAL_TERRITORIAL", "Agricole territorial"),
                    ("INDUSTRIAL_TERRITORIAL", "Industriel territorial"),
                    ("HOUSEHOLD_WASTE_BIOWASTE", "Déchets ménagers et biodéchets"),
                    ("STEP", "STEP"),
                    ("ISDND", "ISDND"),
                ],
                max_length=32,
                null=True,
                verbose_name="Type d'installation",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="average_weighted_distance_km",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Distance moyenne pondérée d'approvisionnement (km)"
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[("PRIVATE", "Issus de collecteurs privés"), ("LOCAL", "Issus de collectivités locales")],
                max_length=10,
                null=True,
                verbose_name="Type de collecte",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="culture_details",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Précisez la culture"),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="dry_matter_ratio_percent",
            field=models.FloatField(blank=True, null=True, verbose_name="Ratio de matière sèche - tMS/tMS (%)"),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="feedstock",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.matierepremiere", verbose_name="Intrant"
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="material_unit",
            field=models.CharField(
                blank=True,
                choices=[("DRY", "Sèche"), ("WET", "Brute")],
                max_length=5,
                null=True,
                verbose_name="Unité matière",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="maximum_distance_km",
            field=models.FloatField(blank=True, null=True, verbose_name="Distance maximale (km)"),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="origin_country",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.pays", verbose_name="Pays d'origine"
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="origin_department",
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name="Département d'origine"),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("INTERNAL", "Interne"), ("EXTERNAL", "Externe")],
                max_length=10,
                null=True,
                verbose_name="Provenance",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="type_cive",
            field=models.CharField(
                blank=True,
                choices=[("SUMMER", "Été"), ("WINTER", "Hiver")],
                max_length=10,
                null=True,
                verbose_name="Type de CIVE",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="volume",
            field=models.FloatField(blank=True, null=True, verbose_name="Tonnage"),
        ),
    ]
