# Generated by Django 5.2.2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0047_alter_biomethanesupplyinput_volume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biomethanesupplyinput",
            name="source",
        ),
        migrations.RemoveField(
            model_name="biomethanesupplyinput",
            name="crop_type",
        ),
    ]
