# Generated by Django 5.2.2 on 2026-06-17 11:43

from django.db import migrations, models

import core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0048_alter_biomethanecontract_buyer_and_more"),
        ("core", "0072_change_feedstock_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanecontract",
            name="complementary_aid_organisms",
            field=core.models.fields.JSONChoiceField(
                blank=True,
                choices=[("ADEME", "Ademe"), ("REGION", "Région"), ("OTHER", "Autre")],
                default=list,
                null=True,
                verbose_name="Aide complémentaire attribuée par",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanecontract",
            name="installation_category",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "INSTALLATION_CATEGORY_1",
                        "Méthanisation en digesteur de produits ou déchets non dangereux, hors matières résultant du traitement des eaux usées urbaines ou industrielles",  # noqa: E501
                    ),
                    (
                        "INSTALLATION_CATEGORY_2",
                        "Méthanisation en digesteur de produits ou déchets non dangereux, y compris des matières résultant du traitement des eaux usées urbaines ou industrielles",  # noqa: E501
                    ),
                    (
                        "INSTALLATION_CATEGORY_3",
                        "Installations de stockage de déchets non dangereux à partir de déchets ménagers et assimilés",
                    ),
                ],
                max_length=32,
                null=True,
                verbose_name="Catégorie d'installation",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanedigestate",
            name="composting_locations",
            field=core.models.fields.JSONChoiceField(
                choices=[("ON_SITE", "Sur site"), ("EXTERNAL_PLATFORM", "Plateforme externe")],
                default=list,
                verbose_name="Lieu du compostage",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="energy_types",
            field=core.models.fields.JSONChoiceField(
                blank=True,
                choices=[
                    ("PRODUCED_BIOGAS", "Biogaz produit par l'installation"),
                    ("PRODUCED_BIOMETHANE", "Biométhane produit par l'installation"),
                    (
                        "WASTE_HEAT_PREEXISTING",
                        "Chaleur fatale [Energie thermique résiduelle] (issue d'un équipement préexistant installé sur site ou sur un site situé à proximité)",  # noqa: E501
                    ),
                    (
                        "WASTE_HEAT_PURIFICATION",
                        "Chaleur fatale (issue du système d'épuration ou de compression de l'installation)",
                    ),
                    ("WASTE_HEAT_ON_SITE", "Chaleur fatale (issue d'un équipement installé sur site)"),
                    ("BIOMASS_BOILER", "Chaudière biomasse"),
                    ("SOLAR_THERMAL", "Solaire thermique"),
                    ("OTHER_RENEWABLE", "Autre énergie renouvelable"),
                    ("FOSSIL", "Energie fossile"),
                    ("OTHER", "Autre"),
                ],
                default=list,
                null=True,
                verbose_name="Nature de l'énergie utilisée pour les besoins de l'installation",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="malfunction_types",
            field=core.models.fields.JSONChoiceField(
                blank=True,
                choices=[
                    ("CONCEPTION", "Conception"),
                    ("MAINTENANCE", "Entretien/Maintenance"),
                    ("BIOLOGICAL", "Biologique"),
                    ("ACCIDENT", "Accident deversement"),
                    ("PURIFIER", "Épurateur"),
                    ("INJECTION_POST", "Poste d'injection (autre que problématiques de saturation des réseaux)"),
                    ("INPUTS", "Intrants"),
                    ("OTHER", "Autres (à préciser)"),
                ],
                default=list,
                null=True,
                verbose_name="Types de dysfonctionnement",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="purification_electric_consumption_kwe",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Consommation électrique du système d'épuration et le cas échéant du traitement des évents (kWe)",  # noqa: E501
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="purified_biogas_quantity_nm3",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Quantité totale de biogaz traitée par le système d'épuration sur l’année (Nm3)",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="self_consumed_biogas_nm3",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Quantité de biogaz autoconsommée pour la pasteurisation, l'hygiénisation ou le traitement des intrants, le chauffage du digesteur et l'épuration du biogaz (Nm3)",  # noqa: E501
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergy",
            name="self_consumed_biogas_or_biomethane_kwh",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Quantité de biogaz/biométhane autoconsommée pour le chauffage du digesteur (kWh) ou pour la pasteurisation, l'hygiénisation et le prétraitement des intrants, le chauffage du digesteur et l'épuration (kWh) selon la référence tarifaire",  # noqa: E501
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneenergymonthlyreport",
            name="average_monthly_flow_nm3_per_hour",
            field=models.FloatField(default=0, verbose_name="Débit moyen mensuel (Nm3/h)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergymonthlyreport",
            name="injected_volume_nm3",
            field=models.FloatField(default=0, verbose_name="Volume injecté (Nm3)"),
        ),
        migrations.AlterField(
            model_name="biomethaneenergymonthlyreport",
            name="month",
            field=models.IntegerField(verbose_name="Mois"),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="digestate_sale_types",
            field=core.models.fields.JSONChoiceField(
                blank=True,
                choices=[
                    ("SPREADING_PLAN_ICPE", "Plan d'épandage (ICPE)"),
                    ("AMM", "Autorisation de mise sur le marché (AMM)"),
                    ("MANDATORY_STANDARD", "Norme rendue d'application obligatoire"),
                    ("EU_FERTILIZER_REGULATION", "Règlement européen sur les fertilisants"),
                    ("CDC_DIG", "Cahier des Charges CDC Dig"),
                ],
                default=list,
                verbose_name="Sous quel(s) statut(s) est valorisé le digestat ?",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="digestate_valorization_methods",
            field=core.models.fields.JSONChoiceField(
                blank=True,
                choices=[
                    ("SPREADING", "Épandage"),
                    ("COMPOSTING", "Compostage"),
                    ("INCINERATION_LANDFILLING", "Incinération / Enfouissement"),
                ],
                default=list,
                verbose_name="Mode de valorisation du digestat",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="installed_meters",
            field=core.models.fields.JSONChoiceField(
                blank=True,
                choices=[
                    ("BIOGAS_PRODUCTION_FLOWMETER", "Débitmètre dédié à la production de biogaz"),
                    ("PURIFICATION_FLOWMETER", "Débitmètre dédié au volume de biogaz traité en épuration"),
                    ("FLARING_FLOWMETER", "Débitmètre dédié au volume de biogaz torché"),
                    (
                        "HEATING_FLOWMETER",
                        "Débitmètre dédié au volume de biogaz ou biométhane utilisé pour le chauffage du digesteur",
                    ),
                    (
                        "PURIFICATION_ELECTRICAL_METER",
                        "Compteur dédié à la consommation électrique au système d'épuration et traitement des évents",
                    ),
                    (
                        "GLOBAL_ELECTRICAL_METER",
                        "Compteur dédié à la consommation électrique de l'ensemble de l'unité de production",
                    ),
                ],
                default=list,
                verbose_name="Débitmètre présent sur votre installation",
            ),
        ),
        migrations.AlterField(
            model_name="biomethaneproductionunit",
            name="spreading_management_methods",
            field=core.models.fields.JSONChoiceField(
                blank=True,
                choices=[
                    ("DIRECT_SPREADING", "Épandage direct"),
                    ("SPREADING_VIA_PROVIDER", "Épandage via un prestataire"),
                    ("TRANSFER", "Cession"),
                    ("SALE", "Vente"),
                ],
                default=list,
                verbose_name="Gestion de l'épandage",
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="average_weighted_distance_km",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Distance moyenne pondérée d'approvisionnement (Km)"
            ),
        ),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="maximum_distance_km",
            field=models.FloatField(blank=True, null=True, verbose_name="Distance maximale (Km)"),
        ),
    ]
