# Generated by Django 5.2.2 on 2026-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0049_alter_biomethanecontract_complementary_aid_organisms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="dry_matter_ratio_percent",
            field=models.FloatField(blank=True, null=True, verbose_name="Ratio de matière sèche (%)"),
        ),
    ]
