# Generated by Django 5.2.2 on 2026-06-02 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0049_alter_biomethanecontract_complementary_aid_organisms_and_more"),
        ("core", "0072_change_feedstock_collation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomethaneFeedstockTariffCoefficient",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("AT_2011", "Tariff decree reference 2011"),
                            ("AT_2020_PLUS", "Tariff decree reference 2020/21/23"),
                        ],
                        max_length=16,
                        verbose_name="Tariff decree regime",
                    ),
                ),
                (
                    "coefficient",
                    models.CharField(
                        choices=[("P1", "P1"), ("P2", "P2"), ("P3", "P3"), ("P", "P"), ("PEFF", "Peff")],
                        max_length=4,
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "feedstock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_coefficients",
                        to="core.matierepremiere",
                        verbose_name="Feedstock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedstock tariff coefficient",
                "verbose_name_plural": "Feedstock tariff coefficients",
                "db_table": "biomethane_feedstock_tariff_coefficient",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feedstock", "regime"),
                        name="unique_feedstock_tariff_coefficient_regime",
                    ),
                ],
            },
        ),
    ]
