# Generated by Django 5.2.2 on 2026-08-03 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0050_alter_biomethanesupplyinput_dry_matter_ratio_percent"),
        ("biomethane", "0051_alter_feedstock_tariff_coefficient_pef"),
    ]

    operations = []
