# Generated by Django 5.2.2 on 2026-08-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0052_merge_20260803_0720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE", "Issus de collecteurs privés"),
                    ("LOCAL", "Issus de collectivités locales"),
                    ("IAA", "Issus de résidus d'IAA"),
                ],
                max_length=10,
                null=True,
                verbose_name="Type de collecte",
            ),
        ),
    ]
