# Generated by Django 5.2.2 on 2026-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0053_alter_biomethanesupplyinput_collection_type"),
        ("core", "0075_alter_genericcertificate_certificate_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="biomethanefeedstocktariffcoefficient",
            name="unique_feedstock_tariff_coefficient_regime",
        ),
        migrations.AddField(
            model_name="biomethanefeedstocktariffcoefficient",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE", "Issus de collecteurs privés"),
                    ("LOCAL", "Issus de collectivités locales"),
                    ("IAA", "Issus de résidus d'IAA"),
                ],
                default="",
                max_length=10,
                verbose_name="Type de collecte",
            ),
        ),
        migrations.AddConstraint(
            model_name="biomethanefeedstocktariffcoefficient",
            constraint=models.UniqueConstraint(
                fields=("feedstock", "regime", "collection_type"),
                name="unique_feedstock_tariff_coefficient_regime_collection",
            ),
        ),
    ]
