# Generated by Django 5.2.2 on 2026-08-04 06:33

from django.db import migrations, models


def null_collection_type_to_empty_string(apps, schema_editor):
    BiomethaneSupplyInput = apps.get_model("biomethane", "BiomethaneSupplyInput")
    BiomethaneSupplyInput.objects.filter(collection_type__isnull=True).update(collection_type="")


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0054_feedstock_tariff_coefficient_collection_type"),
    ]

    operations = [
        migrations.RunPython(null_collection_type_to_empty_string, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="biomethanesupplyinput",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE", "Issus de collecteurs privés"),
                    ("LOCAL", "Issus de collectivités locales"),
                    ("IAA", "Issus de résidus d'IAA"),
                ],
                default="",
                max_length=10,
                verbose_name="Type de collecte",
            ),
        ),
    ]
