# Generated by Django 5.2.2 on 2026-08-24 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biomethane", "0054_biomethaneannualdeclaration_submission_date"),
        ("biomethane", "0055_alter_biomethanesupplyinput_collection_type"),
    ]

    operations = []
